### ISSUE TITLE
Item duplication bug

### ISSUE THREAD

**Issue by tjd2** [ScreamingSandals/BedWars#100]
#### Describe the bug
When player is last one in the arena (he wins or someone else leaves), he can select one item in the inventory. The item then isn't despawned and player can keep it after being teleported. This is pretty big issue, as it allows player to keep some pretty good stuff.

Possible solution. Clear player's cursor slot whenever he leaves arena (either with command or automatically). I wanted to do this with simple Skript command, but the command reward gets executed too late. (see below)

#### Server and plugin version
Spigot version: git-Paper-219
BedWars version: BedWars-0.2.5-SNAPSHOT-423

#### Installed plugins on server (can be obtained by `/pl`)
Plugins (47): ┬AAC┬, ┬AdvancedPortals┬, ┬AsyncWorldEdit┬, ┬AuthMe┬, ┬BedWars┬, ┬
ChatControl┬, ┬ChestShop┬, ┬CS-CoreLib┬, ┬DeepVanish┬, ┬Duels┬, ┬EntityTrackerFi
xer┬, ┬Essentials┬, ┬EssentialsChat┬, ┬EssentialsSpawn┬, ┬FarmLimiter┬, ┬ID-Libr
ary┬, ┬KillerMoney*┬, ┬LimitPillagers┬, ┬LogBlock┬, ┬LuckPerms┬, ┬MaxBansPlus*┬,
 ┬MineResetLite┬, ┬MobArena┬, ┬Multiverse-Core┬, ┬NerfPhantoms┬, ┬NoPlugins┬, ┬P
luginConstructorAPI┬, ┬PluginManager┬, ┬ProtocolLib┬, ┬ProtocolSupport┬, ┬Reside
nce┬, ┬ServerlistMOTD*┬, ┬ServerRestorer┬, ┬SkinsRestorer┬, ┬Skript┬, ┬Skywars*┬
, ┬sleep-most*┬, ┬Slimefun┬, ┬SpigotPing*┬, ┬Spleef*┬, ┬TrollBoss┬, ┬Vault┬, ┬Vo
idGenerator┬, ┬Votifier┬, ┬VotingPlugin┬, ┬WorldBorder┬, ┬WorldEdit
#### Console log
No log for this
#### Configuration (of config.yml and shop.yml)
This shows, how i added the command to be executed (it's the /cslot one). It gets executed too late, so player can quickly put his item back in inventory after being teleported.
rewards:
  enabled: true
  player-win:
  - /example {player} 200
  player-end-game:
  - /cslot {player}
  player-destroy-bed:
  - /example {player} {score}
  player-kill:
  - /example {player} 10

**Comment by iamceph** [comment]
Thanks for reporting, I will fix it today

**Comment by tjd2** [comment]
Thanks!

**Comment by iamceph** [comment]
Should be fixed in 0.2.7
