### ISSUE TITLE
Error on player connect after server start

### ISSUE THREAD

**Issue by Nety01** [ScreamingSandals/BedWars#101]
#### Describe the bug
Got that error https://pastebin.com/64vgZRQp
Probably caused by player tried to join the server too early after server start (also it was in same second as server denied the player connect)

#### Server and plugin version
Spigot version: Paper 1.13.2 latest build
BedWars version: 0.2.4

**Comment by tjd2** [comment]
I am actually getting similar errors on 1.14.4.
Sadly i'm not currently home, so i can't paste the whole error here :(

**Comment by Misat11** [comment]
Try latest build from jenkins
