### ISSUE TITLE
Allow potion effects in shop

### ISSUE THREAD

**Issue by Dunklheit** [ScreamingSandals/BedWars#105]
Allow potion effects to be bought in the shop by players. If keepinventory is enabled, the potion effect will be reapplied for time remaining upon respawn (minus time spent dead: for example 120 seconds remaining - 5 seconds respawn time for 115 seconds remaining on respawn). Allow for customizable duration including unlimited duration.

**Comment by Kexerval** [comment]
This is different than the potion items you can buy. This would be instantly applied upon purchase

**Comment by iamceph** [comment]
Sorry, missclick🙄

**Comment by iamceph** [comment]
Added in new builds
