### ISSUE TITLE
Timing logic randomly starts and stops

### ISSUE THREAD

**Issue by Dunklheit** [ScreamingSandals/BedWars#106]
#### Describe the bug
Logic on timers (game clock, resource spawners, etc) will randomly stop counting down, then start a few seconds/minutes later. Error attached **sometimes, but not always** occurs once every second. It will **always** occur every second if the game clock or resources count down, but game clock may not always count down if the error occurs.

#### Server and plugin version
Spigot version: `git-Spigot-492a779-731e819 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)`
BedWars version: `0.2.4`

#### Installed plugins on server (can be obtained by `/pl`)
`Plugins (15): LuckPerms, MaintenanceTime, WorldEdit, PluginConstructorAPI, PlaceholderAPI, Vault, PlayerParticles, ProtocolLib, Multiverse-Core, Essentials, Plan, EssentialsAntiBuild, BedWars, SuperVanish, TabList`
#### Console log
[error.txt](https://github.com/ScreamingSandals/BedWars/files/4038074/error.txt)

#### Configuration (of config.yml and shop.yml)
[config.yaml](https://github.com/ScreamingSandals/BedWars/files/4038076/config.txt)
[shop.yaml](https://github.com/ScreamingSandals/BedWars/files/4038077/shop.txt)

**Comment by Kexerval** [comment]
Please note this only occurs during active gameplay

**Comment by iamceph** [comment]
That's some weird shit, can you send the arena file too?

**Comment by Kexerval** [comment]
[swamp.yaml](https://github.com/ScreamingSandals/BedWars/files/4038092/swamp.txt)

**Comment by Misat11** [comment]
Try latest build from jenkins, if it helps:
https://jenkins.mtorus.cz/job/BedWars/

**Comment by Kexerval** [comment]
@Misat11 I will try again with my testers tomorrow and post my findings
