### ISSUE TITLE
Holograms (Statistics) not working

### ISSUE THREAD

**Issue by LiamHBest** [ScreamingSandals/BedWars#110]
The statistics holograms dosent show. You have to reload the plugin for it to show and you also have to reload it for every player, meaning for every new player that join the bedwars world lobby they wont see it until you reload the plugin. Can you fix so the holograms always show and you dont have the reload the intire plugin everytime someone joins so you can see the statistics?

//and btw is there a way to change potion effects in the shop, meaning can you make the swiftness potion, for example, only 30 seconds and have swiftness 2, because now you can only have the default values?

#### Server and plugin version
Spigot version: 1.15.2
BedWars version: 02.5

#### Installed plugins on server (can be obtained by `/pl`)
PlayerHeads, LuckPerms, AdvancedFirework, PluginConstructorAPI, WorldEdit, PlaceholderAPI, ClearLag, IP-Check, UltraCustomizer, LobbyPresents, LaggRemover, WorldGuard, Multiverse-Core, LTGlobalChat, SkinsRestorer, OldCombatMechanics, VoidGenerator, UltraPunishments, ViaVersion, Vault, ViaBackwards, GWarp, ViaRewind, LastLoginAPI, Essentials, KitPvP, GadgetsMenu, BedWars, ProtocolLib, SuperLobby, EssentialsXMPP, UltraCustomizerPlus, EssentialsChat, EssentialsGeoIP, AutoQueue, Parkour, TAB, MaintenanceSpigot, ItemJoin, SuperVanish, ChatManager, WorldGuardExtraFlags, DeluxeHub, BKCommonLib, Matrix, Skywars, Skywars-Extension

**Comment by iamceph** [comment]
Fixed in 0.2.7 release.

**Comment by kencinder** [comment]
Didn't want to open a new issue for the same thing, but this happens on 0.2.22 as well, stats hologram disappears and doesn't show for players unless you reload the plugin.

Paper 1.18.1-215
Bedwars 0.2.22

**Comment by zlataovce** [comment]
> Didn't want to open a new issue for the same thing, but this happens on 0.2.22 as well, stats hologram disappears and doesn't show for players unless you reload the plugin.
> 
> Paper 1.18.1-215
> Bedwars 0.2.22

please make a new issue with proper information, this one is very old
