### ISSUE TITLE
Charge Vault Currency to Play

### ISSUE THREAD

**Issue by AlphaDelta23** [ScreamingSandals/BedWars#111]
#### Describe the solution you'd like
The ability to charge players a fee for competing in Bedwars.

**Comment by iamceph** [comment]
Charge them after completing the game, or on join? :)

**Comment by Bbro122** [comment]
The likely answer is that he wants on join
 As that is most reasonable, though it would be interesting to make it have a gamble system too.

**Comment by zlataovce** [comment]
implemented
