### ISSUE TITLE
Resource holos dissaper after death

### ISSUE THREAD

**Issue by SirvydasS** [ScreamingSandals/BedWars#112]
#### Describe the bug
When you start play bedwars game you will see holograms above rescourse spawn, but when you die, then they dissaper for you.

#### Server and plugin version
Spigot version: Paper version git-Paper-105 (MC: 1.15.2) 
BedWars version: + BedWars +  Version: 0.2.5

**Comment by iamceph** [comment]
Fixed in 0.2.7 release.
