### ISSUE TITLE
respawn protection 

### ISSUE THREAD

**Issue by djbenbe** [ScreamingSandals/BedWars#113]
Best,
when we die 2 times in a row it happens that we get spammed all the time in the chat with respawn protection gone!
there is nothing in the logs that could lead to this error.
best regards,
Ben

Spigot version: 1.12.2
BedWars version:  0.2.5

![Knipsel](https://user-images.githubusercontent.com/12442307/75584426-00887000-5a70-11ea-898d-b7821a128215.PNG)

**Comment by Misat11** [comment]
hello,
I know you said, there's no error, but can you send us your latest.log file? also can you send us your config.yml and arena yml file?

**Comment by djbenbe** [comment]
[2020-02-27-1.log.gz](https://github.com/ScreamingSandals/BedWars/files/4270315/2020-02-27-1.log.gz)
[config.zip](https://github.com/ScreamingSandals/BedWars/files/4270317/config.zip)

**Comment by Misat11** [comment]
You have too many errors in your log file. You should resolve all this errors. The config.yml file seems good, but from errors I see, that this file was regenerated by bedwars, because your file wasn't valid (after any editing check your file with yamllint). Also I wanted log where you play bedwars game and this error happened.

**Comment by djbenbe** [comment]
have overlooked. I had seen most of [BuycraftX]

**Comment by djbenbe** [comment]
[latest.log](https://github.com/ScreamingSandals/BedWars/files/4270380/latest.log)
look we were playing again and if you die twice in succession then you have a lot of spam after each other and that does not stop. there is nothing in the logbook

**Comment by Misat11** [comment]
OK, wait few minutes and try latest build from jenkins. This build isn't fixed, but I added some logging into it.

**Comment by djbenbe** [comment]
we test it for you.

**Comment by djbenbe** [comment]
we have tested with several and we have spammed that again in chat. that happens after dying several times in succession

**Comment by Misat11** [comment]
and in console? are there any new errors?

**Comment by djbenbe** [comment]
[latest (1).log](https://github.com/ScreamingSandals/BedWars/files/4270396/latest.1.log)
I did not find an error but here you have the log file

**Comment by Misat11** [comment]
and it's always on 2 respawning or is it random?

**Comment by djbenbe** [comment]
dying randomly is the cause

**Comment by Misat11** [comment]
OK, wait few minutes for next build, it should work correctly now. (but it's just temporary fix, so let this issue opened)

**Comment by djbenbe** [comment]
ok i solved now
