### ISSUE TITLE
Server kicks if game gets set to edit mode

### ISSUE THREAD

**Issue by DevYorma** [ScreamingSandals/BedWars#116]
#### Describe the bug
When I set the only configured game to edit mode, everytime I try to join BedWars sends me back to my lobby server. After a server restart the game is enabled again.

#### Server and plugin version
Spigot version: git-Paper-243 (1.14.4)
BedWars version: 0.2.6-SNAPSHOT-444

#### Installed plugins on server (can be obtained by `/pl`)
Plugins (26): BedWars, LuckPerms, Matrix, Multiverse-Core, PlaceholderAPI, PlugMan, PremiumVanish, ProtocolLib, ReplaySystem, Skellett, Skore, Skript, skript-db, skript-mirror, Skungee, skUtilities, TAB, Tablisknu, TitleManager, TuSKe, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion*, WorldEdit, WorldGuard

#### Console log
[14:33:20] [Server thread/INFO]: Yorma issued server command: /bw admin Mermaid edit
[14:33:21] [Server thread/INFO]: Yorma lost connection: Disconnected
[14:33:42] [User Authenticator #1/INFO]: UUID of player Yorma is 8828af6c-fffc-40b0-bda5-0fbd287e86ed
[14:33:42] [Server thread/INFO]: Yorma[/87.169.160.112:43861] logged in with entity id 49 at ([WarteLobby]0.4044954430471954, 64.0, -0.45371346834846826)
[14:33:42] [Server thread/INFO]: Yorma lost connection: Disconnected

#### Configuration (of config.yml and shop.yml)
config.yml: https://hastebin.com/wenuguledo.cs
shop.yml: https://hastebin.com/saxazahoga.bash

#### If there are problem with only one game, paste here config of this game
I don't know because this is the only game I have.
Arena config: https://hastebin.com/unaxojopil.cs

**Comment by notfoundname** [comment]
after setting game to edit mode and changing some things, you must save it by using /bw admin (Arena name) save
then it will be saved and enabled

**Comment by iamceph** [comment]
This is a purpose of Bungee mode. I can make it that only players with certain permissio can join.

**Comment by DevYorma** [comment]
@notfoundname I everytime I got kicked directly. I couldn't change anything.
@iamceph Would be very helpful. Otherwise I have to disable bungee everytime I would like to edit something.

**Comment by iamceph** [comment]
Alright, I'll add it

**Comment by DevYorma** [comment]
Thank you so much.

**Comment by DevYorma** [comment]
One further idea:
An option in the config with that players will not be send to lobby server everytime the game ends.

**Comment by iamceph** [comment]
Added in latest Jenkins build, will be released today. You'll need to have "misat11.bw.admin" permissions to not get disconnected in bungee mode. :)

**Comment by DevYorma** [comment]
It works. Thank you so much. :)
