### ISSUE TITLE
Not every protection wall gets resetted (only sometimes)

### ISSUE THREAD

**Issue by DevYorma** [ScreamingSandals/BedWars#117]
#### Describe the bug
Sometimes some protection walls still persist after game end.

#### Server and plugin version
Spigot version: git-Paper-243 (1.14.4)
BedWars version: 0.2.6-SNAPSHOT-444

#### Installed plugins on server (can be obtained by `/pl`)
Plugins (26): BedWars, LuckPerms, Matrix, Multiverse-Core, PlaceholderAPI, PlugMan, PremiumVanish, ProtocolLib, ReplaySystem, Skellett, Skore, Skript, skript-db, skript-mirror, Skungee, skUtilities, TAB, Tablisknu, TitleManager, TuSKe, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion*, WorldEdit, WorldGuard

#### Console log
/

#### Configuration (of config.yml and shop.yml)
config.yml: https://hastebin.com/wenuguledo.cs
shop.yml: https://hastebin.com/saxazahoga.bash

#### If there are problem with only one game, paste here config of this game
I don't know because this is the only game I have.
Arena config: https://hastebin.com/unaxojopil.cs

**Comment by iamceph** [comment]
Tested that, never happened to me. Are there any server lags or something external?

**Comment by iamceph** [comment]
Fixed in 0.2.7 release.
