### ISSUE TITLE
trap item works not correctly

### ISSUE THREAD

**Issue by DevYorma** [ScreamingSandals/BedWars#118]
#### Describe the bug
I got a message that a caught someone in a trap, but he was still able to move (the effects he got, disappeard after a few seconds).  After that he was able to destroy the string which represents the trap.

#### Server and plugin version
Spigot version: Paper-223 (1.14.4)
BedWars version: 0.2.3-SNAPSHOT-403

#### Installed plugins on server (can be obtained by `/pl`)
Plugins (26): BedWars, LuckPerms, Matrix, Multiverse-Core, PlaceholderAPI, PlugMan, PremiumVanish, ProtocolLib, ReplaySystem, Skellett, Skore, Skript, skript-db, skript-mirror, Skungee, skUtilities, TAB, Tablisknu, TitleManager, TuSKe, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion*, WorldEdit, WorldGuard

#### Console log
/

#### Configuration (of config.yml and shop.yml)
config.yml: https://hastebin.com/ecaqawahus.cs
shop.yml: https://hastebin.com/zodawupohu.bash

#### If there are problem with only one game, paste here config of this game
I don't know because this is the only game I have.
Arena config: https://hastebin.com/unaxojopil.cs

**Comment by iamceph** [comment]
Should be fixed in 0.2.7
