### ISSUE TITLE
MoarBows Support

### ISSUE THREAD

**Issue by Kirrasio** [ScreamingSandals/BedWars#122]
#### Describe the solution you'd like
MoarBows functionality is blocked with some of the items, I would like to request the plugin have full functionality when the game is running. (it works with the game not running)
#### Is your feature request related to a problem? Please describe
Bows fire but some specialty functions do not work, like the Void bow. I can increase the list to include more bows that are broken if needed.

https://www.spigotmc.org/resources/moar-bows.36387/

**Comment by iamceph** [comment]
We will try to implement this in 1.x.x versions
