### ISSUE TITLE
Reduce amount of items

### ISSUE THREAD

**Issue by MaxOette** [ScreamingSandals/BedWars#128]
Hi so i have the problem that there are e.g. 4 Teams set up for an arena but only 2 of them are playing. The gold/iron/bronze is spawning on the 2 emty team-islands which is in my opinion unnecessary. 
So think it is better when items wont be generated on emty team items to reduce possible lag

**Comment by iamceph** [comment]
Have you added teams to the spawners? This feature is implemented.

**Comment by MaxOette** [comment]
ok but how? if i type /bw admin ARENANAME spawner add true 1 TEAMNAME there is an errormessageServer is spigot1.14.4 and BW 0.2.4
-------- Ursprüngliche Nachricht --------Von: iamceph <notifications@github.com> Datum: 02.04.20  02:24  (GMT+01:00) An: ScreamingSandals/BedWars <BedWars@noreply.github.com> Cc: MaxOette <maxoette@mail.de>, Author <author@noreply.github.com> Betreff: Re: [ScreamingSandals/BedWars] Reduce amount of items (#128) 
Have you added teams to the spawners? This feature is implemented.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ScreamingSandals/BedWars/issues/128#issuecomment-607553802",
"url": "https://github.com/ScreamingSandals/BedWars/issues/128#issuecomment-607553802",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by iamceph** [comment]
Then send the error message.

**Comment by MaxOette** [comment]
hi so i found the command to now on spigot.mc and the spanwer gets generated successfully, but: The spawners from empty teams still gererate items which causes unnecessary lag and i also have set a limit of 100 per spawner but they keep spawning every second(10s/20s) for the whole game 
-------- Ursprüngliche Nachricht --------Von: iamceph <notifications@github.com> Datum: 04.04.20  19:32  (GMT+01:00) An: ScreamingSandals/BedWars <BedWars@noreply.github.com> Cc: MaxOette <maxoette@mail.de>, Author <author@noreply.github.com> Betreff: Re: [ScreamingSandals/BedWars] Reduce amount of items (#128) 
Then send the error message.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ScreamingSandals/BedWars/issues/128#issuecomment-609062785",
"url": "https://github.com/ScreamingSandals/BedWars/issues/128#issuecomment-609062785",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by iamceph** [comment]
What BedWars version do you have

**Comment by MaxOette** [comment]
0.2.4
-------- Ursprüngliche Nachricht --------Von: iamceph <notifications@github.com> Datum: 04.04.20  19:54  (GMT+01:00) An: ScreamingSandals/BedWars <BedWars@noreply.github.com> Cc: MaxOette <maxoette@mail.de>, Author <author@noreply.github.com> Betreff: Re: [ScreamingSandals/BedWars] Reduce amount of items (#128) 
What BedWars version do you have

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ScreamingSandals/BedWars/issues/128#issuecomment-609065923",
"url": "https://github.com/ScreamingSandals/BedWars/issues/128#issuecomment-609065923",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by iamceph** [comment]
0.2.6 is latest, install it.
