### ISSUE TITLE
MariaDB Database integration ?

### ISSUE THREAD

**Issue by DerLinkman** [ScreamingSandals/BedWars#129]
Hey @Misat11,

thanks for this really awesome Bedwars plugin! We`re currently implementing it on our server.
However, I noticed that we cannot connect the plugin to a database (probably because our database is a MariaDB database?).
So I wanted to ask when the MariaDB support comes (if it is not already there)

Greetings
DerLinkman

**Comment by Misat11** [comment]
it should work, try to create database manually

CREATE TABLE IF NOT EXISTS `bw_stats_players` (`kills` int(11) NOT NULL DEFAULT '0', `wins` int(11) NOT NULL DEFAULT '0', `score` int(11) NOT NULL DEFAULT '0', `loses` int(11) NOT NULL DEFAULT '0', `name` varchar(255) NOT NULL, `destroyedBeds` int(11) NOT NULL DEFAULT '0', `uuid` varchar(255) NOT NULL, `deaths` int(11) NOT NULL DEFAULT '0', PRIMARY KEY (`uuid`))

**Comment by DerLinkman** [comment]
Ah yes, now it works! Very nice thanks a lot :D

**Comment by DerLinkman** [comment]
Well i correct my answer:
https://pastebin.com/QKhh27mz

**Comment by Misat11** [comment]
check if informations written in config.yml (part database) is correct and if yes, send me your config.yml

**Comment by DerLinkman** [comment]
Ok nevermind this message only pops up when i reload the plugin!
