### ISSUE TITLE
Removable/Addable Waiting Lobby

### ISSUE THREAD

**Issue by n1msy** [ScreamingSandals/BedWars#131]
When the game is waiting for players to join (aka when the game isn't running a match), there's a lobby for players to join to that's in the arena while waiting for players. When the game starts, the lobby is removed from the arena. During arena rebuilding, the lobby would be added back for the next round. This would be similar to saving a schematic and it's block data, using the block data to remove the waiting lobby, then using the schematic to paste it back at the same saved location of the saved schematic. Players would have to select the corner locations of the lobby, and this would be an optional feature.

**Comment by Misat11** [comment]
Implemented in snapshots of 0.3.0.
