### ISSUE TITLE
Option to Spawn with Armor Equipped

### ISSUE THREAD

**Issue by bradydee** [ScreamingSandals/BedWars#132]
The way my config is set up, I have players spawning into Bed Wars with a wooden sword and a set of leather armor. However, there is no option for the players to spawn with the armor already equipped. Instead, the armor is just put into their inventory and they have to manually put it on. If there was some way to auto-equip armor on spawn, that would be great!

**Comment by iamceph** [comment]
Added, test it with the latest Jenkins build that will be online in few minutes. :)
