### ISSUE TITLE
I can can use the signs but the players cant, they get no error either

### ISSUE THREAD

**Issue by Mr-beanGaming** [ScreamingSandals/BedWars#134]
Help please. BTW I also encountered another bug today, when I try to switch teams some times I get kicked for some weird reason it says its releated to the plugin tho

**Comment by iamceph** [comment]
This is already answered about 100 times, disable your spawn protection in server.properties or check your WorldGuard settings

**Comment by Mr-beanGaming** [comment]
If you have said it so many times, maybe write it in the front page of the
plugin so people can see it.

søn. 5. apr. 2020 kl. 16:25 skrev iamceph <notifications@github.com>:

**Comment by AmazinGreg52** [comment]
I know it is in the #FaQ on discord but do a little guide on how to fix it in the faq e.g 
Turn off spawn protection 
1.Go to server.properties
etc
