### ISSUE TITLE
Can't join any running game

### ISSUE THREAD

**Issue by Silkxn** [ScreamingSandals/BedWars#137]
I can't join any running arenas or link them to signs. It used to work before but it doesnt anymore. I verified if I wrote correctly [Bedwars] or my arena name, but it was fine. After that I tried to /bw join <arena> but it says me "[BW] You are already in some game, which of course, I am not, since i'm standing in the main lobby. After tha, i can't use any commands : "[BW] This command is blocked while the game is running"

Plugins installed: WorldEdit, SkinsRestorer, HubThat, AutoRestart,Vault, Multiverse-Core, Multiverse-Portals, PerWorldInventory, and ScreamingBedwars.

Hope you can help me! Thanks

**Comment by AmazinGreg52** [comment]
have you checked if the arena is even registered by doing /bw list And the "[BW] This command is blocked while the game is running" is just there so people who have permission to go into gamemode 1 dont cheat and use gamemode 1 etc

**Comment by Silkxn** [comment]
Thanks for answering that quickly. Yeah i checked that, and it's listed. I understand that message, but the point is that i wasnt in any gamemode, i was in the lobby

**Comment by AmazinGreg52** [comment]
In any way or form you joined the bw game it disables you from using any command except /bw <command> and I'm not sure about the 1st issue. Just wait on a response from the devs

**Comment by iamceph** [comment]
Please send us your latest.log file.

**Comment by Silkxn** [comment]
[latest.log](https://github.com/ScreamingSandals/BedWars/files/4434814/latest.log)
Here it is. Sorry for not having send it before

**Comment by AmazinGreg52** [comment]
does it just say arena disabled?

**Comment by iamceph** [comment]
It does not work because you have error in Shop.yml as it says in log: 
"9:54:14] [Server thread/ERROR]: Error occurred while enabling BedWars v0.2.6 (Is it up to date?)
java.lang.NullPointerException: null"

**Comment by Silkxn** [comment]
Where? When I enter the "/bw list" command it says me "Available Arenas: MyArena 0"

**Comment by iamceph** [comment]
I don't know what did you edited in shop, but it's done incorectly. Send it over, I will fix it for you.

**Comment by Silkxn** [comment]
It's obviously that since I edited the shop.yml. But I thought it was done correctly. Here it is:

**Comment by Silkxn** [comment]
Whoops, sorry, havent seen that github doesnt allows yml files
Going to zip it

**Comment by Silkxn** [comment]
[shop.zip](https://github.com/ScreamingSandals/BedWars/files/4434827/shop.zip)
Here.

**Comment by Silkxn** [comment]
Can i ask you to tell me where was the error?

**Comment by iamceph** [comment]
Eh, this shop file is from BedWarsRel, not from our ScreamingBedWars haha

**Comment by AmazinGreg52** [comment]
XDDD

**Comment by iamceph** [comment]
https://github.com/ScreamingSandals/BedWars/blob/master/plugin/src/main/resources/shop.yml Here is our shop file

**Comment by Silkxn** [comment]
Wait sorry. Got messed up. I will send you the correct one. Sorry x)

**Comment by Silkxn** [comment]
[shop.zip](https://github.com/ScreamingSandals/BedWars/files/4434854/shop.zip)
This is the one I edited and used on my server. Had two shop.yml on my dowload directory, sorry

**Comment by iamceph** [comment]
Alright, line 120 - you have there enchants: but with nothing below, that generates NULL as in error log, because there are expected some items to be but are nothing. Same with line 143. Delete them, it will work fine. :) Close this issue afterwards please 👾

**Comment by Silkxn** [comment]
Alright I will test it like that, i will close it if it works again! Still, huge thanks for  answering so quick. One more question, what software do you advise for yml editing?

**Comment by iamceph** [comment]
Sublime Text 3 is awesome 👍

**Comment by Silkxn** [comment]
I thought it couldn't read yml but i guess i was wrong then xD
Thanks for all

**Comment by iamceph** [comment]
You need to go to the right corner, click on it and type Y as YAML, it will select YAML as your language. :) 

![image](https://user-images.githubusercontent.com/4377405/78510058-d0c93800-7792-11ea-8d67-9b1df97fe489.png)

**Comment by Silkxn** [comment]
Hi again. The sign to join the game still doesn't work. Still can't join by the /bw join command.

**Comment by Silkxn** [comment]
Tried a fresh reinstall of the plugin. Same errors, same sign and game joining issues.

**Comment by iamceph** [comment]
This is surely not plugin's fault. Try to delete everything and see how it goes. Send the errors otherwise.
