### ISSUE TITLE
Arena deletes itself after restart.

### ISSUE THREAD

**Issue by Spinbab** [ScreamingSandals/BedWars#138]
Hello. Whenever I restart my server my arena deletes itself. I have saved it and I have the file saved to my desktop as a backup, but I have no way to load it. Please help?

I'm using Minehut, so I don't really know what version Spigot and Bedwars are on.

My plugins are: BedWars, BukkitCore. HolographicDisplays, PlayerServer, WorldEdit, WorldGuard

Config.yml is attached as a txt file

[config.txt](https://github.com/ScreamingSandals/BedWars/files/4434885/config.txt)

**Comment by iamceph** [comment]
This was confirmed issue for old BedWars version, do you have 0.2.6 installed?

**Comment by Spinbab** [comment]
I checked, I have 0.2.5. Thanks. I suppose I should download the newest version from the github and put it on Minehut?

**Comment by iamceph** [comment]
You need to have 0.2.6. You can't put your own plugins on Minehut as I know.. Ping the support to update the plugin to lastest version! :)

**Comment by Spinbab** [comment]
Ah, alright. Thank you :D
