### ISSUE TITLE
[Team Upgrades] Dev Needed?

### ISSUE THREAD

**Issue by PulseBeat02** [ScreamingSandals/BedWars#139]
Hi. This is not a feature request. I saw in your to do list that you may include team upgrades. Perhaps I could fork the project and see if I can finish the team upgrades code from there? Just for clarification purposes, I was confused when I read your team upgrades classes in the project. Could you do a quick clarification on what each class does? (If you have time, maybe explain what the methods in the class do, it’s fine if you don’t explain it. I just want to get a head start on the team upgrades section). I have coded one plugin before, however, I am very familiar with mod programming, so I think I can adjust to plugin development. Finally, I wanted to make sure and ask about what upgrades should the plugin include? I was originally thinking about sharpness, protection, etc (kinda like the Hypixel bedwars one),  but please leave your thoughts down below on what I can help with.

**Comment by PulseBeat02** [comment]
I see what you mean. In the spawner class, you have a method which adds a value to the level of the spawner.

For protection: We could check if the player interacted with the villager and upgraded the protection, and then loop through each player on the specified team and go through their inventories. We can add an enchantment by getting the ItemStack of each of the armor and use the addEnchantment method (which may be a different method alias now, but still works)

For sharpness: Basically the same thing above, but get the sword (if they have one) in the player inventory and enchant the ItemStack with sharpness.

Heal Pool/Miner Fatigue/Trap Detection: This will probably be harder to implement because we must know the bounds of each team’s island. Perhaps we can make a new command to set the bounds for each island, or we can set a radius from the team bed such that the trap/heal/miner fatigue will happen.

Boss Buff: Haven’t looked much into your boss classes yet, but I will just take a look right now.

**Comment by Misat11** [comment]
So if you want you can do a pull request with some new features. Also if you find any bugs in current version you can also make some pull request for master branch.

**Comment by PulseBeat02** [comment]
Alright, will do. I absolutely love this plugin and I can’t stop using it with my friends on my server. 😀

**Comment by iamceph** [comment]
Yo, join our Discord server if you'll want anything
