### ISSUE TITLE
Spectator issue

### ISSUE THREAD

**Issue by testificate2000** [ScreamingSandals/BedWars#142]
After game starts people are joining the game but, are not part of it, not in spectator mode, and are able to hurt the ingame players

**Comment by nicegamer7** [comment]
Do you have Multiverse installed?

**Comment by iamceph** [comment]
Multiverse issue, grant right permissions for the users.

**Comment by nicegamer7** [comment]
More specifically, `mv.bypass.gamemode.NAME`.

See https://github.com/Multiverse/Multiverse-Core/wiki/Big-List-O'-Permissions.

**Comment by nicegamer7** [comment]
Although, I do believe there is still a bug with spectators, so if you experience anything odd, please reopen this.

**Comment by iamceph** [comment]
Alot of issues been fixed with latest jenkins builds
