### ISSUE TITLE
Shop does not work

### ISSUE THREAD

**Issue by sfsfsfsfsfsfsfsfsfsafS** [ScreamingSandals/BedWars#143]
#### Describe the bug
A clear and concise description of what the bug is.is:issue is:open I tried to add stuff to my shop but it would not ley me open it so i deleted it but this time when i added something and deleted it it stopped working completely please help

#### Server and plugin version
Spigot version:1.15.2
BedWars version:newest

#### Configuration (of config.yml and shop.yml)shop config:data:
#-   stack:
#      type: GOLDEN_APPLE
#      amount: 1
#      meta:
#        ==: ItemMeta
#        meta-type: UNSPECIFIC
#        display-name: "Example category"
#        lore:
#        - "This is my category!"
#        - "Please buy things inside!"
#    items:
#    - price: 50
#      price-type: "bronze"
#      stack:
#        type: DIAMOND_SWORD
#        amount: 1
#        meta:
#          ==: ItemMeta
#          meta-type: UNSPECIFIC
#          enchants:
#            DAMAGE_ALL: 2
#          repair-cost: 1
#          Damage: 99
# Value 'applycolorbyteam' is used for automatic-coloring-in-shop.
# See WarpPowder for more info.

- stack: "DIAMOND_CHESTPLATE;1;Armor;Protect yourself with armor! Click here."
  items:
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_HELMET
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_LEGGINGS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_BOOTS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 3 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 2
   - price: 7 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 3
   - price: 10 of gold
     stack:
      type: IRON_HELMET
      display-name: Helm
      enchants:
       PROTECTION_ENVIRONMENTAL: 2
       
- stack: "DIAMOND_SWORD;1;Swords;Click here to get sword for attacking your enemies"
  column: center
  items:
   - price: 8 of bronze
     stack:
      type: STONE_SWORD
      enchants:
       DAMAGE_ALL: 2
   - price: 7 of iron
     stack:
      type: IRON_SWORD
      enchants:
       DAMAGE_ALL: 5
   - price: 3 of iron
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 2
   - price: 7 of iron
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 3
   - price: 7 of gold
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 2
       KNOCKBACK: 1
   - price: 15 of gold
     stack:
      type: GOLDEN_AXE
      display-name: "Axe of Infinity"
      enchants:
       DAMAGE_ALL: 1
       DURABILITY: 1
       KNOCKBACK: 1
       
- stack: "BOW;1;Bows;Prove yourself as a marksman with these wonderful bows"
  column: right
  items:
   - price: 3 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
   - price: 7 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_DAMAGE: 1
   - price: 13 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_DAMAGE: 2
   - price: 14 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_FIRE: 1
   - price: 15 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_FIRE: 1
       ARROW_KNOCKBACK: 1
   - ARROW for 1 of gold

- stack: "COOKED_PORKCHOP;1;Eat;Are you hungry? Get something to eat."
  row: 3
  column: 2
  items:
   - COOKED_PORKCHOP;2 for 4 of bronze
   - GOLDEN_APPLE for 2 of iron
   - BREAD;10 for 5 of gold

- stack:
   type: POTION
   meta:
    ==: ItemMeta
    meta-type: POTION
    display-name: "Drinks"
    lore:
     - "Not enough? Use these potions and you'll feel better!"
    potion-type: strength
  row: 3
  column: 6
  items:
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: healing
     price: 3 of iron
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strong_healing
     price: 5 of iron
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: swiftness
     price: 7 of iron
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strength
     price: 1 of gold
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: regeneration
     price: 3 of gold

- stack: "WHITE_WOOL;1;Blocks;Get to the others! Possible with blocks."
  linebreak: before
  items:
   - WHITE_WOOL;16 for 4 of bronze
   - END_STONE;12 for 24 of bronze
   - OAK_PLANKS;16 for 4 of iron
   - GLOWSTONE;4 for 15 of bronze
   - price: 4 of bronze
     properties: "applycolorbyteam"
     stack: GLASS

- stack: "TNT;1;Useful Stuff;Looking for useful stuff? Here are some!"
  column: center
  items:
   - CHEST for 1 of iron
   -ENDER_PEARL for 3 of gold
   - price: 7 of iron
     properties:
      - name: "WarpPowder"
        delay: 6
     stack:
      type: GUNPOWDER
      display-name: "Warp Powder"
      lore:
       - "When using this powder you'll get"
       - "teleported to you spawn point within 6 seconds"
       - "Warning: Any movement will stop the process"
   - price: 3 of iron
     properties:
      - name: "Trap"
        data:
         - sound: ENTITY_SHEEP_AMBIENT
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 15
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 18
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 2
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
     stack:
      type: STRING
      display-name: "Trap"
      lore:
       - "Get informed if an enemy steps on your trap"
       - "and your enemy won't be able to move properly."
   - price: 6 of iron
     properties:
      - name: "MagnetShoes"
        probability: 75
     stack:
      type: IRON_BOOTS
      display-name: "Magnet-Shoes"
      lore:
       - "Wear those shoes and have a 75%"
       - "chance of getting no knockback!"
   - price: 5 of iron
     properties: "Tracker"
     stack:
      type: COMPASS
      display-name: "Tracker"
      lore:
       - "Wanna know where your closest target is?"
       - "Let's try this out!"
   - price: 5 of iron
     properties:
      - name: "rescueplatform"
        delay: 5
     stack:
      type: BLAZE_ROD
      display-name: "Rescue Platform"
      lore:
       - "Protect yourself from falling into"
       - "void with a Rescue Platform."
       - "This is your last hope!"
   - price: 5 of gold
     properties:
      - name: "arrowblocker"
        delay: 5
     stack:
      type: ENDER_EYE
      display-name: "Arrow Blocker"
      lore:
       - "Block arrows that are coming"
       - "for you with black magic."
       - "I mean, with this item."
   - price: 64 of bronze
     properties:
      - name: "protectionwall"
     stack:
      type: BRICKS
      display-name: "Protection Wall"
      lore:
       - "Instantly builds a wall that"
       - "can save your life!"
   - price: 24 of iron
     properties:
      - name: "Golem"
        speed: 0.25
        follow: 16.0
     stack:
      type: GHAST_SPAWN_EGG
      display-name: "Golem"
      lore:
       - "An iron golem that will protect"
       - "your team from the enemies."
   - price: 10 of gold
     properties: "TNTSheep"
     stack:
      type: SHEEP_SPAWN_EGG
      display-name: "TNT Sheep"
      lore:
       - "Use the TNT-Sheep! It will"
       - "walk towards your closest enemy"
       - "and explode within 8 seconds!"

- stack: "DIAMOND_PICKAXE;1;Pickaxes;Destroy others blocks? Use these pickaxes."
  column: right
  items:
   - price: 4 of bronze
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 1
   - price: 2 of iron
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 2
   - price: 1 of gold
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 3

**Comment by iamceph** [comment]
Bad shop format. Invalid issue request.
