### ISSUE TITLE
Duplication Bug on death

### ISSUE THREAD

**Issue by Grizzly90** [ScreamingSandals/BedWars#148]
#### Describe the bug
While falling you open the inventory and take something with the mouse and/or put it in the crafting field. After death (we only tested:)by falling this items reappear in the inventory with the respawn. Special when putting items in the crafting-field while falling: I wasn't able to pick the items from the spawner only after opening my inventory or talking to the shop. Maybe comparable to the existing bug: #100 ? sounds like an comparable bug.

#### Server and plugin version
Spigot version: git-Spigot-e7dc2f5-a8ec1d6 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
BedWars version: 0.2.7 

#### Installed plugins on server (can be obtained by `/pl`)
CleanroomGenerator, LuckPerms, WorldEdit, AsyncWorldEdit, PlaceholderAPI, KidsTimeBoard, Vault, KidStuff, ProtocolLib, WorldGuard, Multiverse-Core, LibsDisguises, Simple_PaintBall, Plan, BedWars, Parkour, SurvivalGames, HolographicDisplays, HideAndSeek, CMI, BungeeTabListPlus, Splegg, Skywars, VillageDefense

#### Console log
No messages

#### Configuration (of config.yml and shop.yml)
config.yml
locale: de
allow-crafting: false
keep-inventory-on-death: false
in-lobby-colored-leather-by-team: true
jointeam-entity-show-name: true
friendlyfire: false
player-drops: true
join-randomly-after-lobby-timeout: true
spectator-gm3: false
prevent-killing-villagers: true
compass-enabled: true
join-randomly-on-lobby-join: false
add-wool-to-inventory-on-join: true
prevent-spawning-mobs: true
spawner-holograms: true
spawner-disable-merge: true
prevent-lobby-spawn-mobs-in-radius: 16
spawner-holo-height: 0.25
spawner-holograms-countdown: true
damage-when-player-is-not-in-arena: true
remove-unused-target-blocks: true
allow-block-falling: true
game-start-items: false
player-respawn-items: false
gived-game-start-items:
- DIRT:32
gived-player-respawn-items: []
disable-hunger: false
automatic-coloring-in-shop: true
sell-max-64-per-click-in-shop: true
destroy-placed-blocks-by-explosion: true
holo-above-bed: true
allowed-commands: []
change-allowed-commands-to-blacklist: false
bungee:
  enabled: false
  serverRestart: true
  serverStop: false
  server: hub
  auto-game-connect: false
farmBlocks:
  enable: true
  blocks: []
scoreboard:
  enable: true
  title: §a%game%§r - %time%
  bedLost: §c✘
  bedExists: §a✔
  teamTitle: '%bed%%color%%team%'
title:
  fadeIn: 0
  stay: 20
  fadeOut: 0
items:
  jointeam: PLAYER_HEAD
  leavegame: SLIME_BALL
  startgame: DIAMOND
  shopback: BARRIER
  shopcosmetic: GRAY_STAINED_GLASS_PANE
  pageback: ARROW
  pageforward: ARROW
  team-select: WHITE_WOOL
vault:
  enable: true
  reward:
    kill: 5
    win: 20
resources:
  gold:
    material: GOLD_INGOT
    color: GOLD
    name: Gold
    interval: 20
    translate: resource_gold
    spread: 1.0
  iron:
    material: IRON_INGOT
    color: GRAY
    name: Iron
    interval: 10
    translate: resource_iron
    spread: 1.0
  bronze:
    material: BRICK
    color: DARK_RED
    name: Bronze
    interval: 1
    translate: resource_bronze
    spread: 1.0
respawn:
  protection-enabled: true
  protection-time: 10
specials:
  action-bar-messages: true
  rescue-platform:
    is-breakable: false
    delay: 0
    break-time: 10
    distance: 1
    material: GLASS
  protection-wall:
    is-breakable: true
    delay: 20
    break-time: 0
    width: 5
    height: 3
    distance: 2
    material: CUT_SANDSTONE
  tnt-sheep:
    speed: 2.0
    follow-range: 10.0
    max-target-distance: 32
    explosion-time: 8
  arrow-blocker:
    protection-time: 10
    delay: 5
  warp-powder:
    teleport-time: 6
    delay: 0
  magnet-shoes:
    probability: 75
  golem:
    speed: 0.25
    follow-range: 10
    health: 20
    name-format: '%teamcolor%%team% Golem'
    show-name: true
    delay: 0
    collidable: false
  teamchest:
    turn-all-enderchests-to-teamchests: true
tnt:
  auto-ignite: false
  explosion-time: 8
sounds:
  on_bed_destroyed: ENTITY_ENDER_DRAGON_GROWL
  on_countdown: UI_BUTTON_CLICK
  on_game_start: ENTITY_PLAYER_LEVELUP
  on_team_kill: ENTITY_PLAYER_LEVELUP
  on_player_kill: ENTITY_PLAYER_BIG_FALL
  on_item_buy: ENTITY_ITEM_PICKUP
  on_upgrade_buy: ENTITY_EXPERIENCE_ORB_PICKUP
  on_respawn_cooldown_wait: UI_BUTTON_CLICK
  on_respawn_cooldown_done: ENTITY_PLAYER_LEVELUP
game-effects:
  end:
    effects:
    - ==: Firework
      flicker: false
      trail: false
      colors:
      - &id001
        ==: Color
        RED: 255
        BLUE: 255
        GREEN: 255
      fade-colors:
      - *id001
      type: BALL
    power: 1
    type: Firework
  start: {}
  kill: {}
  teamkill: {}
  lobbyjoin: {}
  lobbyleave: {}
  respawn: {}
  beddestroy: {}
  warppowdertick: {}
lobby-scoreboard:
  enabled: true
  title: §eBEDWARS
  content:
  - ' '
  - '§fKarte: §2%arena%'
  - '§fSpieler: §2%players%§f/§2%maxplayers%'
  - ' '
  - §fWarten auf Spieler ...
  - ' '
statistics:
  enabled: true
  type: yaml
  show-on-game-end: true
  bed-destroyed-kills: true
  scores:
    kill: 10
    die: 0
    win: 50
    bed-destroy: 25
    lose: 0
    record: 100
database:
  host: localhost
  port: 3306
  db: databse
  user: root
  password: secret
  table-prefix: bw_
bossbar:
  use-xp-bar: false
  lobby:
    enable: true
    color: YELLOW
    style: SEGMENTED_20
  game:
    enable: true
    color: GREEN
    style: SEGMENTED_20
holograms:
  enabled: true
  headline: Deine Your §eBEDWARS§f-Statistik
chat:
  override: true
  format: '<%teamcolor%%name%§r> '
  send-death-messages-just-in-game: true
  send-custom-death-messages: true
  default-team-chat-while-running: true
  all-chat-prefix: '@a'
  team-chat-prefix: '@t'
  all-chat: '[ALLE] '
  team-chat: '[TEAM] '
  death-chat: '[ZUSCHAUER] '
  separate-chat:
    lobby: false
    game: false
rewards:
  enabled: false
  player-win:
  - /example {player} 200
  player-end-game:
  - /example {player} {score}
  player-destroy-bed:
  - /example {player} {score}
  player-kill:
  - /example {player} 10
lore:
  generate-automatically: true
  text:
  - '§7Preis:'
  - §7%price% %resource%
  - '§7Menge:'
  - §7%amount%
sign:
- §c§l[BedWars]
- '%arena%'
- '%status%'
- '%players%'
hotbar:
  selector: 0
  color: 1
  start: 2
  leave: 8
breakable:
  enabled: false
  blocks: []
  asblacklist: false
version: 2
debug: false
allow-spectator-join: false
disable-server-message:
  player-join: false
  player-leave: false
respawn-cooldown:
  enabled: true
  time: 5
stop-team-spawners-on-die: false
leaveshortcuts:
  enabled: false
  list:
  - leave
mainlobby:
  enabled: false
  location: ''
  world: ''

shop.yml
https://pastebin.com/yfpZTUqY

**Comment by iamceph** [comment]
Please paste your shop to pastebin, not here.

**Comment by Grizzly90** [comment]
done.

**Comment by linusstretchtips** [comment]
when yall to lazy to answer back xdd. this man has been waiting for 3 months now xd

**Comment by Misat11** [comment]
> when yall to lazy to answer back xdd. this man has been waiting for 3 months now xd

I still don't know how to fix that :)

**Comment by mindw0rm** [comment]
I made a workaround (in a separate plugin that imports BedwarsAPI) that prevents klicks in the crafting grid and while falling, and also clears the inventory on respawn (to clear items that out players learned to put in the cursor slot shortly before death -- our players are mainly kids, and you can trust in them to fine _every_ littly bug that can be somehow abused):

```
  @EventHandler
  public void onInventoryClick(InventoryClickEvent e) {
    HumanEntity he = e.getWhoClicked();
    if (he instanceof Player && e.getClickedInventory() != null) {
      Player player = (Player)he;
      if (api.isPlayerPlayingAnyGame(player)) {
        switch (e.getClickedInventory().getType()) {
          case CRAFTING:
          case PLAYER:
            int raw = e.getRawSlot();
            if (!player.isOnGround() || raw >= 1 && raw <= 4)
              e.setCancelled(true);
        }
      }
    }
  }
  @EventHandler
  public void onPlayerSpawn(PlayerRespawnEvent e) {
    Player player = e.getPlayer();

    if (api.isPlayerPlayingAnyGame(player)) {
      player.getInventory().clear();
    }
  }
```
This might be a bit extreme, but does prevent the issue for us and doesn't lead to side effects or complaints so far (disclaimer: I belong to the same server team as Grizzly90).

**Comment by iamceph** [comment]
You can make Pull Request if you want :)
