### ISSUE TITLE
Bedwars loading after MyWorlds

### ISSUE THREAD

**Issue by J-SHarper** [ScreamingSandals/BedWars#149]
#### Describe the bug
Bedwars loads after MyWorlds, meaning that the world where our arenas are stored is not loaded, causing our arenas not to load on startup.

#### Server and plugin version
Paper version: 227
BedWars version: 0.27

**Comment by iamceph** [comment]
Never heard of that plugin, will check

**Comment by J-SHarper** [comment]
Thank you! Here's the link if helpful: [](https://www.spigotmc.org/resources/myworlds.39594/)

**Comment by iamceph** [comment]
I like that one, will test that plugins, seems pretty cool! Thanks!

**Comment by iamceph** [comment]
Should be fixed in latest build on our CI. Please close this issue if that is true :) 

https://ci.screamingsandals.org/job/BedWars-0.x.x/ - build 503
