### ISSUE TITLE
Maven Repository wrong URL in Wiki

### ISSUE THREAD

**Issue by mindw0rm** [ScreamingSandals/BedWars#152]
#### Describe the bug
The URL to the maven repository given in https://github.com/ScreamingSandals/BedWars/wiki is wrong.
https://jenkins.mtorus.cz/plugin/repository/everything/  redirects to https://ci.screamingsandals.org/plugin/repository/everything/ which only gives a 404. 

I was not able to guess the correct URL. Is there still a maven repository, or do I have to use the jar?

(Rest of the bug template is not relevant to this bug)

**Comment by Misat11** [comment]
Ah I forgot to change it, wait minute

**Comment by Misat11** [comment]
Ok, wiki was changed.
The current repo is https://repo.screamingsandals.org/

**Comment by mindw0rm** [comment]
Wow, that was fast!
Thanks :)
