### ISSUE TITLE
MapVoting and GoldVoting BITTE ADDET DAS IHR HABT DAS BESTE PLUGIN

### ISSUE THREAD

**Issue by gameplayema** [ScreamingSandals/BedWars#153]
Hi,
Könntet ihr für dieses tolle Plugin vielleicht ein mapvoting  und ein GoldVoting adden? Wenn man dann in die Wartelobby kommt, sollte man mit einem item dann die mal auswählen können...
Wie kann. Ich alles von Bedwarsrel importieren?
Ist tatsächlich alles gleich?
LG GameplayEmaYT

**Comment by iamceph** [comment]
We need english issue.

**Comment by gameplayema** [comment]
Can You add mapvoting?

**Comment by gameplayema** [comment]
Ist die plugin toll 100% live verräter?

**Comment by iamceph** [comment]
Just stop with that Deutch -.- And there is already issue on the map-voting thing.

**Comment by gameplayema** [comment]
Does it work in 1.8?

**Comment by gameplayema** [comment]
And how Can i import all from bedwarsrel?

**Comment by iamceph** [comment]
Nope, it does not. And you can't

**Comment by gameplayema** [comment]
> Nope, it does not. And you can't

What

**Comment by gameplayema** [comment]
Doesnt it work in 1.8!?!?

**Comment by gameplayema** [comment]
:(

**Comment by iamceph** [comment]
It does not.
