### ISSUE TITLE
Golems dont move and not attacking enemy

### ISSUE THREAD

**Issue by SirvydasS** [ScreamingSandals/BedWars#158]
#### Describe the bug
When you spawn a golem he standing in one place and doing nothing, not attacking enemies.

#### Server and plugin version
Spigot version:  Tuinity version git-Tuinity-"e4674f4" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
BedWars version: 0.2.7

**Comment by Misat11** [comment]
try latest snapshot

**Comment by wasplay** [comment]
The golem is still not working for me, even with the snapshot

**Comment by 6789012** [comment]
My Golem doesn't work either
version 1.12.2

**Comment by wasplay** [comment]
Fixed ?
