### ISSUE TITLE
Unlimited fireballs

### ISSUE THREAD

**Issue by SirvydasS** [ScreamingSandals/BedWars#159]
#### Describe the bug
If you putting fireball to the second hand - you have unlimited fireballs and you can spam.

#### Server and plugin version
Spigot version: Tuinity version git-Tuinity-"e4674f4" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
BedWars version: 0.2.7

**Comment by SirvydasS** [comment]
TNT sheep also, maybe golems too

**Comment by Misat11** [comment]
4ef8bd6afaffef97f57ce2cd0c813f93c88f4deb
