### ISSUE TITLE
Team Upgrades/Evolving Spawner Upgrade Prices

### ISSUE THREAD

**Issue by ChainBoy300** [ScreamingSandals/BedWars#162]
#### Describe the solution you'd like
It would be nice if there was team upgrades, not just for spawner upgrades but for something like....maybe enchantments? Permanent buffs? Maybe just an item that is given to everyone on the team.

Second feature request (Not sure if I should be doing it like this but yes)
Maybe add evolving spawner upgrade prices so you don't just upgrade your spawner infinitely easier with the next upgrade you might unlock.

#### Is your feature request related to a problem? Please describe
It is not related to any problems I believe.

**Comment by EpicPuppy613** [comment]
I agree with this feature, as it can make the games more interesting. This can also allow for more resources used for team upgrades.

**Comment by EpicPuppy613** [comment]
Update: Already on the to-do list

**Comment by iamceph** [comment]
Duplicate
