### ISSUE TITLE
fix hud on bedrock client

### ISSUE THREAD

**Issue by towuk118** [ScreamingSandals/BedWars#163]
#### Describe the bug
I connect from Bedrock MC to Java server (with Geyser-Bukkit plugin) CHECK videos:
Video 1 (main): https://youtu.be/dNBOH7yqXNo
Video 2 (optional): https://youtu.be/KcQSHuu_X6k

#### Server and plugin version
Spigot version: git-Spigot-2040c4c-1872231 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
BedWars version: latest (Version: 0.2.7)

#### Installed plugins on server (can be obtained by `/pl`)
Plugins (10): Geyser-Bukkit, SkinsRestorer, OldCombatMechanics, Vault, PlayerParticles, Multiverse-Core, ProtocolLib, BedWars, Essentials, AuthMe

#### Console log
[latest.log](https://github.com/ScreamingSandals/BedWars/files/4600462/latest.log)

#### Configuration (of config.yml and shop.yml)
its dont have problems!
#### If there are problem with only one game, paste here config of this game
not problems!

**Comment by iamceph** [comment]
This is unsupported plugin, we never meant to support that. So it is not a bug, but feature request. I will look into it.

**Comment by towuk118** [comment]
> This is unsupported plugin, we never meant to support that. So it is not a bug, but feature request. I will look into it.

okay, thanks

**Comment by Misat11** [comment]
If the issue happen only for bedrock players, than it's issue of the be->pc translator (in this case Geyser-Bukkit), not bedwars. Report it on their issues tracker.

**Comment by towuk118** [comment]
Is bug in Geyser-plugin
https://github.com/GeyserMC/Geyser/issues/621#issue-623478660
