### ISSUE TITLE
Join Signs change glass color

### ISSUE THREAD

**Issue by EpicPuppy613** [ScreamingSandals/BedWars#164]
#### Describe the solution you'd like
Join Signs will change glass color according to status.
ORANGE: Waiting
BLUE: Starting
GREEN: In Progress
RED: Invalid

#### Is your feature request related to a problem? Please describe
No

**Comment by iamceph** [comment]
Added in the latest dev builds, test it out. :)

**Comment by EpicPuppy613** [comment]
Ok thanks, will the signs auto detect glass behind it?

**Comment by xordos** [comment]
> 
> Ok thanks, will the signs auto detect glass behind it?
> […](#)
As I tested, the glass under and behind the sign will change color automatically once the flag(under block-behind) is turned on in config.yml
