### ISSUE TITLE
Only OPs can join using signs

### ISSUE THREAD

**Issue by MilkEnthusiast** [ScreamingSandals/BedWars#166]
#### Describe the bug
Only players with OP are able to join using signs
#### Server and plugin version
Spigot version: 1.8.8
BedWars version: Latest

#### Installed plugins on server (can be obtained by `/pl`)
LuckPerms, WorldEdit, Void2Spawn, ChestCommands, NoFall, ImageOnMap, PerWorldPlugins, ClearLag, SurvivalGames, AutoLapiz, Multiverse-Core, WorldGuard, Multiverse-Inventories, BedWars, HolographicDisplays, Multiverse-Portals, Skywars
#### Console log
None
#### Configuration (of config.yml and shop.yml)
Default (I haven't changed them at all)

**Comment by Misat11** [comment]
Move sign out of spawn protection (for example if you have in server.properties set spawn protection to 16, move 34 blocks away from spawn location) or change spawn protection to zero. Non-OP players can't do some things in spawn protection.

**Comment by iamceph** [comment]
Check FAQ on discord, disable spawn protection. And anyways, 1.8 is unsupported.
