### ISSUE TITLE
Spectators can break blocks and ruin the map

### ISSUE THREAD

**Issue by MilkEnthusiast** [ScreamingSandals/BedWars#168]
#### Describe the bug
When players lose and become spectators they are able to break the lobby and the map
#### Server and plugin version
Spigot version: 1.9
BedWars version: latest

#### Installed plugins on server (can be obtained by `/pl`)
LuckPerms, WorldEdit, Void2Spawn, ChestCommands, OpenInv, NoFall, ImageOnMap, PerWorldPlugins, ClearLag, SurvivalGames, SuperVanish, AutoLapiz, Multiverse-Core, WorldGuard, Multiverse-Inventories, BedWars, HolographicDisplays, Multiverse-Portals, Skywars

#### Configuration (of config.yml and shop.yml)
Default

**Comment by iamceph** [comment]
Multiverse permissions issue, we are setting them spectator gamemode.
