### ISSUE TITLE
What are the ids for enchants in the shop config

### ISSUE THREAD

**Issue by MilkEnthusiast** [ScreamingSandals/BedWars#169]
#### Describe the bug
unable to find the enchant ids for the shop config
#### Server and plugin version
Spigot version: 1.9
BedWars version: latest

#### Installed plugins on server (can be obtained by `/pl`)
LuckPerms, WorldEdit, Void2Spawn, NoDrop, LastLoginAPI, ChestCommands, OpenInv, NoFall, ImageOnMap, PerWorldPlugins, ClearLag, SurvivalGames, SuperVanish, AutoLapiz, Multiverse-Core, WorldGuard, BedWars, ItemJoin, HolographicDisplays, Multiverse-Portals, Skywars
#### Console log
none
#### Configuration (of config.yml and shop.yml)
default, besides trying to change bow enchants

**Comment by iamceph** [comment]
That has nothing to do with BedWars. 
Whats so hard ffs to use google. https://lmgtfy.com/?q=spigot+1.9+enchants+id
