### ISSUE TITLE
Resources spawning and immediately deleting.

### ISSUE THREAD

**Issue by gameslp** [ScreamingSandals/BedWars#170]
#### Describe the bug
Everything was working and then i added WorldGuard and TNTrun_reloaded and now items are spawning and deleting.

#### Server and plugin version
Spigot version: Latest
BedWars version: Latest

#### Installed plugins on server (can be obtained by `/pl`)
Multiverse-Core 2, TNTrun_reloaded, WorldEdit, WorldGuard

#### Configuration (of config.yml and shop.yml)

[bedwars.zip](https://github.com/ScreamingSandals/BedWars/files/4632892/bedwars.zip)

**Comment by iamceph** [comment]
Not a bedwars problem, never heard of that.
