### ISSUE TITLE
CakeWars, is cake does not appear.

### ISSUE THREAD

**Issue by 6789012** [ScreamingSandals/BedWars#171]
#### Describe the bug
I decided to make a mini game CakeWars since there can be any block but the cake was eaten in the game and it didn't appear again after the game.

#### Server and plugin version
Spigot version: 1.12.2
BedWars version: 0.2.6

**Comment by Misat11** [comment]
Wait two minutes and try latest build from jenkins, it's implementing way for disabling cake eating.

**Comment by Misat11** [comment]
Also if you want to have cake eatable (for some unknown reason) we will implement this in future.
