### ISSUE TITLE
potion types not working in shop?

### ISSUE THREAD

**Issue by MilkEnthusiast** [ScreamingSandals/BedWars#172]
#### Describe the bug
the default potions arent showing in the shop and are just water bottles
#### Server and plugin version
Spigot version: 1.9
BedWars version: latest

#### Installed plugins on server (can be obtained by `/pl`)
LuckPerms, WorldEdit, Void2Spawn, NoDrop, LastLoginAPI, ChestCommands, OpenInv, NoFall, ImageOnMap, PerWorldPlugins, ClearLag, SurvivalGames, TNTRun, SuperVanish, AutoLapiz, Multiverse-Core, FireBalls, WorldGuard, BedWars, ItemJoin, HolographicDisplays, Multiverse-Portals, Skywars
#### Console log
none
#### Configuration (of config.yml and shop.yml) (config is default)
data:
#-   stack:
#      type: GOLDEN_APPLE
#      amount: 1
#      meta:
#        ==: ItemMeta
#        meta-type: UNSPECIFIC
#        display-name: "Example category"
#        lore:
#        - "This is my category!"
#        - "Please buy things inside!"
#    items:
#    - price: 50
#      price-type: "bronze"
#      stack:
#        type: DIAMOND_SWORD
#        amount: 1
#        meta:
#          ==: ItemMeta
#          meta-type: UNSPECIFIC
#          enchants:
#            DAMAGE_ALL: 2
#          repair-cost: 1
#          Damage: 99
# Value 'applycolorbyteam' is used for automatic-coloring-in-shop.
# See WarpPowder for more info.

- stack: "DIAMOND_CHESTPLATE;1;Armor;Protect yourself with armor! Click here."
  column: 2
  row: 2
  items:
   - price: 20 of bronze
     properties: "applycolorbyteam"
     stack:
      type: CHAINMAIL_BOOTS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 20 of bronze
     properties: "applycolorbyteam"
     stack:
      type: CHAINMAIL_LEGGINGS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 6 of iron
     properties: "applycolorbyteam"
     stack:
      type: IRON_BOOTS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 6 of iron
     stack:
      type: IRON_LEGGINGS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 3 of gold
     stack:
      type: DIAMOND_BOOTS
      enchants:
       PROTECTION_ENVIRONMENTAL: 2
   - price: 3 of gold
     stack:
      type: DIAMOND_LEGGINGS
      enchants:
       PROTECTION_ENVIRONMENTAL: 3
       
- stack: "DIAMOND_SWORD;1;Swords;Click here to get sword for attacking your enemies"
  column: 4
  row: 2
  items:
   - price: 10 of iron
     stack:
      type: STICK
      enchants:
       KNOCKBACK: 1
   - price: 10 of bronze
     stack:
      type: STONE_SWORD
      enchants:
       DAMAGE_ALL: 0
   - price: 7 of iron
     stack:
      type: IRON_SWORD
      enchants:
       DAMAGE_ALL: 0
   - price: 4 of gold
     stack:
      type: DIAMOND_SWORD
      enchants:
       DAMAGE_ALL: 0
       
- stack: "BOW;1;Bows;Prove yourself as a marksman with these wonderful bows"
  column: 5
  row: 2
  items:
   - ARROW;8 for 2 of iron
   - price: 12 of iron
     stack:
      type: BOW
   - price: 24 of iron
     stack:
      type: BOW
      enchants:
       ARROW_DAMAGE: 1
   - price: 6 of gold
     stack:
      type: BOW
      enchants:
       ARROW_DAMAGE: 1
       ARROW_KNOCKBACK: 1

- stack:
   type: POTION
   meta:
    ==: ItemMeta
    meta-type: POTION
    display-name: "Drinks"
    lore:
     - "Not enough? Use these potions and you'll feel better!"
    potion-type: strength
  row: 2
  column: 6
  items:
   - stack:
      type: potion 1 8270
      meta: 
       ==: ItemMeta
       meta-type: potion{Potion:invisibility}
       potion-type: 373:8206
     price: 3 of iron
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: 8206
       potion-type: invisibility
     price: 5 of iron
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: swiftness
     price: 7 of iron
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strength
     price: 1 of gold
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: regeneration
     price: 3 of gold

- stack: "SANDSTONE;1;Blocks;Get to the others! Possible with blocks."
  column: 1
  row: 2
  items:
   - price: 4 of bronze
     properties: "applycolorbyteam"
     stack: WOOL;16
   - CUT_SANDSTONE;16 for 12 of bronze
   - END_STONE;12 for 24 of bronze
   - OAK_PLANKS;16 for 4 of iron
   - OBSIDIAN;4 for 8 of gold
   - price: 4 of bronze
     properties: "applycolorbyteam"
     stack: GLASS

- stack: "TNT;1;Useful Stuff;Looking for useful stuff? Here are some!"
  row: 2
  column: 7
  items:
   - ENDER_PEARL for 4 of gold
   - GOLDEN_APPLE for 3 of iron
   - TNT for 4 of iron
   - FIRE_CHARGE for 40 of bronze
   - price: 7 of iron
     properties:
      - name: "WarpPowder"
        delay: 6
     stack:
      type: GUNPOWDER
      display-name: "Warp Powder"
      lore:
       - "When using this powder you'll get"
       - "teleported to you spawn point within 6 seconds"
       - "Warning: Any movement will stop the process"
   - price: 3 of iron
     properties:
      - name: "Trap"
        data:
         - sound: ENTITY_SHEEP_AMBIENT
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 15
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 18
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 2
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
     stack:
      type: STRING
      display-name: "Trap"
      lore:
       - "Get informed if an enemy steps on your trap"
       - "and your enemy won't be able to move properly."
   - price: 6 of iron
     properties:
      - name: "MagnetShoes"
        probability: 75
     stack:
      type: IRON_BOOTS
      display-name: "Magnet-Shoes"
      lore:
       - "Wear those shoes and have a 75%"
       - "chance of getting no knockback!"
   - price: 5 of iron
     properties: "Tracker"
     stack:
      type: COMPASS
      display-name: "Tracker"
      lore:
       - "Wanna know where your closest target is?"
       - "Let's try this out!"
   - price: 15 of iron
     properties:
      - name: "rescueplatform"
        delay: 5
     stack:
      type: BLAZE_ROD
      display-name: "Rescue Platform"
      lore:
       - "Protect yourself from falling into"
       - "void with a Rescue Platform."
       - "This is your last hope!"
   - price: 5 of gold
     properties:
      - name: "arrowblocker"
        delay: 5
     stack:
      type: ENDER_EYE
      display-name: "Arrow Blocker"
      lore:
       - "Block arrows that are coming"
       - "for you with black magic."
       - "I mean, with this item."
   - price: 64 of bronze
     properties:
      - name: "protectionwall"
     stack:
      type: BRICKS
      display-name: "Protection Wall"
      lore:
       - "Instantly builds a wall that"
       - "can save your life!"
   - price: 24 of iron
     properties:
      - name: "Golem"
        speed: 0.25
        follow: 16.0
     stack:
      type: GHAST_SPAWN_EGG
      display-name: "Golem"
      lore:
       - "An iron golem that will protect"
       - "your team from the enemies."

- stack: "DIAMOND_PICKAXE;1;Pickaxes;Destroy others blocks? Use these pickaxes."
  column: 3
  row: 2
  items:
   - price: 10 of bronze
     stack:
      type: WOODEN_PICKAXE
   - price: 20 of bronze
     stack:
      type: STONE_PICKAXE
      enchants:
       DIG_SPEED: 1
   - price: 8 of iron
     stack:
      type: IRON_PICKAXE
      enchants:
       DIG_SPEED: 2
   - price: 12 of iron
     stack:
      type: DIAMOND_PICKAXE
      enchants:
       DIG_SPEED: 3
   - price: 12 of iron
     stack:
      type: DIAMOND_AXE
      enchants:
       DIG_SPEED: 2
   - price: 30 of bronze
     stack:
      type: SHEARS

**Comment by iamceph** [comment]
Download latest version from Jenkins and try again.

**Comment by Misat11** [comment]
Also I notice you have version 1.9. Make sure you are using latest patch version of your release (in this case 1.9.4), 1.9.0 is not working good at all
