### ISSUE TITLE
Costume tab

### ISSUE THREAD

**Issue by AhmedFathey2008** [ScreamingSandals/BedWars#173]
Hello,
I love this plugin very much
But can you add on config "Tab"
Only if you can

Thank you

**Comment by iamceph** [comment]
What is "config on tab"

**Comment by AhmedFathey2008** [comment]
i mean costumise the tap like hypixel
example:
R ratio2k            #R mean by red team
B rekch              #blue team
G  greenflame   #green team
Y FlowminiumYT      #yellow team
so can you do that?

**Comment by iamceph** [comment]
Will be in 1.x.x

**Comment by AhmedFathey2008** [comment]
ok thanks
