### ISSUE TITLE
bw reload causes subcommands to fail

### ISSUE THREAD

**Issue by Kirrasio** [ScreamingSandals/BedWars#176]
#### Describe the bug
Bedwars reload command causes subcommands to stop working entirely and start saying /bw [subcommand] - This wouldn't be too big of a problem, however I've blocked bedwars join commands so we can reset it through a denizen script and then force join with a subcommand. (this resets the map from pasted in structures, mythicmobs, pets and other odds and ends.)

BedWars version:
BedWars-0.2.8-SNAPSHOT-515.jar

Installed plugins on server (can be obtained by /pl)
Plugins (29): BedWars, ChatControl, Citizens, CMI, CMIPaperLib, CoreProtect, CrazyEnchantments, Denizen, Depenizen, FastAsyncWorldEdit, HeadDatabase*, LibsDisguises, LuckPerms, Minepacks, Multiverse-Core, MythicMobs, PhatLoots, PlaceholderAPI, PocketGames, ProtocolLib, SCBWAddon, Shopkeepers, SpecializedCrates, SuperLuckyBlock, Vault, VoidGenerator, WorldBorder, WorldEdit, WorldGuard

Console log
Configuration (of config.yml and shop.yml)
https://pastebin.com/2tcxLp29
https://pastebin.com/hFj3q4ck

**Comment by iamceph** [comment]
Fixed in 1.x.x, wait for the release please.
