### ISSUE TITLE
Is it possible to HideFlags for items?

### ISSUE THREAD

**Issue by sapov89706** [ScreamingSandals/BedWars#187]
How do I had the flags for potions, armor, swords, etc.? I know in some other plugins, I could just add something like "HideFlags: true" underneath each item to remove them.

**Comment by Misat11** [comment]
https://github.com/ScreamingSandals/SimpleInventories/wiki/Variable:-stack

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html

**Comment by Misat11** [comment]
First link is how to use it in shop (look for ItemFlags: )

The second link are possible values.

**Comment by iamceph** [comment]
ItemFlags:
    - HIDE_ATTRIBUTES

**Comment by sapov89706** [comment]
thanks guys
