### ISSUE TITLE
OP bypass minimum player

### ISSUE THREAD

**Issue by OmsinKrissada** [ScreamingSandals/BedWars#189]
#### Describe the solution you'd like
Can I have the ability for server administrators to start the game regardless of minimum players for testing purposes?
Of course, as a configurable option. Thank you.

#### Is your feature request related to a problem? Please describe
Not related.

**Comment by iamceph** [comment]
Will be in 1.x.x. Not possible in 0.x.x

**Comment by OmsinKrissada** [comment]
Thank you.
