### ISSUE TITLE
Raining begins whenever the Bedwars game ends or the lobby is left

### ISSUE THREAD

**Issue by MadManPineapple** [ScreamingSandals/BedWars#195]
#### Describe the bug
When a player either leaves the bedwars game lobby that they were in or if the game finishes, then rain begins for that player in the world that is being played in. This is not a server side issue as the rain only appears for that player unless another player has also done the same (e.g. if a new player joined after the rain appeared then the rain would only appear on the previous player's screen.)

#### Server and plugin version
Spigot version: BukkitCraft 1.16.1
BedWars version: 0.2.10

#### Installed plugins on server (can be obtained by `/pl`)
LuckPerms, PhantomSMP, ChatColour2, Rocket, DropHeads, ClearLag, Betterinvsee, RTP, Zenchantments, WorldBorder, Vault, Spawn, Multiverse-Core, MyWarp, WorldEdit, Essentials, BedWars, SurvivalGames, WorldGuard, PhatLoots, ScreamingBedwarsAddon, LWC, Quests

#### Console log
No console log as its only on the clients side

#### Configuration (of config.yml and shop.yml)
Changed nothing from original

**Comment by Misat11** [comment]
I've noticed that incompatibility with 1.16.1 too. I'll look into it tomorrow.

**Comment by Misat11** [comment]
this bug is related with SPIGOT-5849, not with bedwars. This bug is marked as resolved, use BuildTools to obtain latest build.
