### ISSUE TITLE
PlaceholderAPI Support

### ISSUE THREAD

**Issue by Jan-DT** [ScreamingSandals/BedWars#197]
#### Describe the solution you'd like

I would love it if you would add PlaceholderAPI support to the plugin. It allows people like me to add holographic displays and scoreboards with bedwars stats on them.

**Comment by Misat11** [comment]
https://github.com/ScreamingSandals/BedWars/wiki/PlaceholderAPI-placeholders

**Comment by Misat11** [comment]
#160

**Comment by Jan-DT** [comment]
oops couldnt find it, thanks at least!
