### ISSUE TITLE
Kick prevent start game

### ISSUE THREAD

**Issue by KyneasSurYoutube** [ScreamingSandals/BedWars#198]
#### Describe the bug
Hello,
First of all, sorry for the quality of my writing, I use translation software (which is not really efficient in terms of comprehension).
Basically, when the players have joined a team (by the way, that would be a feature that allows the game to start without the players joining a team), the game starts the countdown, as soon as it reaches 10 (and the title is displayed), I have a magnificent malformed json error message.

#### Server and plugin version
Spigot version: 1.14.4
BedWars version: 0.2.11

#### Installed plugins on server (can be obtained by `/pl`)
This is a problem coming from ScreamingBedWars, I tested it on a server without any plugins other than this one.

#### Console log
There are no console errors, just a client error.

Error code : Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(True) to accept malformed JSON at line 1 column 1

**Comment by iamceph** [comment]
Not caused by BedWars, update your server to at least 1.15.2, as that is supported version by Spigot or Paper.
