### ISSUE TITLE
Please add a bungeecord addon for lobbies

### ISSUE THREAD

**Issue by posterhusky** [ScreamingSandals/BedWars#199]
#### Describe the solution you'd like
Please add a bungee cord lobby support! Because the bungee system that exists right now isn't quite good... It will be nice that you added the ability to join a game with signs, and not a chestcommands GUI where you don't know is the game started or not, or the server shut down? And add papi support for the online in a game, and for the status of a game.

**Comment by iamceph** [comment]
Will be our plugin BungeeLink.
