### ISSUE TITLE
Method to autostart bedwars

### ISSUE THREAD

**Issue by Celophy** [ScreamingSandals/BedWars#200]
Will be possible to autostart a game without the need of an admin online? i searched in config but i can't find nothing, help!

**Comment by Misat11** [comment]
Join to game and use COMPASS SELECTOR to select teams or open config.yml and enable join-randomly-on-lobby-join. For support please use discord. Link is in README.md or on spigot page.

**Comment by Celophy** [comment]
thanks!!!!!
