### ISSUE TITLE
I can't change the price of things using diamonds or emeralds

### ISSUE THREAD

**Issue by thebosseric123** [ScreamingSandals/BedWars#204]
every time I try and change the price to of diamond instead of 'of bronze' it always says shop.yml is wrong is there a way to make it work because I added emerald and diamond gens so I want them to have use. thanks
didn't really know which category this goes in so just put it in bug sorry if I am wrong

**Comment by notfoundname** [comment]
You probably made some mistakes in your shop file. Use some YAML validator like yamllint.com, or paste broken store here, I'll try to fix it

**Comment by thebosseric123** [comment]
``data:
#-   stack:
#      type: GOLDEN_APPLE
#      amount: 1
#      meta:
#        ==: ItemMeta
#        meta-type: UNSPECIFIC
#        display-name: "Example category"
#        lore:
#        - "This is my category!"
#        - "Please buy things inside!"
#    items:
#    - price: 50
#      price-type: "bronze"
#      stack:
#        type: DIAMOND_SWORD
#        amount: 1
#        meta:
#          ==: ItemMeta
#          meta-type: UNSPECIFIC
#          enchants:
#            DAMAGE_ALL: 2
#          repair-cost: 1
#          Damage: 99
# Value 'applycolorbyteam' is used for automatic-coloring-in-shop.
# See WarpPowder for more info.

- stack: "DIAMOND_CHESTPLATE;1;Armor;Protect yourself with armor! Click here."
  items:
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_HELMET
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_LEGGINGS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_BOOTS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 3 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 2
   - price: 7 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 3
   - price: 10 of gold
     stack:
      type: IRON_HELMET
      display-name: Helm
      enchants:
       PROTECTION_ENVIRONMENTAL: 2
       
- stack: "DIAMOND_SWORD;1;Swords;Click here to get sword for attacking your enemies"
  column: center
  items:
   - price: 8 of bronze
     stack:
      type: STICK
      enchants:
       KNOCKBACK: 1
   - price: 2 of iron
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 1
   - price: 3 of iron
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 2
   - price: 7 of iron
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 3
   - price: 1 of diamond
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 2
       KNOCKBACK: 1
   - price: 1 of emerald
     stack:
      type: GOLDEN_AXE
      display-name: "Axe of Infinity"
      enchants:
       DAMAGE_ALL: 1
       DURABILITY: 1
       KNOCKBACK: 1
       
- stack: "BOW;1;Bows;Prove yourself as a marksman with these wonderful bows"
  column: right
  items:
   - price: 1 of emerald
     stack:
      type: BOW
      enchants:
   - price: 2 of emerald
     stack:
      type: BOW
      enchants:
       ARROW_DAMAGE: 1
   - price: 3 of emerald
     stack:
      type: BOW
      enchants:
       ARROW_DAMAGE: 2
   - price: 3 of diamond
     stack:
      type: BOW
      enchants:
       ARROW_FIRE: 1
   - price: 5 of emerald
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_FIRE: 1
       ARROW_KNOCKBACK: 1
   - ARROW for 1 of iron

- stack: "COOKED_PORKCHOP;1;Eat;Are you hungry? Get something to eat."
  row: 3
  column: 2
  items:
   - COOKED_PORKCHOP;2 for 4 of bronze
   - GOLDEN_APPLE for 2 of iron
   - BREAD;10 for 5 of gold

- stack:
   type: POTION
   meta:
    ==: ItemMeta
    meta-type: POTION
    display-name: "Drinks"
    lore:
     - "Not enough? Use these potions and you'll feel better!"
    potion-type: strength
  row: 3
  column: 6
  items:
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: healing
     price: 3 of gold
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strong_healing
     price: 5 of iron
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: swiftness
     price: 3 of diamond
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strength
     price: 1 of emerald
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: regeneration
     price: 3 of gold

- stack: "SANDSTONE;1;Blocks;Get to the others! Possible with blocks."
  linebreak: before
  items:
   - price: 4 of bronze
     properties: "applycolorbyteam"
     stack: WOOL
   - price: 4 of bronze
     properties: "applycolorbyteam"
     stack: GLASS
   - END_STONE;3 for 7 of bronze
   - IRON_BLOCK for 3 of iron
   - GLOWSTONE;4 for 15 of bronze

- stack: "TNT;1;Useful Stuff;Looking for useful stuff? Here are some!"
  column: center
  items:
   - CHEST for 1 of iron
   - ENDER_CHEST for 1 of gold
   - price: 7 of iron
     properties:
      - name: "WarpPowder"
        delay: 6
     stack:
      type: GUNPOWDER
      display-name: "Warp Powder"
      lore:
       - "When using this powder you'll get"
       - "teleported to you spawn point within 6 seconds"
       - "Warning: Any movement will stop the process"
   - price: 3 of iron
     properties:
      - name: "Trap"
        data:
         - sound: ENTITY_SHEEP_AMBIENT
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 15
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 18
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 2
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
     stack:
      type: STRING
      display-name: "Trap"
      lore:
       - "Get informed if an enemy steps on your trap"
       - "and your enemy won't be able to move properly."
   - price: 1 of diamond
     properties:
      - name: "MagnetShoes"
        probability: 75
     stack:
      type: IRON_BOOTS
      display-name: "Magnet-Shoes"
      lore:
       - "Wear those shoes and have a 75%"
       - "chance of getting no knockback!"
   - price: 1 of emerald
     properties: "Tracker"
     stack:
      type: COMPASS
      display-name: "Tracker"
      lore:
       - "Wanna know where your closest target is?"
       - "Let's try this out!"
   - price: 15 of iron
     properties:
      - name: "rescueplatform"
        delay: 5
     stack:
      type: BLAZE_ROD
      display-name: "Rescue Platform"
      lore:
       - "Protect yourself from falling into"
       - "void with a Rescue Platform."
       - "This is your last hope!"
   - price: 2 of emerald
     properties:
      - name: "arrowblocker"
        delay: 5
     stack:
      type: ENDER_EYE
      display-name: "Arrow Blocker"
      lore:
       - "Block arrows that are coming"
       - "for you with black magic."
       - "I mean, with this item."
   - price: 64 of bronze
     properties:
      - name: "protectionwall"
     stack:
      type: BRICKS
      display-name: "Protection Wall"
      lore:
       - "Instantly builds a wall that"
       - "can save your life!"
   - price: 24 of iron
     properties:
      - name: "Golem"
        speed: 0.25
        follow: 16.0
     stack:
      type: GHAST_SPAWN_EGG
      display-name: "Golem"
      lore:
       - "An iron golem that will protect"
       - "your team from the enemies."
   - price: 10 of gold
     properties: "TNTSheep"
     stack:
      type: SHEEP_SPAWN_EGG
      display-name: "TNT Sheep"
      lore:
       - "Use the TNT-Sheep! It will"
       - "walk towards your closest enemy"
       - "and explode within 8 seconds!"
   - price: 40 of iron
     properties: "ThrowableFireball"
     stack:
       type: FIRE_CHARGE
       display-name: "Fireball"
       lore:
         - "Is it a bird? Is it a plane?"
         - "By the time you know"
         - "you are dead!"

- stack: "DIAMOND_PICKAXE;1;Pickaxes;Destroy others blocks? Use these pickaxes."
  column: right
  items:
   - price: 4 of bronze
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 1
   - price: 2 of iron
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 2
   - price: 1 of gold
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 3

**Comment by thebosseric123** [comment]
on the YAMLLINT it says its correct

**Comment by notfoundname** [comment]
As file please, or use pastebin

**Comment by thebosseric123** [comment]
there a pastebin linked above

**Comment by Misat11** [comment]
Send us also your config.yml so we can test your files. And note that in your shop.yml that you sent us via pastebin are still some items that require bronze.

**Comment by thebosseric123** [comment]
Oh ok but can you list the items that require bronze so I could fix it

**Comment by thebosseric123** [comment]
I know that my gives players items is wrong but it is fixed now

**Comment by thebosseric123** [comment]
Im just going to use the addon
