### ISSUE TITLE
Every time I try to save it says internal error

### ISSUE THREAD

**Issue by thebosseric123** [ScreamingSandals/BedWars#205]
I have both screaming bedwars and the addon the newest version and can't get it to work. anything i save just gives me internal error but all other commands work

**Comment by iamceph** [comment]
There is some fuckup in your config probably. Also, why are you "reporting" this without any log? We can't magically tell whats wrong

**Comment by thebosseric123** [comment]
https://pastebin.com/8r2qht64
here is the log

**Comment by thebosseric123** [comment]
I checked yamllint and it says its correct

**Comment by Misat11** [comment]
I see you are using snapshot version, try latest build

**Comment by pronze** [comment]
This issue also happens if you have removed an world which was an arena before it's removal. Try doing /bw admin <mapname> remove, or you can go to your arenas folder inside bedwars directory and delete the map which was linked with the world you removed.

**Comment by thebosseric123** [comment]
So I should redo everything your saying

**Comment by pronze** [comment]
No, what I meant was if you deleted a world which was linked with bedwars before, the plugin will fail trying to load the arena showing the null pointer exception error. So only follow the steps if you had deleted a world which previously you had setup an arena with.

**Comment by thebosseric123** [comment]
I think I might’ve deleted the world but I only had problems when I added the add on it was fine before

**Comment by pronze** [comment]
It's not an addon issue, your logs does not show any addon related errors. While checking your logs it shows one of your games are null. Delete any map from your arenas folder that you don't require (or which was linked to previously deleted world) and it'll be fine.

**Comment by thebosseric123** [comment]
I mean I only have one map so I’ll just redo this and ask on discord if it still doesn’t work. I already redid it before so it shouldn’t take to long
