### ISSUE TITLE
Players receive nothing when they join the game.

### ISSUE THREAD

**Issue by PQguanfang** [ScreamingSandals/BedWars#206]
#### Describe the bug
I notice that this plugin has this feature:when a player join the game,they will get some items like TeamSelecter(A compass)...
But for me,nothing was given when my players join the game.

#### Server and plugin version
Spigot version:1.16.1(Paper)
BedWars version:0.2.11 0.2.12 all tested,have the same problem

#### Installed plugins on server (can be obtained by `/pl`)
SimpleInventroy and BedWars

#### Console log
No error.

#### Configuration (of config.yml and shop.yml)
Both of them are default,which means they are generated by the plugin its own.

#### If there are problem with only one game, paste here config of this game

PS:A OP in my server receive these items,I dont know why.I have OP permission too,but I don't have these items.I have checked my configuration the whole day,I think these is no problems with them.

**Comment by Misat11** [comment]
I've never seen this problem before. Send us your arena file and latest.log file.
