### ISSUE TITLE
Shops Dont Work

### ISSUE THREAD

**Issue by Nikitanikota** [ScreamingSandals/BedWars#208]
#### Describe the bug
The Shops Dont Spawn

#### Server and plugin version
Spigot version:
BedWars version: 0.2.11

#### Installed plugins on server (can be obtained by `/pl`)
luckperms, Worldedit, AntiSpam, ultraCustomizer, Multivers_Core, oldcombatMechanics, Autorestart, sudo, ImageOnMap, ViaVersion, WitherAC, Vault, ViaBackwards, ProtocolLib, Citizens, EssentialsXMPP, UltraCustomiserPlus, SVAHypixelify, EssentialsChat, Litebans, ChitizensCMD, Worldguard, MoreVaultPlus

**Comment by iamceph** [comment]
Not a bug, you messed up your config or you dont have npcs enabled. Contact us on discord, not here.
