### ISSUE TITLE
The protective wall can be used countless times

### ISSUE THREAD

**Issue by nkxingxh** [ScreamingSandals/BedWars#213]
#### Describe the bug
当用副手使用防御墙时，一个防御墙可以使用无数次。
When using a protective wall with an offhand, a protective wall can be used countless times.

#### Server and plugin version
Spigot version: 1.16.1(Paper)
BedWars version: 0.2.1.1

#### Installed plugins on server (can be obtained by `/pl`)
BedWars, ClearLag, Essentials, GroupManager, HolographicDisplays, LockettePro, MultiWorld, OpenInv, ProtocolLib, QualityArmory, QuickShop, RedstoneClockPreventerm, Residence and so on....

#### Console log
无错误输出
No error output

#### Configuration (of config.yml and shop.yml)
没有更改，它是默认的
No changes, it is the default

#### If there are problem with only one game, paste here config of this game
所有的游戏都有这个问题
All games have this problem

**Comment by iamceph** [comment]
Update to latest build from our CI. https://ci.screamingsandals.org/job/BedWars-0.x.x/
