### ISSUE TITLE
i can not make an arena

### ISSUE THREAD

**Issue by Cassum12** [ScreamingSandals/BedWars#215]
downloaded the ''bedwars'' plugin for my minecraft server to play on a custom map with my friends, i followed a tutorial on how to use it but i can't make an arena. it will say ''/bw help'' when i type '/bw admin <arenaname> add.
i'd like to getr a response asap, thanks!

**Comment by pronze** [comment]
The valid syntax is /bw admin (mapname) add. You must specify the map name as an argument too.
