### ISSUE TITLE
Bedwars set-ups get reset

### ISSUE THREAD

**Issue by WaterGenic** [ScreamingSandals/BedWars#226]
I don't know if this a bug or something, but when I set up a bedwars game then I play. Then I shut down the server. When I come back on the server it says there is no bedwars game set up. So then I have to create the whole game up again to play. I don't want to keep resetting the game every time I shut down the server.

**Comment by iamceph** [comment]
Not a bug, probably multiworld problem or config problem. Contact us on discord if you want help.
