### ISSUE TITLE
The plugin 'BedWars' cannot execute the command '/bw'.

### ISSUE THREAD

**Issue by tfcmahmoud** [ScreamingSandals/BedWars#230]
Hello, So I added somethings in the files and I was sure that I did every thing right but when I started the server it told me The plugin 'BedWars' cannot execute the command '/bw'.
and when I went in the logs it said 

[16:54:03] [Server thread/WARN]: Your shop.yml/shop.groovy is wrong!
--
107 | [16:54:03] [Server thread/WARN]: Disabling plugin..

so what is a possible solution to fix this without deleting the plugin

**Comment by Misat11** [comment]
First: Use YamlLint/YamlChecker to check the yaml format
Second: check if all price-types are correct
Third: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

If you couldn't find solution, send us your shop file here via pastebin/hastebin

**Comment by tfcmahmoud** [comment]
Thank you,this helps a lot
