### ISSUE TITLE
Upgrading spawner villager

### ISSUE THREAD

**Issue by tfcmahmoud** [ScreamingSandals/BedWars#231]
Hello, so I recently used this plugin and its the best bedwars plugin but I think something is missing it is a villager that you can upgrade your spawners speed I wish this could be added or if I can add it my own I wish that you respond to this by how I can add it my own

**Comment by linusstretchtips** [comment]
Hello,
You have 2 options to do this.
1) Either Use the built-in feature
Check WIKI: https://github.com/ScreamingSandals/BedWars/wiki/Upgrades

2) Use hypixelify:
https://www.spigotmc.org/resources/addon-sbahypixelify-for-screaming-bedwars-1-9-4-1-16-3.79505/

If you need anything else, just reply 👍
