### ISSUE TITLE
Can you do this plugins for Pokkit plugins?

### ISSUE THREAD

**Issue by Hoangviphb999** [ScreamingSandals/BedWars#232]
I want to this plugins can be used in Pokkit (A plugins which it can load any Spigot/Bukkit for Nukkit plugins) and it can be a great things.

**Comment by linusstretchtips** [comment]
You could of said something ceph lmao

Anyways,
We dont know if it will work for pokkit and we dont support it.
Thanks

**Comment by Misat11** [comment]
Pokkit is still not completed, as it's mentioned in the https://github.com/PetteriM1/Pokkit/blob/new-master/README.md

Probably when it will become more stable, most of features of BedWars would start working
