### ISSUE TITLE
Bungeecord error when you leave server/game after changed teams 2 or more times

### ISSUE THREAD

**Issue by Magzypotato** [ScreamingSandals/BedWars#235]
#### Describe the bug
I have a bungeecord network. I use the bungeecord settings for screaming bedwars and also use the SBAHypixelify addon. This error message comes in my bungeecord console when i use the bed in slot 9 to instanstly leave the server https://paste.gg/p/anonymous/c44506b372db4e4584e2ce516ed22578. I havent tested but if you do /server lobby the same thing would probably happen. Note that this error only happens if you have changed your team at least 2 times since you joined. 
I have gone through my entire bedwars and Sbahypixelify files very accurately and it should work.

#### Server and plugin version
Spigot version: This server is running Paper version git-Paper-288 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[15:22:22 INFO]: You are 24 version(s) behind (i dont think this matters at all, but i have updated it now)

BedWars version: Bedwars-0.2.15

#### Installed plugins on server (can be obtained by `/pl`)
I know that this error is the bedwars/sbahypixelify fault, but this is my plugins:
BedWars, Essentials, KohiKB*, LuckPerms, Multiverse-Core, NoCheatPlus, OldCombatMechanics, PlaceholderAPI, ProtocolLib, SBAHypixelify, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support*, ViaVersion, VoidGenerator, WorldEdit

#### Console log
This console log is very strange bit i will clarify and make it simpler. When you see errors i changed team 2 or 3 times in the lobby, but when you dont see errors i just joined and left very fast (and sometimes changed team 1 time) just to check if i would ever get the same error, which i didnt.
So its pretty obiouvsly an error for if you change team 2 or more times.
https://paste.gg/p/anonymous/a17515f98a31430d987ee2f8d611c5a0

#### Configuration (of config.yml and shop.yml)
Bedwars config: https://paste.gg/p/anonymous/670a6a072cdd4cda8030dc338ee8eefa
SBAHypixelify bwaconfig: https://paste.gg/p/anonymous/88714d11e85e4298a53dbd2ca8b8b5b4
Shop.yml: https://paste.gg/p/anonymous/9c458ff6e23c46dd969e0244eba0f15c

**Comment by iamceph** [comment]
That is caused by Bungeecord itself. It cannot handle scoreboards that well
