### ISSUE TITLE
Villager doesn't respawn sometimes

### ISSUE THREAD

**Issue by M1904** [ScreamingSandals/BedWars#236]
#### Describe the bug
Sometimes players call us because the villagers trade regular items and no bedwars-items. The problem in this case is, after the last game the villagers do not despawn, stay alive at the same position without AI and at the beginning of the next game there are 2 villagers at the same position. one which trades regular, one which trades bedwars-items. Now the player has a 50/50 chance to get the right trades. 

#### Server and plugin version
Spigot version: 1.16.4
BedWars version: 0.2.15

#### Console log

no error in console

#### Configuration (of config.yml and shop.yml)

[shop.txt](https://github.com/ScreamingSandals/BedWars/files/5644667/shop.txt)
[config.txt](https://github.com/ScreamingSandals/BedWars/files/5644668/config.txt)

**Comment by iamceph** [comment]
Should be fixed in latest snapshots
