### ISSUE TITLE
Countdown

### ISSUE THREAD

**Issue by sunnyy420** [ScreamingSandals/BedWars#242]
Hello, I have a great idea of adding "countdown". Currently there is bossbar countdown till arena starts, but it would be great if we can add custom placeholder to our lobby scoreboard to display exact time in seconds. If there aren't enough players, it will just display "Waiting...". These both texts should be configuratable.

**Comment by Misat11** [comment]
Duplicated by #500, but I'll close this one in favor of the newer request.
