### ISSUE TITLE
Double quit message

### ISSUE THREAD

**Issue by zannapzg** [ScreamingSandals/BedWars#247]
There is a problem with quit messages (from the arenas)
The message appears 2 times sometime

My server version is: Paper 1.15.2
![image](https://user-images.githubusercontent.com/61860483/103137751-1684b280-46cc-11eb-83d6-fe6596d65621.png)

My BedWars plugin version is the latest from spigot

My plugins are these:
![image](https://user-images.githubusercontent.com/61860483/103137756-27352880-46cc-11eb-9fe1-dff59e668108.png)

No error in console

**Comment by iamceph** [comment]
Not enough informations, are you running bungee? Provide server logs.
