### ISSUE TITLE
Iron forge and heal pool

### ISSUE THREAD

**Issue by SamSamsung** [ScreamingSandals/BedWars#248]
#### Describe the bug
The iron upgarde doesn't work, even if i put ALL of my iron in it, it won't work and same for heal pool.

#### Server and plugin version
Spigot version: 1.16.4
SBA Hypixel BedWars version: (4.2, i think)

#### Installed plugins on server (can be obtained by `/pl`)
- Multicore
- Bedwars
- Citizen
- Via backwards
- Via version
- hologramm
-

**Comment by iamceph** [comment]
Not BedWars bug, that's Hypixelify. Also, you dont provide enough informations anyways :)
