### ISSUE TITLE
ViaVersion 1.8: "Internal Exception: io.netty.handler.codec.DecoderException"

### ISSUE THREAD

**Issue by google-meet-meat** [ScreamingSandals/BedWars#249]
When using ViaBackwards, ViaRewind, and ViaVersion with the plugin, the player is kicked out of the game when trying to join a BedWars match. The error shown in the console is `Internal Exception: io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0`

The cause of this issue is the boss bar -- the 1.9 boss bar is sent to the 1.8 player, and they are disconnected. The temporary workaround for this fix is to disable the boss bar in the `config.yml`. If possible, it would be great if this could be fixed so that the boss bar works for 1.8.

**Comment by Misat11** [comment]
This bug is related to ViaRewind, not to BedWars.
