### ISSUE TITLE
Change scoreboard impl to not flicker every second

### ISSUE THREAD

**Issue by kentos01** [ScreamingSandals/BedWars#251]
#### Describe the solution you'd like
Change scoreboard impl to not flicker every second
#### Is your feature request related to a problem? Please describe
yes, every second the scoreboard flickers, its pretty easy to make a scoreboard that doesn't do this, look on youtube.

**Comment by pronze** [comment]
Already added on the latest snapshot as experimental scoreboard.

**Comment by kentos01** [comment]
where can i download the snapshot from?

**Comment by iamceph** [comment]
ci.screamingsandals.org
