### ISSUE TITLE
Didnt Save Game in yml

### ISSUE THREAD

**Issue by HolyFireJake** [ScreamingSandals/BedWars#255]
#### Describe the bug
I was creating a Game with the Game "Knockout" i already had a Game with the same name but renamed and deleted it but when i try to create a new one it doesnt save it as a arena but i can access it in the game.
After restarting the Server it was gone...
#### Server and plugin version
Spigot version: / Paper: 391
BedWars version: 0.2.15

#### Installed plugins on server (can be obtained by `/pl`)
Plugins (21): AreaShop, BedWars, ChestShop, dynmap*, Essentials, EssentialsChat, EssentialsSpawn, HolographicDisplays, IridiumSkyblock, LuckPerms, Multiverse-Core, Multiverse-Portals, NametagEdit*, ProtocolLib, StatsAPI*, TabList, UltimateClaims, Vault, VoidGenerator, WorldEdit, WorldGuard
#### Console log
/
#### Configuration (of config.yml and shop.yml)
config:
**https://pastebin.com/U09u53m6**
shop:
**https://pastebin.com/wsnkKWeV**
#### If there are problem with only one game, paste here config of this game
didnt got created

**Comment by iamceph** [comment]
You probably onle renamed the yaml file and not the actual name in the file or via-versa. Not a bug, don't create games with same names. :)

**Comment by HolyFireJake** [comment]
But the Game doesnt exist anywhere but still bugs out i renamed everything via Files the File name and the Name in the File still probally dumb me still thank you have a great day!

**Comment by iamceph** [comment]
Okay, can you send me the file over? Join our discord so I can assist you with it. :)

**Comment by HolyFireJake** [comment]
can you send me an invite please
