### ISSUE TITLE
Javadocs are offline

### ISSUE THREAD

**Issue by irishgreencitrus** [ScreamingSandals/BedWars#256]
API Docs are 404 [here](https://docs.screamingsandals.org/bedwars/apidocs/)
I need the javadocs events for this plugin if there are any.

**Comment by iamceph** [comment]
Javadocs are offline for quite a while, we will fix it when we have time. For now you can just download sources to your IDE.
https://gitlab.hoznet.dev/screamingsandals/public-repo

**Comment by Misat11** [comment]
Also on this repo you can found javadoc jars, which contain the generated html that you can extract and open in your browser

**Comment by irishgreencitrus** [comment]
Are there any plugin specific events i should be made aware of?

**Comment by iamceph** [comment]
Alot of events :D

**Comment by irishgreencitrus** [comment]
where could i find the docs?

**Comment by Misat11** [comment]
https://gitlab.hoznet.dev/screamingsandals/public-repo/-/package_files/5015/download

**Comment by pronze** [comment]
Sorry for the delay, but Javadocs are backup :)
https://jd.screamingsandals.org/BedWars-parent/BedWars-API/
