### ISSUE TITLE
Ayuda :(

### ISSUE THREAD

**Issue by TheNahuelAsd** [ScreamingSandals/BedWars#260]
Mi problema es,como añado una cama a un equipo,cuando quiero guardar absolutamente todo lo que hise no me deja porque dice "coloque la cama a tal equipo" y no me deja guardar por esa razon

**Comment by SamSamsung** [comment]
¿estás haciendo el comando / bw admin [nombre del mapa] el equipo lee [color del equipo] mirando al frente de la cama? Utilizo el traductor de Google, así que la traducción es mala.

**Comment by iamceph** [comment]
Please use our Discord and contact us in multi-lang support here. We only accept issues in English.
