### ISSUE TITLE
Debug mode (start game with only one player)

### ISSUE THREAD

**Issue by Hazza4569** [ScreamingSandals/BedWars#261]
Would be nice to be able to start games without a second player, to be able to check that the shops and spawners are working as expected.

I currently am enduring a rather slow debug cycle of editing yaml files, reloading the plugin, then waiting until my friend can jump on the server so i can test if I've made the changes correctly.

**Comment by stovan12** [comment]
probably bugs out and makes you win instantly as 1 player left = game over

**Comment by Hazza4569** [comment]
Indeed, I imagine there would need to be some sort of flag to indicate it is in debug mode and so not end because there is just one player.

**Comment by lilingxi01** [comment]
I suggest that the debug mode should not have a win / lose automatically (so testers can continue with only one player).
Just for testing the maps, shops, items, etc.

And probably should log the events like "bed (red side) destroyed" on console or chat to make sure that things are going right.
