### ISSUE TITLE
NullPointerException when world is missing.

### ISSUE THREAD

**Issue by iamceph** [ScreamingSandals/BedWars#262]
Statistics holograms, signs and probably other things are not checking if the world exists and throws exceptions. We need to patch that.

Some stack traces from Discord:
https://my.gaagjescraft.net/paste/9HTnMgWf
https://my.gaagjescraft.net/paste/HK56NA8a

Thanks to jurian#5137 for pointing that out.

**Comment by Misat11** [comment]
I'll fix that
