### ISSUE TITLE
Buying a full pair of Armor in one stack

### ISSUE THREAD

**Issue by TheHolyFire** [ScreamingSandals/BedWars#263]
#### Describe the solution you'd like
I would like a feature where you can buy a whole set of Armor(iron) in one Stack
#### Is your feature request related to a problem? Please describe
No

**Comment by dannymozzer** [comment]
> #### Describe the solution you'd like
> I would like a feature where you can buy a whole set of Armor(iron) in one Stack
> 
> #### Is your feature request related to a problem? Please describe
> No

I agree, this is also something I would like to either know how to do, or have as a feature!

**Comment by Square661** [comment]
> #### Describe the solution you'd like
> I would like a feature where you can buy a whole set of Armor(iron) in one Stack
> 
> #### Is your feature request related to a problem? Please describe
> No

Do you mean instead of only getting half armour you want full? I can't remember if there was a way to customize this or not.

**Comment by YodaLightsabr** [comment]
Is there a way to give multiple items in one shop slot? I wish there were better docs.
