### ISSUE TITLE
StatisticsHolograms HashMap memory leak problem

### ISSUE THREAD

**Issue by stovan12** [ScreamingSandals/BedWars#264]
#### Describe the bug
Screaming Bedwars has a memory leak which causes servers left on for a long time to crash.
**Problem:**
https://imgur.com/a/3jaJOJi
_"One instance of "org.screamingsandals.bedwars.holograms.StatisticsHolograms" loaded by "org.bukkit.plugin.java.PluginClassLoader @ 0x706215a28" occupies 437,864,936 (48.32%) bytes. The memory is accumulated in one instance of "java.util.HashMap$Node[]", loaded by "<system class loader>", which occupies 437,864,784 (48.32%) bytes."_

**Solution:**
onPlayerQuitEvent you need to _remove the player object key_ from "StatisticsHolograms.holograms", also, it is _not good practice to use player objects as a key_, this _prevents them from being garbage collected_. I would instead recommend using player UUIDs as keys and calling _Bukkit.getPlayer(UUID)_ when you need a player object.

#### Server and plugin version
Spigot version: 1.16.5
BedWars version: 0.2.15

**Comment by iamceph** [comment]
@Misat11 This shit goes on your hands, I would never have Player as a key! :omegalul:

**Comment by iamceph** [comment]
@stovan12 Good point, thanks :)
