### ISSUE TITLE
Game not starting

### ISSUE THREAD

**Issue by Tuhid123** [ScreamingSandals/BedWars#278]
#### Describe the bug
when i start the game the game does

starting game in 1

starting game in 1.

starting game in 1 

and it never starts

#### Server and plugin version
Spigot version: 1.9
BedWars version:latest

**Comment by pronze** [comment]
You haven't provided any additional details at all, please provide your logs, config.yml and arena file

**Comment by Tuhid123** [comment]
> You haven't provided any additional details at all, please provide your logs, config.yml and arena file

im new here so here is the logs file https://pastebin.com/zcPzKvHa

**Comment by iamceph** [comment]
Old server software, update.
