### ISSUE TITLE
Players getting hurt as soon as the game starts

### ISSUE THREAD

**Issue by Tuhid123** [ScreamingSandals/BedWars#280]
When the game starts players automatically gets hit and dies when they respawn they still take damage
 
 spigot : 1.9.4
 
 bedwars: latest
 
 console file : https://pastebin.com/GvU9BDbK
 confige.yml : https://pastebin.com/tb6rLVjZ
 
 shop.yml : https://pastebin.com/iAnzf5MJ

**Comment by IandresServer** [comment]
moi mon problème C'est que quand je commence une Partie je peut pas leur enlever de dégats !

**Comment by iamceph** [comment]
English only.

**Comment by IandresServer** [comment]
When I hit an enemy, they take no damage, not even 1 heart! Please help me ... I'll open my server soon!

**Comment by IandresServer** [comment]
Help  please

**Comment by IandresServer** [comment]
@iamceph you can help me please ?

**Comment by IandresServer** [comment]
PLEAAAASE 😭😭

**Comment by IandresServer** [comment]
HHHHHHHHHHHHEEEEEEEEEEEEEEEEELP PLEEEEEEEEEEAAAAAAAASE

**Comment by zlataovce** [comment]
join discord and stop spamming https://discord.gg/efgAEFED

**Comment by IandresServer** [comment]
OKAY
