### ISSUE TITLE
Put out fires in arena after match end

### ISSUE THREAD

**Issue by FromenActual** [ScreamingSandals/BedWars#283]
#### Describe the solution you'd like
When the match finishes, extinguish all fires in the area to prevent arena blocks from burning away. The only solution right now is to disable fire, I'd like to have fire enabled in my server.

#### Is your feature request related to a problem? Please describe
If a fire gets ignited for any reason, and fire tick is enabled, the fire spreads to flammable blocks that are part of the arena. During the match, the area blocks are not destroyed, but once the match finishes, the fires are not extinguished and they are able to destroy arena blocks (I burned an entire building in testing).

**Comment by Misat11** [comment]
This is more like bug than feature request, so I'm giving this issue correct labels.

**Comment by FromenActual** [comment]
Thanks, just seemed to me like fire wasn't implemented yet, I thought I'd just gone beyond the feature scope of this plugin with fire 🔥

**Comment by zlataovce** [comment]
a fix was implemented, closing this issue.
