### ISSUE TITLE
Can't eat enemy cake?

### ISSUE THREAD

**Issue by bG9sIHVyIGhvbW8** [ScreamingSandals/BedWars#285]
#### Describe the bug
On CakeWars; whenever attempting to eat an enemies cake, I'm unable to eat the cake fully, there's just one bite left.

#### Server and plugin version
Spigot version: 1.12.2 Paper
BedWars version: 0.2.15

#### Installed plugins on server (can be obtained by `/pl`)
Before filing a bug report, I tested with only 4 plugins: BedWars, LuckPerms, Multiverse-Core and Vault; same issue occurs.

#### Console log
No warnings or errors are outputted to Console by the plugin.

#### Configuration (of config.yml and shop.yml)
https://pastebin.com/QzdziUJt - config.yml
https://pastebin.com/iXatExpY - shop.yml

#### If there are problem with only one game, paste here config of this game
https://pastebin.com/R14fwaD0 - arena .yml file

**Comment by iamceph** [comment]
There should be a config settings for this, try checking it

**Comment by bG9sIHVyIGhvbW8** [comment]
> There should be a config settings for this, try checking it

What option?

**Comment by IandresServer** [comment]
GUYS HELP ME

**Comment by iamceph** [comment]
It is in the configuration.
