### ISSUE TITLE
Unable to rightclick armor stand.

### ISSUE THREAD

**Issue by Developer-Doge** [ScreamingSandals/BedWars#286]
#### Describe the bug
Unable to rightclick the armor stand for team selection.

#### Server and plugin version
Spigot version: Cardboard
BedWars version: Newest (3/18/2021)

#### Installed plugins on server (can be obtained by `/pl`)
multiverse portals
multiverse signs

#### Console log
normal vanilla logs

#### Configuration (of config.yml and shop.yml)
default

**Comment by zlataovce** [comment]
are you using a stable version? "normal vanilla logs" doesn't help, send them. 


Cardboard Spigot doesn't exist, are you using Paper or normal Spigot?

**Comment by Developer-Doge** [comment]
> are you using a stable version? "normal vanilla logs" doesn't help, send them.
> 
> Cardboard Spigot doesn't exist, are you using Paper or normal Spigot?

https://www.curseforge.com/minecraft/mc-mods/cardboard

**Comment by zlataovce** [comment]
is that a server software or a plugin/mod? provide the logs also

**Comment by Developer-Doge** [comment]
> is that a server software or a plugin/mod? provide the logs also

Mod so that I can run fabric mods alongside spigot plugins

**Comment by iamceph** [comment]
Not our problem, contact mod author.

**Comment by Developer-Doge** [comment]
> Not our problem, contact mod author.

How can you draw that sort of conclusion, thats like saying because im running magma you automatically get to dodge an actual bug

**Comment by galfar-coder** [comment]
Its not a bug from the plugin. 
# Works normally.

**Comment by iamceph** [comment]
> > Not our problem, contact mod author.
> 
> How can you draw that sort of conclusion, thats like saying because im running magma you automatically get to dodge an actual bug

I can say that clearly because this plugin is written for CraftBukkit and uses NMS for Holograms. Therefore, anything that is not CraftBukkit (or fork) cannot run it. Understandable?

**Comment by linusstretchtips** [comment]
> I can say that clearly because this plugin is written for CraftBukkit and uses NMS for Holograms. Therefore, anything that is not 
> CraftBukkit (or fork) cannot run it. Understandable?

Cephs answer was 10/10. 
1) ceph, u angry or somethin today?
2) brillient answer
3) you downloaded the plugin on SPIGOT so you run SPIGOT / CRAFTBUKKIT software or any other fork. use some common sense tbh
