### ISSUE TITLE
Hearts below the player's name

### ISSUE THREAD

**Issue by Tobstr02** [ScreamingSandals/BedWars#290]
#### Describe the solution you'd like
Would be really nice if you add hearts like 20❤ below the name.

#### Is your feature request related to a problem? Please describe

**Comment by YodaLightsabr** [comment]
> #### Describe the solution you'd like
> Would be really nice if you add hearts like 20❤ below the name.
> 
> #### Is your feature request related to a problem? Please describe

@Tobstr02 Use a scoreboard and set it to belowname

**Comment by Tobstr02** [comment]
tried to do it. But as you start playing bedwars it dissapears

**Comment by AmazingAidan25** [comment]
bro misat is a genius.

**Comment by bijuu123** [comment]
You may Use SBA 1.5.5 for it
Use Bedwars 0.2.18 Only for that
Install java 11 or 16

That may be good
