### ISSUE TITLE
MySQL-Tables aren't generated

### ISSUE THREAD

**Issue by jannis6023** [ScreamingSandals/BedWars#291]
#### Describe the bug
The MySQL-Tables aren't generated. The Plugin queries the DB, no connection problems. Error when reading caused by missing table. No Tables are created by the plugin. Permissions already checked.

#### Server and plugin version
Spigot version: 1.9
BedWars version: latest spigotmc.org

#### Console log
```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'bedwars.bw_stat
s_players' doesn't exist
```

#### Configuration (of config.yml and shop.yml)
typical MySQL-Configuration, nothing special

**Comment by jannis6023** [comment]
Another Log loading the Plugin:
```
https://just-paste.it/pT8F698xBh
```

**Comment by Tobstr02** [comment]
Same issue here

**Comment by pronze** [comment]
I know I'm a bit late, but please can you provide us with your logs?, it would help us in diagnosing this issue.

**Comment by smpial** [comment]
same problem

**Comment by Misat11** [comment]
Try creating the table manually

```sql
CREATE TABLE IF NOT EXISTS `bw_stats_players` (
   `kills` int(11) NOT NULL DEFAULT '0', 
   `wins` int(11) NOT NULL DEFAULT '0', 
   `score` int(11) NOT NULL DEFAULT '0', 
   `loses` int(11) NOT NULL DEFAULT '0', 
   `name` varchar(255) NOT NULL, 
   `destroyedBeds` int(11) NOT NULL DEFAULT '0', 
   `uuid` varchar(255) NOT NULL, 
   `deaths` int(11) NOT NULL DEFAULT '0', 
   PRIMARY KEY (`uuid`)
);
```

**Comment by smpial** [comment]
Can the database store arena data? Or can it only store player statistics?

**Comment by Misat11** [comment]
only statistics

**Comment by smpial** [comment]
ok, thanks
