### ISSUE TITLE
How to create team upgrade

### ISSUE THREAD

**Issue by Lun3z** [ScreamingSandals/BedWars#292]
Can we create team upgrade ? If yes how ?

**Comment by zlataovce** [comment]
use [SBAHypixelify](https://www.spigotmc.org/resources/addon-sbahypixelify-for-screaming-bedwars-1-9-4-1-16-4.79505/)

**Comment by pronze** [comment]
You can use SBAHypixelify, or read the following wiki page: https://github.com/ScreamingSandals/BedWars/wiki/Upgrades
