### ISSUE TITLE
Missing traduction value

### ISSUE THREAD

**Issue by MinDBreaK** [ScreamingSandals/BedWars#296]
#### Describe the bug
I am not sure, this might need requalification to send it to Hypixelify. This only applies when buying an upgrade for a spawner. The message is not translated. See screenshot. There is no upgrade message to the team on upgrade despite being configured. 
![image](https://user-images.githubusercontent.com/15737031/113699273-9fe94f00-96d5-11eb-873b-54f214ba3a66.png)

#### Server and plugin version
Spigot version: PaperMC 1.16.5 (build 581)
BedWars version: 0.2.15

#### Installed plugins on server (can be obtained by `/pl`)
BedWars, Multiverse-Core, SBAHypixelify

#### Console log
https://paste.gg/p/anonymous/eb6fe421b57f4120be53d7f52ee103c5

#### Configuration (of config.yml and shop.yml)
https://paste.gg/p/anonymous/bfbe1f8dc77f42fd86c6c381876c358b

**Comment by iamceph** [comment]
Hypixelify bug.
