### ISSUE TITLE
Ore spawner

### ISSUE THREAD

**Issue by zaeldyt** [ScreamingSandals/BedWars#297]
Hello, I would like to know if it is possible to create new ore spawners (I would like to create a diamond spawner),
thank you

**Comment by GreenTNS** [comment]
It is possible to create new ore spawner. Simply go into your config and go to resources. Then add the diamond spawner.
Here's an example:
resources:
  emerald:
    material: EMERALD
    color: GREEN
    name: Emerald
    interval: 60
    translate: resource_emerald
    spread: 1.0
  diamond:
    material: DIAMOND
    color: BLUE
    name: Diamond
    interval: 30
    translate: resource_diamond
    spread: 1.0
  iron:
    material: IRON_INGOT
    color: WHITE
    name: Iron
    interval: 2.5
    translate: resource_iron
    spread: 1.0
  gold:
    material: GOLD_INGOT
    color: GOLD
    name: Gold
    interval: 8
    translate: resource_gold
    spread: 1.0

**Comment by zaeldyt** [comment]
c'est ce que j'ai fait, pourtant, cela ne fonctionne pas
![2021-04-12 (2)](https://user-images.githubusercontent.com/82387110/114400340-22748180-9ba2-11eb-9fc0-8b489a252850.png)
![2021-04-12 (3)](https://user-images.githubusercontent.com/82387110/114400906-b9d9d480-9ba2-11eb-89cf-e4c861a0c4a3.png)

**Comment by zaeldyt** [comment]
this is what i did, yet it doesn't work

**Comment by zaeldyt** [comment]
Help me please

**Comment by notfoundname** [comment]
LIGHT_BLUE does not exist, use just BLUE

**Comment by zaeldyt** [comment]
Yes, but it doesn't work for any minerals

**Comment by zaeldyt** [comment]
I modified this, and the ores are all present in the game, thanks :)
