### ISSUE TITLE
improved stores

### ISSUE THREAD

**Issue by zaeldyt** [ScreamingSandals/BedWars#298]
Hello again, I would like to know if it was possible to create stores like on hypixel (screen below) with a shortcut category and also see the categories at the top of the shop.
If this is not in the plugin, then it will be good if this is added, if possible.
Thank you
![2021-04-13_19 40 49](https://user-images.githubusercontent.com/82387110/114596936-7cec0b80-9c90-11eb-9565-cd680715c646.png)
![Inked2021-04-13_19 40 44_LI](https://user-images.githubusercontent.com/82387110/114597001-8d9c8180-9c90-11eb-9b06-3148da292ae5.jpg)

**Comment by iamceph** [comment]
You can edit the shop, use shop.yml.

**Comment by zaeldyt** [comment]
I know, but is it possible to modify the file to do what I want to do?

**Comment by zaeldyt** [comment]
?

**Comment by GreenTNS** [comment]
Use SBA Hypixelify

**Comment by zaeldyt** [comment]
okey thanks
