### ISSUE TITLE
Egg Wars Generators

### ISSUE THREAD

**Issue by arttwart** [ScreamingSandals/BedWars#300]
Hello.

Plugin allows us to change the block type. That's great! I would love to make an Egg Wars game setup, but plugin doesn't  support sign generators like the original Egg Wars. Can you add that?

Basic features:
1. Editable sign texts
2. Generator levels
3. Editable item spawn rate per level
4. Generator upgrade GUI
5. Fireworks when we update generator
6. Editable generated item

Plus, probably you know how Egg Wars works, so I don't want to be more spesific.

**Comment by Misat11** [comment]
Added to our todo list for version 0.3.0: https://trello.com/c/B5p4aRHq/33-egg-wars-original-generators
