### ISSUE TITLE
Leftover TnT Destroys map after game

### ISSUE THREAD

**Issue by TheHappyHopper** [ScreamingSandals/BedWars#302]
#### Describe the bug
When the game ends, primed tnt left over from the end of the game will destroy the arena

#### Server and plugin version
Spigot version: git-Yatopia-ver/1.16.5-88
BedWars version:0.2.15

#### Installed plugins on server (can be obtained by `/pl`)

![2021-04-25_15 18 11](https://user-images.githubusercontent.com/66880702/116011534-615efa00-a5da-11eb-8a74-00050458fb41.png)

#### Console log
Nothing

**Comment by Misat11** [comment]
This should be fixed in the snapshot versions, however they are unstable for using in production environment.

**Comment by LoveScreamingBw** [comment]
Hello everyone
