### ISSUE TITLE
ARENA GAME MODE

### ISSUE THREAD

**Issue by LoveScreamingBw** [ScreamingSandals/BedWars#304]
Hello everyone, in fact a while ago I opened a mini-games bedwars server etc ... so I created a SOLO mode arena I configured it etc ... all works very well so far. when I joined the arena in the scoreboard there is MODE: SQUADS written while I want this arena to be in SOLO mode I have the SBAHypixelify addon! Is there a possibility to change the game mode of the arena? If so, thank you for answering me.

Thank you Sincerely, have a good evening.

LoveScreamingBw.

**Comment by iamceph** [comment]
Hypixelify issue, not ours :)

**Comment by LoveScreamingBw** [comment]
Okay Thank.
