### ISSUE TITLE
Deleted arenas 

### ISSUE THREAD

**Issue by gav1818** [ScreamingSandals/BedWars#306]
#### Describe the bug
 WHEN I LEAVE MY MINEHUNT SERVER AND COME BACK THE NEXT DAY, MY ARENAS ARE DELTED, THE MAPS ARE STILL THERE, BUT I HAVE TO REDO ALLL THE SPAWN POINTS, TEAMS, Etc
#### Server and plugin version
Spigot version:
BedWars version: 1.16.5

**Comment by zlataovce** [comment]
minehut is known to be problematic with their world management, we can do nothing about this unfortunately

**Comment by iamceph** [comment]
Not our problem.
