### ISSUE TITLE
[1.16.5] Unable to place block

### ISSUE THREAD

**Issue by UQRARA** [ScreamingSandals/BedWars#308]
I cannot place any blocks after the game starts, but I can place them next to the bed  :(

Other functions are normal
Game version: 1.16.5[arclight]
Bw version: 0.2.15

Plugin:
EssentialsX
AuthMe
Worldedit
Worldguard
Multiverse-Core
GroupManager

**Comment by UQRARA** [comment]
I apologize, This is my logs

**Installed plugins on server** 
EssentialsX  AuthMe  AdvancedNMotd  Worldedit  Worldguard  Multiverse-Core  
GroupManager  BentoBox  BedWars  KeepInventory TAB  VoidGenerator

**Console log**
[latest.log](https://github.com/ScreamingSandals/BedWars/files/6476902/latest.log)

**BWConfig**
[config.txt](https://github.com/ScreamingSandals/BedWars/files/6476912/config.txt)

**arenas**
[浮空平台.txt](https://github.com/ScreamingSandals/BedWars/files/6476913/default.txt)

**Comment by zlataovce** [comment]
make sure you are not protecting your arena with worldguard or any other plugin and make sure you have set spawn-protection in server.properties to 0

**Comment by UQRARA** [comment]
Yes, I'm pretty sure no other protection plug-ins have been used

**Comment by UQRARA** [comment]
> Yes, I'm pretty sure no other protection plug-ins have been used

This is because the arena cannot be placed when it is started

When the arena is not activated, it can be destroyed and built

**In addition, you can place block on the bed**
