### ISSUE TITLE
Shop,s will not spawn

### ISSUE THREAD

**Issue by Ethmangameon** [ScreamingSandals/BedWars#309]
#### Server and plugin version
Spigot version: 1.16
BedWars version: latest

#### Installed plugins on server (can be obtained by `/pl`)
Essentials
BedWars 
Citizenscmd
Citizens 
#### Console log 
[latest.log](https://github.com/ScreamingSandals/BedWars/files/6468438/latest.log)

#### Configuration (of config.yml and shop.yml) 
Default

**Comment by zlataovce** [comment]
`there is no error in console` is not a log, stick to the issue template


- Make sure that Mob Spawning is ENABLED
- Make sure that NPC's are Enabled

**Comment by Ethmangameon** [comment]
> `there is no error in console` is not a log, stick to the issue template
> 
> * Make sure that Mob Spawning is ENABLED
> * Make sure that NPC's are Enabled
wdym NPS,s are Enabled

**Comment by iamceph** [comment]
Update to latest version.
