### ISSUE TITLE
Kick at end

### ISSUE THREAD

**Issue by luchs888** [ScreamingSandals/BedWars#310]
Describe the bug

At the end of each round, all players are kicked

Server and plugin version
Paper 1.16.5
ScreamingBedwars version: 0.2.15

Config part

bungee:
enabled: false
serverRestart: false
serverStop: false
server: Lobby
auto-game-connect: true

without error messages in logs

Kick Message "The server you were previously went down, you have been connected to a fallback server"

The server is still on and the player are not tpt to the fallback server (we try it whit bungee on and off)

**Comment by iamceph** [comment]
Update to latest version.
