### ISSUE TITLE
Match does not start

### ISSUE THREAD

**Issue by gs24092007** [ScreamingSandals/BedWars#312]
I have made a bedwars map meant for Duos but when i join the game the mode shows quads and even when this minimum player requirement is matched it doesn't start and the countdown gets stuck on 1

**Comment by zlataovce** [comment]
change the player-size variable per arena in hypixelify's config (1 = solo, 2 = double, 3 = triple, 4 = squads)


keep in mind that all of the players need to join a team before the game starts, turn on this setting to have them join random teams after lobby countdown: `join-randomly-after-lobby-timeout`


for future issue submissions, please stick to the issue template
