### ISSUE TITLE
Flow property lost as soon as arena is created

### ISSUE THREAD

**Issue by itsmemac** [ScreamingSandals/BedWars#314]
#### Describe the bug
As soon as you create an arena in-game and save it, the blocks inside the arena loses MC default behaviour
eg : lava flow, water flow

#### Server and plugin version
Spigot version: Paper version git-Paper-652 (MC: 1.16.5)
BedWars version: Screaming BedWars [1.9 - 1.16] 0.2.15

#### Installed plugins on server (can be obtained by `/pl`)
BattleTraining, BedWars, Citizens, DeluxeMenus, DiceFurniture, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, FurnitureLib, HeadDatabase, HeadDisplays, HolographicDisplays, HolographicExtension, Images, LiteBans, LuckPerms, Maintenance, Multiverse-Core, MysqlEcoBridge, OldCombatMechanics, PlaceholderAPI, ProtectionLib, ProtocolLib, SBAHypixelify, ServerUtils, SpawnJoin, TAB, TAB-BukkitBridge, TitleManager, UltraCustomizer, Vault, VoidGenerator, VoidSpawn, WDLCompanion, WorldEdit, WorldEditSelectionVisualizer, WorldGuard and spark

#### Console log
https://pastebin.com/ZV1YCuWw

#### Configuration (of config.yml and shop.yml)
[config.yml](https://pastebin.com/8SvpVTeb)
[Shop.yml](https://pastebin.com/9yNCyzKH)

#### Images
[Arena setup done](https://cdn.discordapp.com/attachments/582272127198167078/845004941680836658/2021-05-20_23.57.38.png)
[Arena setup not done](https://cdn.discordapp.com/attachments/582272127198167078/845005239999397888/2021-05-20_23.58.41.png)

#### World guard , Essentials and other configs
[Essentials Config](https://pastebin.com/TAA47MJA)
[World guard config](https://pastebin.com/uuFuHPBs)
[server.properties](https://pastebin.com/GbZjF326)
[World guard world config (same for all the worlds)](https://pastebin.com/hmmXYzNU)

Tried with essentials, worldguard. WDLCompanion and worldedit disabled also removed -- still the same issue

**Comment by Misat11** [comment]
As long as arena is enabled and waiting for players, the bedwars protects it from being changed by mc behaviour. Once you turn arena to edit mode or the game starts, flowing should work again.
