### ISSUE TITLE
can you port to Nukkit

### ISSUE THREAD

**Issue by DesertSoldier43** [ScreamingSandals/BedWars#317]
#### Describe the solution you'd like
can you port to Nukkit with an option for a SimpleFormWIndow (for mobile players) which is basically just a UI

I want to when u spawn in the main lobby, not the bedwars lobby, to have an item that pops up a UI that can toggle mobile or pc mode which PC mode has a chest UI and not just buttons. Thankfully, the API is somewhat similar like bukkit, but there ARE SOME differences. Thanks

#### Is your feature request related to a problem? Please describe
No, just an AMAZING FEATURE for the Bedrock players. It would be TRULY GRATEFUL. PLEASE.

**Comment by zlataovce** [comment]
I am pretty sure that misat won't support bedrock at all. Your best bet is to use Geyser, if you want it for bedrock.

**Comment by Misat11** [comment]
Minecraft: Bedrock edition is not platform we are targeting rn (possibly in future we can think of that), porting the whole plugin won't be really easy because MC: Java and MC: Bedrock are completely different platforms and we are not experienced in this world. There is other project called Geyser which you can use to join java server with bedrock client.

**Comment by DesertSoldier43** [comment]
> Minecraft: Bedrock edition is not platform we are targeting rn (possibly in future we can think of that), porting the whole plugin won't be really easy because MC: Java and MC: Bedrock are completely different platforms and we are not experienced in this world. There is other project called Geyser which you can use to join java server with bedrock client.

but it is so laggy

**Comment by DesertSoldier43** [comment]
can I port it

**Comment by zlataovce** [comment]
this project is opensource, so yes, you can try to port it to nukkit, but we won't provide support for it.

**Comment by DesertSoldier43** [comment]
> this project is opensource, so yes, you can try to port it to nukkit, but we won't provide support for it.

and what file is equal to pom.xml in maven. I use maven and have never used gradle. And what dependencies are there for example. MySQL etc
