### ISSUE TITLE
Respawning issue with viaversion

### ISSUE THREAD

**Issue by jacobvd0** [ScreamingSandals/BedWars#320]
#### Describe the bug
Hi I have this plugin running on a 1.12.2 paper server and when a player dies when using 1.16 via viaversion their screeen freezes for a few seconds.

#### Server and plugin version
Spigot version:
![image](https://user-images.githubusercontent.com/46667568/120910075-e26dde80-c6ba-11eb-8ce3-f3862c5db55f.png)

BedWars version: 0.2.15

#### Installed plugins on server (can be obtained by `/pl`)
BedWars, Essentialsx, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, LuckPerms, SBAHypixelify, Skript, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard
#### Console log
https://pastebin.com/rAfhX6rZ
#### Configuration (of config.yml and shop.yml)
https://pastebin.com/bK9uNp03 config.yml
https://pastebin.com/LQx7QYBJ shop.yml

**Comment by notfoundname** [comment]
try enabling allow-fake-death

**Comment by iamceph** [comment]
Update to latest version.
