### ISSUE TITLE
Spigot Plugin Not Updated

### ISSUE THREAD

**Issue by PikachuPlays** [ScreamingSandals/BedWars#322]
I make servers using Aternos because I don't have a lot of free money to spend on a server. Aternos does allow plugins but they have to be popular enough and from a trusted website. Spigot being one of them. The ScreamingBedWars plugins latest update is from November 29th 2020. I use the software paper, which is just spigot upgraded.

#### Server and plugin version
Paper version: #777
BedWars version: 0.2.15

#### Installed plugins on server (can be obtained by `/pl`)
Skin Restorer
ScreamingBedWars
SBA for ScreamingBedWars
HoloGraphicDisplays
OldCombatMechanics

**Comment by zlataovce** [comment]
0.2.15 is the latest stable version, there is no update to be put onto the spigot page yet
