### ISSUE TITLE
/bw reload & Multiple Bugs have occured 

### ISSUE THREAD

**Issue by Bulldo344** [ScreamingSandals/BedWars#327]
This plugin breaks a lot with loads of configurations to the yml files specifically the configs & the other files. I spend 5+ hours setting it up; every time I configure the file, it breaks the script.

The main thing that breaks 24/7 is the NPCs, and then I try to fix them, and everything breaks.

![image](https://user-images.githubusercontent.com/53837083/122865918-2258d680-d2f5-11eb-8172-3f97c20e89e1.png)
https://paste.shockbyte.com/undefined

If you have like a YAML error fixer or something or if somebody can help me fix this issue, that would be greatly appreciated.

**Comment by Bulldo344** [comment]
https://paste.shockbyte.com/undefined

**Comment by Bulldo344** [comment]
Bug shorten to; 

Keep in mind, this is only a bug that has to do with squads, the rest of the game modes are fine.

https://cdn.discordapp.com/attachments/582689305751978024/856763008017891328/unknown.png 
https://paste.shockbyte.com/evumuhukepodilefojob
https://paste.gg/p/anonymous/5ae441f08dcb4ae89144caed40e696bc

**Comment by pronze** [comment]
Seems like an issue with SBA, next time report issues regarding SBA here: https://github.com/pronze/SBA/issues
