### ISSUE TITLE
FEATURE REQUEST (MUST NEED)

### ISSUE THREAD

**Issue by Hoangviphb999** [ScreamingSandals/BedWars#333]
#### Describe the solution you'd like
Hi ScreamingBedwars Staff Team!
I have used ScreamingBedwars and it perfect for Minecraft Java server and GeyserMC too and I want to add some feature must have.
1. ScreamingBedwars setup is really hard for Minecraft GeyserMC player, and i want to add GUI setup for both Java and Bedrock
2. Since Floodgates now support Bedrock forms UI so i want this plugins implentment forms UI for Bedrock client.
Well everything i want is done, wish developer always doing these great things.
Thanks!!!
Hoàng Wibu#7887 (on discord)

**Comment by iamceph** [comment]
We don't support Geyser, if something is broken, they need to fix it. :P

**Comment by Hoangviphb999** [comment]
> We don't support Geyser, if something is broken, they need to fix it. :P

I mean support Bedrock forms for Bedrock player cuz Floodgates support Bedrock forms

**Comment by Hoangviphb999** [comment]
And the setup GUI to easier setup
