### ISSUE TITLE
Is it possible to add own SpecialItems?

### ISSUE THREAD

**Issue by Placeblock** [ScreamingSandals/BedWars#337]
I tried to create my own special item, for this i added an Interface and an Impl class
In the bedwars source code the interface extends from BWPlayer, but for me there is no BWPlayer, GameImpl etc in the API?
Am i doing something wrong?

Maybe you can help me : )
have a great day!

**Comment by Misat11** [comment]
hello. The master branch is used for upcoming version 0.3.0. For 0.2.x source code check 0.2.16 branch

**Comment by PlaceblockHD** [comment]
So you cant create special items with only the api?

**Comment by iamceph** [comment]
Az @zlataovce described, you need to implement the API and then add dependency on BedWars as compileOnly. You can create items with API.
