### ISSUE TITLE
Diamond and Emerald Generators Small and don't spin

### ISSUE THREAD

**Issue by AmazingAidan25** [ScreamingSandals/BedWars#339]
I was testing out the new bedwars version with my friends and one of them pointed out that the generators were not spinning. I went to go have a look for myself and sure enough, they were stuck in place. I'm running 2.18-14 bedwars and 1.5.5 SBA. The armorstands that usually are there looked like the generators had been swapped for player heads. What do I do to fix this? I have a bedwars tournament coming up that I'm hosting and I want the generators to be working properly.

Thanks,
AmazingAidan25

**Comment by iamceph** [comment]
@AmazingAidan25 I never heard about that version of BW. Please provide correct version and details.

**Comment by zlataovce** [comment]
closed as stale
