### ISSUE TITLE
Gameinv command not showing up. 

### ISSUE THREAD

**Issue by AmazingAidan25** [ScreamingSandals/BedWars#340]
When I try to do the /Sba gamesinv doubles, the plug-in gives me an improper syntax error through chat. Ive enabled all the settings for gamesinv but nothing works. I’m running paper 1.17 and bedwars 2.18-14. I use sba 1.5.5. Can anyone help?

**Comment by zlataovce** [comment]
you're on the bedwars repo, not the sba one and gamesinv was disabled in one of the latest updates

**Comment by AmazingAidan25** [comment]
How would I do a gamesinv style thing now?

**Comment by KnowItAllNetwork** [comment]
> How would I do a gamesinv style thing now?

you can use the custom setup from #custom-setups in the discord server of screaming sandals.

**Comment by iamceph** [comment]
Unknown BedWars version,
