### ISSUE TITLE
Get kick when playing

### ISSUE THREAD

**Issue by Itzmefoxy** [ScreamingSandals/BedWars#341]
I just want to test out, and when I play after 5-10 seconds I get kicked

Spigot version: 1.17.1
BedWars version: 0.2.18 (To use SBA)

Screaming Bedwars

![image](https://user-images.githubusercontent.com/68133216/130380472-b1a2b112-63a0-4dc7-af34-c32d4759889c.png)

-

-

**Comment by Misat11** [comment]
bedwars 0.2.18 is not compatible with mc 1.17.1 (only with 1.17), for mc 1.17.1 there's bw 0.2.19, however it's not compatible with sba 1.5.5 (but it is compatible with the snapshot builds of sba from jenkins)
