### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by Aadi-mone** [ScreamingSandals/BedWars#347]
**#### Describe the bug**

Can you please say is there a way for auto equipping the armor after buying and a way to add team upgrades, I don't want to use SBA Hypixelfy Addon because it's too heavy and buggy? if there is a way that would be really helpful!

**#### Server and plugin version**

PapperMC 1.16
BedWars version: 0.2.18

**#### Installed plugins on the server (can be obtained by `/pl`)**

Just the plugin in that server I am using bungeechrode 

**#### Console log**

<html>
<body>

[09:39:04] [Server thread/INFO]: [BedWars] Enabling BedWars v0.2.18
--
522 | [09:39:04] [Server thread/INFO]: [BedWars] Successfully loaded messages for BedWars! Language: English
523 | [09:39:04] [Server thread/INFO]: [BedWars] Loading statistics from YAML-File ...
524 | [09:39:04] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: bedwars
525 | [09:39:04] [Server thread/INFO]: ===================== by ScreamingSandals <Misat11, Iamceph, Pronze>
526 | [09:39:04] [Server thread/INFO]: + Screaming BedWars + Version: 0.2.18 FREE
527 | [09:39:04] [Server thread/INFO]: ===================== STABLE VERSION
528 | [09:39:04] [Server thread/INFO]: [BW] Found Vault
529 | [09:39:04] [Server thread/INFO]: [BW] Arena SwashBuckel loaded!
530 | [09:39:04] [Server thread/INFO]: [BW] Arena Aquarim loaded!
531 | [09:39:04] [Server thread/INFO]: [BW] Arena Ashore loaded!
532 | [09:39:04] [Server thread/INFO]: [BW] Arena DreamGroove loaded!
533 | [09:39:04] [Server thread/INFO]: Everything is loaded! If you like our work, consider visiting our Patreon! <3
534 | [09:39:04] [Server thread/INFO]: https://www.patreon.com/screamingsandals

</body>
</html>

#### Configuration (of config.yml and shop.yml)

Default, Not changed!! 

#### If there are problems with only one game, paste here the config of this game
N/A

**Comment by zlataovce** [comment]
there is no way to have armor auto equip in the current stable version of BedWars, but it's going to be in the upcoming 0.3.0 version.
upgrades can be added by modifying the shop.yml file or making a new shop file: https://github.com/ScreamingSandals/BedWars/wiki/Upgrades

**Comment by zlataovce** [comment]
you can modify the scoreboard in the language file for yourself

**Comment by Aadi-mone** [comment]
No, we can just modify the waiting lobby scoreboard!!
And what is the placeholder for gens upgrade and the more??

**Comment by Aadi-mone** [comment]
@zlataovce  Can I get a response?

**Comment by zlataovce** [comment]
placeholders are in the [wiki](https://github.com/ScreamingSandals/BedWars/wiki/PlaceholderAPI-placeholders)
