### ISSUE TITLE
Enormous Bug! Kicking from the server. 

### ISSUE THREAD

**Issue by Superior126** [ScreamingSandals/BedWars#349]
When you try to play a game it works fine but after about 30 secs, everyone in the game gets kicked. Sometimes when rejoining it says our connection is throttled. I have to use a slightly older version of the plugin because the newest version wont work with the addon. 

Spigot version: 1.17.1
BedWars version: 0.2.18-14

**Comment by zlataovce** [comment]
0.2.18 does not support 1.17.1. update to 0.2.19.
