### ISSUE TITLE
Some players see red at side of screen and not able to place,break block and just able to pvp in duos map (Airshow,Rooftop)

### ISSUE THREAD

**Issue by MyBedwars** [ScreamingSandals/BedWars#354]
#### Describe the bug
Some players see red at side of screen and not able to place,break block and just able to pvp in duos map (Airshow,Rooftop)
#### Server and plugin version
Spigot version: 1.16.5
BedWars version: 0.2.18 (To use SBA)

#### Installed plugins on server (can be obtained by `/pl`)
BedWars-0.2.18-14.jar
DeluxeHub-3.3.10.jar
IridiumSkyblock-3.0.6.jar
Multiverse-Core-4.3.0.jar
Multiverse-Inventories-4.2.2.jar
oneblock.jar
OpenLogin.jar
PlaceholderAPI-2.10.9.jar
SBA-1.5.5.jar
Vault.jar
ViaRewind-2.0.1.jar
ViaBackwards-4.0.1.jar
ViaVersion-4.0.1.jar
worldedit-bukkit-7.2.6.jar
worldguard-bukkit-7.0.5-dist.jar
znpc-servers.jar
#### Console log
says nothing
#### Configuration (of config.yml and shop.yml)
Console:
locale: en
debug: false
allow-crafting: false
keep-inventory-on-death: false
in-lobby-colored-leather-by-team: true
jointeam-entity-show-name: true
friendlyfire: false
player-drops: false
join-randomly-after-lobby-timeout: true
prevent-killing-villagers: true
compass-enabled: true
join-randomly-on-lobby-join: false
add-wool-to-inventory-on-join: true
prevent-spawning-mobs: true
spawner-holograms: false
spawner-disable-merge: true
prevent-lobby-spawn-mobs-in-radius: 16
spawner-holo-height: 0.25
spawner-holograms-countdown: true
damage-when-player-is-not-in-arena: true
remove-unused-target-blocks: true
allow-block-falling: true
game-start-items: true
player-respawn-items: false
gived-game-start-items:

wooden_sword
leather_helmet
leather_boots
leather_leggings
leather_chestplate
disable-hunger: true
automatic-coloring-in-shop: true
sell-max-64-per-click-in-shop: true
destroy-placed-blocks-by-explosion-except:
''
destroy-placed-blocks-by-explosion: true
holo-above-bed: true
allow-spectator-join: true
disable-server-message:
player-join: false
player-leave: false
respawn-cooldown:
enabled: true
time: 5
stop-team-spawners-on-die: false
allowed-commands: []
change-allowed-commands-to-blacklist: false
bungee:
enabled: false
serverRestart: true
serverStop: false
server: hub
auto-game-connect: true
kick-when-proxy-too-slow: true
motd:
enabled: false
waiting: '%name%: Waiting for players [%current%/%max%]'
waiting_full: '%name%: Game is full [%current%/%max%]'
running: '%name%: Game is running [%current%/%max%]'
rebuilding: '%name%: Rebuilding...'
disabled: '%name%: Game is disabled'
farmBlocks:
enable: false
blocks: []
scoreboard:
enable: false
title: §a%game%§r - %time%
bedLost: §c✘
bedExists: §aheavy_check_mark
teamTitle: '%bed%%color%%team%'
anchorEmpty: §e✘
title:
enabled: false
fadeIn: 0
stay: 0
fadeOut: 0
items:
jointeam: COMPASS
leavegame: RED_BED
startgame: DIAMOND
shopback: BARRIER
shopcosmetic: GRAY_STAINED_GLASS_PANE
pageback: ARROW
pageforward: ARROW
team-select: WHITE_WOOL
vault:
enable: false
reward:
kill: 5
win: 20
final-kill: 5
bed-destroy: 0
resources:
emerald:
material: EMERALD
color: GREEN
name: Emerald
interval: 60
translate: resource_emerald
spread: 0.1
diamond:
material: DIAMOND
color: BLUE
name: Diamond
interval: 30
translate: resource_diamond
spread: 0.1
iron:
material: IRON_INGOT
color: WHITE
name: Iron
interval: 2.5
translate: resource_iron
spread: 1.0
gold:
material: GOLD_INGOT
color: GOLD
name: Gold
interval: 8
translate: resource_gold
spread: 1.0
respawn:
protection-enabled: true
protection-time: 5
specials:
action-bar-messages: true
rescue-platform:
is-breakable: false
delay: 0
break-time: 10
distance: 1
material: GLASS
protection-wall:
is-breakable: false
delay: 20
break-time: 0
width: 5
height: 3
distance: 2
material: CUT_SANDSTONE
tnt-sheep:
speed: 2.0
follow-range: 10.0
max-target-distance: 32
explosion-time: 8
arrow-blocker:
protection-time: 10
delay: 5
warp-powder:
teleport-time: 6
delay: 0
magnet-shoes:
probability: 75
golem:
speed: 0.25
follow-range: 10
health: 20
name-format: '%teamcolor%%team% Golem'
show-name: true
delay: 0
collidable: false
teamchest:
turn-all-enderchests-to-teamchests: true
throwable-fireball:
explosion: 3.0
damage: 2.0
auto-igniteable-tnt:
explosion-time: 3
damage-placer: true
tnt: {}
sounds:
on_trap_triggered: ENTITY_ENDERMAN_TELEPORT
bed_destroyed:
sound: ENTITY_ENDER_DRAGON_GROWL
volume: 1
pitch: 1
my_bed_destroyed:
sound: ENTITY_ENDER_DRAGON_GROWL
volume: 1
pitch: 1
countdown:
sound: UI_BUTTON_CLICK
volume: 1
pitch: 1
game_start:
sound: ENTITY_PLAYER_LEVELUP
volume: 1
pitch: 1
team_kill:
sound: ENTITY_PLAYER_LEVELUP
volume: 1
pitch: 1
player_kill:
sound: ENTITY_PLAYER_BIG_FALL
volume: 1
pitch: 1
item_buy:
sound: ENTITY_ITEM_PICKUP
volume: 1
pitch: 1
upgrade_buy:
sound: ENTITY_EXPERIENCE_ORB_PICKUP
volume: 1
pitch: 1
respawn_cooldown_wait:
sound: UI_BUTTON_CLICK
volume: 1
pitch: 1
respawn_cooldown_done:
sound: ENTITY_PLAYER_LEVELUP
volume: 1
pitch: 1
game-effects:
end:
effects:
==: Firework
flicker: false
trail: false
colors:

&id002
==: Color
RED: 255
BLUE: 255
GREEN: 255
fade-colors:
*id002
type: BALL
power: 1
type: Firework
start: {}
kill: {}
teamkill: {}
lobbyjoin: {}
lobbyleave: {}
respawn: {}
beddestroy: {}
warppowdertick: {}
lobby-scoreboard:
enabled: false
title: §eBEDWARS
content:
' '

'§fMap: §2%arena%'

'§fPlayers: §2%players%§f/§2%maxplayers%'

' '

§fWaiting ...

' '
statistics:
enabled: true
type: yaml
show-on-game-end: false
bed-destroyed-kills: false
scores:
kill: 10
die: 0
win: 50
bed-destroy: 25
lose: 0
record: 100
final-kill: 0
database:
host: localhost
port: 3306
db: databse
user: root
password: secret
table-prefix: bw_
useSSL: false
bossbar:
use-xp-bar: false
lobby:
enable: true
color: YELLOW
style: SEGMENTED_20
game:
enable: true
color: GREEN
style: SEGMENTED_20
holograms:
enabled: true
headline: Your §eBEDWARS§f stats
leaderboard:
headline: '&6Bedwars Leaderboard'
format: '&l%order%. &7%name% - &a%score%'
size: 10
chat:
override: true
format: '<%teamcolor%%name%§r> '
separate-chat:
lobby: false
game: false
send-death-messages-just-in-game: true
send-custom-death-messages: true
default-team-chat-while-running: true
all-chat-prefix: '@A'
team-chat-prefix: '@t'
all-chat: '[ALL] '
team-chat: '[TEAM] '
death-chat: '[DEATH] '
disable-all-chat-for-spectators: false
rewards:
enabled: false
player-win:

/example {player} 200
player-end-game:

/example {player} {score}
player-destroy-bed:

/example {player} {score}
player-kill:

/example {player} 10
player-final-kill:

/example {player} 10
lore:
generate-automatically: true
text:

'§7Cost: §f%price% %resource%'

''
sign:
lines:

§c§l[BedWars]

'%arena%'

'%status%'

'%players%'
block-behind:
enabled: false
waiting: ORANGE_STAINED_GLASS
rebuilding: BROWN_STAINED_GLASS
in-game: GREEN_STAINED_GLASS
game-disabled: RED_STAINED_GLASS
hotbar:
selector: 0
color: 1
start: 2
leave: 8
breakable:
enabled: false
asblacklist: false
blocks: []
leaveshortcuts:
enabled: false
list:

leave
mainlobby:
enabled: true
location: -2.1896992292162984;70.0;-75.64880255471022;275.70853;0.8477453
world: world
version: 2
turnOnExperimentalGroovyShop: false
preventSpectatorFlyingAway: false
removePurchaseMessages: false
disableCakeEating: true
disableDragonEggTeleport: true
disable-flight: true
shop:
rows: 4
render-actual-rows: 6
render-offset: 9
render-header-start: 0
render-footer-start: 45
items-on-row: 9
show-page-numbers: true
inventory-type: CHEST
citizens-enabled: true
gived-player-respawn-items: []
allow-fake-death: false
preventArenaFromGriefing: false
update-checker:
zero:
console: true
admins: true
one:
console: true
admins: true
target-block:
allow-destroying-with-explosions: false
respawn-anchor:
fill-on-start: true
enable-decrease: true
sound:
charge: BLOCK_RESPAWN_ANCHOR_CHARGE
used: BLOCK_GLASS_BREAK
deplete: BLOCK_RESPAWN_ANCHOR_DEPLETE
cake:
destroy-by-eating: true
event-hacks:
damage: false
destroy: false
place: false
tab:
enable: false
header:
enabled: true
contents:

'&aMy awesome BedWars server'
'&bMap: %map%'
'&cPlayers: %respawnable%/%max%'
footer:
enabled: true
contents:
'&eexample.com'
'&fWow!!'
§a%spectators% are watching this match
hide-spectators: true
hide-foreign-players: false
default-permissions:
join: true
leave: true
stats: true
list: true
rejoin: true
autojoin: true
leaderboard: true
enable-cheat-command-for-admins: true
shop.yml:
data:
locate: '$blocks'
stack: WHITE_WOOL;1;§aBlocks;§eClick to view!
skip: 1

write: false
stack: 'STONE'
id: blocks
items:

locate: 'main'
stack: WHITE_WOOL;1;§aBlocks;§eClick to view!
skip: 1
locate: '$swords'
stack: GOLDEN_SWORD;1;§aMelee;§eClick to view!
locate: '$armor'
stack: CHAINMAIL_BOOTS;1;§aArmor;§eClick to view!
locate: '$tools'
stack: STONE_PICKAXE;1;§aTools;§eClick to view!
locate: '$bows'
stack: BOW;1;§aRanged;§eClick to view!
locate: '$potions'
stack: BREWING_STAND;1;§aPotions;§eClick to view!
locate: '$utility'
stack: TNT;1;§aUtility;§eClick to view!
stack: GREEN_STAINED_GLASS_PANE;1
row: 2
column: 1
stack: WOOL;16;Wool;§7Great for bridging across;§7islands.
price: 4 of iron
properties: applycolorbyteam
row: 3
column: 1
CLAY;16 for 12 of iron
GLASS;4 for 12 of iron
END_STONE;12 for 24 of iron
LADDER;16 for 4 of iron
OAK_PLANKS;16 for 4 of gold
OBSIDIAN;4 for 4 of emerald
write: false
stack: 'STONE'
id: swords
items:

locate: '$blocks'
stack: WHITE_WOOL;1;§aBlocks;§eClick to view!
skip: 1
locate: 'main'
stack: GOLDEN_SWORD;1;§aMelee;§eClick to view!
locate: '$armor'
stack: CHAINMAIL_BOOTS;1;§aArmor;§eClick to view!
locate: '$tools'
stack: STONE_PICKAXE;1;§aTools;§eClick to view!
locate: '$bows'
stack: BOW;1;§aRanged;§eClick to view!
locate: '$potions'
stack: BREWING_STAND;1;§aPotions;§eClick to view!
locate: '$utility'
stack: TNT;1;§aUtility;§eClick to view!
stack: GREEN_STAINED_GLASS_PANE;1
row: 2
column: 2
stack: STONE_SWORD;1
price: 10 of iron
row: 3
column: 1
IRON_SWORD;1 for 7 of gold
DIAMOND_SWORD;1 for 4 of emerald
price: 5 of gold
stack:
type: STICK
enchants:
KNOCKBACK: 1
write: false
stack: 'STONE'
id: armor
items:

locate: '$blocks'
stack: WHITE_WOOL;1;§aBlocks;§eClick to view!
skip: 1
locate: '$swords'
stack: GOLDEN_SWORD;1;§aMelee;§eClick to view!
locate: 'main'
stack: CHAINMAIL_BOOTS;1;§aArmor;§eClick to view!
locate: '$tools'
stack: STONE_PICKAXE;1;§aTools;§eClick to view!
locate: '$bows'
stack: BOW;1;§aRanged;§eClick to view!
locate: '$potions'
stack: BREWING_STAND;1;§aPotions;§eClick to view!
locate: '$utility'
stack: TNT;1;§aUtility;§eClick to view!
stack: GREEN_STAINED_GLASS_PANE;1
row: 2
column: 3
stack: CHAINMAIL_BOOTS;1
price: 40 of iron
row: 3
column: 1
IRON_BOOTS;1 for 12 of gold
DIAMOND_BOOTS;1 for 4 of emerald
write: false
stack: 'STONE'
id: tools
items:

locate: '$blocks'
stack: WHITE_WOOL;1;§aBlocks;§eClick to view!
skip: 1
locate: '$swords'
stack: GOLDEN_SWORD;1;§aMelee;§eClick to view!
locate: '$armor'
stack: CHAINMAIL_BOOTS;1;§aArmor;§eClick to view!
locate: 'main'
stack: STONE_PICKAXE;1;§aTools;§eClick to view!
locate: '$bows'
stack: BOW;1;§aRanged;§eClick to view!
locate: '$potions'
stack: BREWING_STAND;1;§aPotions;§eClick to view!
locate: '$utility'
stack: TNT;1;§aUtility;§eClick to view!
stack: GREEN_STAINED_GLASS_PANE;1
row: 2
column: 4
stack: SHEARS;1
price: 20 of iron
row: 3
column: 1
WOODEN_PICKAXE;1 for 10 of iron
WOODEN_AXE;1 for 10 of iron
IRON_PICKAXE;1 for 20 of iron
IRON_AXE;1 for 20 of iron
DIAMOND_PICKAXE;1 for 12 of gold
DIAMOND_AXE;1 for 12 of gold
write: false
stack: 'STONE'
id: bows
items:

locate: '$blocks'
stack: WHITE_WOOL;1;§aBlocks;§eClick to view!
skip: 1
locate: '$swords'
stack: GOLDEN_SWORD;1;§aMelee;§eClick to view!
locate: '$armor'
stack: CHAINMAIL_BOOTS;1;§aArmor;§eClick to view!
locate: '$tools'
stack: STONE_PICKAXE;1;§aTools;§eClick to view!
locate: 'main'
stack: BOW;1;§aRanged;§eClick to view!
locate: '$potions'
stack: BREWING_STAND;1;§aPotions;§eClick to view!
locate: '$utility'
stack: TNT;1;§aUtility;§eClick to view!
stack: GREEN_STAINED_GLASS_PANE;1
row: 2
column: 5
stack: BOW;1
price: 12 of gold
row: 3
column: 1
price: 24 of gold
stack:
type: BOW
enchants:
ARROW_DAMAGE: 1
price: 6 of emerald
stack:
type: BOW
enchants:
ARROW_KNOCKBACK: 1
ARROW_DAMAGE: 1
write: false
stack: 'STONE'
id: potions
items:

locate: '$blocks'
stack: WHITE_WOOL;1;§aBlocks;§eClick to view!
skip: 1

locate: '$swords'
stack: GOLDEN_SWORD;1;§aMelee;§eClick to view!

locate: '$armor'
stack: CHAINMAIL_BOOTS;1;§aArmor;§eClick to view!

locate: '$tools'
stack: STONE_PICKAXE;1;§aTools;§eClick to view!

locate: '$bows'
stack: BOW;1;§aRanged;§eClick to view!

locate: 'main'
stack: BREWING_STAND;1;§aPotions;§eClick to view!

locate: '$utility'
stack: TNT;1;§aUtility;§eClick to view!

stack: GREEN_STAINED_GLASS_PANE;1
row: 2
column: 6

row: 3
column: 1
stack:
type: POTION
display-name: "§rPotion of Leaping I"
meta:
==: ItemMeta
meta-type: POTION
potion-type: leaping
price: 1 of emerald

row: 3
column: 2
price: 2 of emerald
stack:
type: POTION
display-name: "§rPotion of Invisibility"
effects:
- effect: invisibility
duration: 600
amplifier: 1

row: 3
column: 3
price: 1 of emerald
stack:
type: POTION
display-name: "§rPotion of Leaping"
effects:
- effect: jump_boost
duration: 600
amplifier: 5

write: false
stack: 'STONE'
id: utility
items:

locate: '$blocks'
stack: WHITE_WOOL;1;§aBlocks;§eClick to view!
skip: 1
locate: '$swords'
stack: GOLDEN_SWORD;1;§aMelee;§eClick to view!
locate: '$armor'
stack: CHAINMAIL_BOOTS;1;§aArmor;§eClick to view!
locate: '$tools'
stack: STONE_PICKAXE;1;§aTools;§eClick to view!
locate: '$bows'
stack: BOW;1;§aRanged;§eClick to view!
locate: '$potions'
stack: BREWING_STAND;1;§aPotions;§eClick to view!
locate: 'main'
stack: TNT;1;§aUtility;§eClick to view!
stack: GREEN_STAINED_GLASS_PANE;1
row: 2
column: 7
price: 3 of gold
row: 3
column: 1
stack:
type: GOLDEN_APPLE
price: 4 of gold
properties: "autoigniteabletnt"
stack:
type: TNT
ENDER_PEARL;1 for 4 of emerald
WATER_BUCKET;1 for 3 of emerald
price: 3 of iron
properties:
name: "Trap"
data:
sound: ENTITY_SHEEP_AMBIENT
effect:
==: org.bukkit.potion.PotionEffect
effect: 15
amplifier: 2
duration: 100
ambient: true
has-particles: true
has-icon: true
effect:
==: org.bukkit.potion.PotionEffect
effect: 18
amplifier: 2
duration: 100
ambient: true
has-particles: true
has-icon: true
effect:
==: org.bukkit.potion.PotionEffect
effect: 2
amplifier: 2
duration: 100
ambient: true
has-particles: true
has-icon: true
stack:
type: STRING
display-name: "Trap"
lore:
"§7Get informed if an enemy steps on your trap"
"§7and your enemy won't be able to move properly."
""
price: 120 of iron
properties:
name: "Golem"
speed: 0.25
follow: 16.0
stack:
type: GHAST_SPAWN_EGG
display-name: "Golem"
lore:
"§7An iron golem that will protect"
"§7your team from the enemies."
""
price: 40 of iron
properties: "ThrowableFireball"
stack:
type: FIRE_CHARGE
display-name: "Fireball"
lore:
- "§7Is it a bird? Is it a plane?"
- "§7By the time you know"
- "§7you are dead!"
- ""
price: 1 of emerald
row: 4
column: 1
properties: "BridgeEgg"
stack:
type: EGG
display-name: "§cBridgeEgg"
lore:
- "§7This egg creates a trail of bridge after it's thrown"
- ""
price: 24 of iron
row: 4
column: 2
properties: "PopupTower"
stack:
type: CHEST
display-name: "§aCompact Pop-up Tower"
lore:
- "§7Place a pop-up defence!"
- ""
locate: '$swords'
stack: GOLDEN_SWORD;1;§aMelee;§eClick to view!

locate: '$armor'
stack: CHAINMAIL_BOOTS;1;§aArmor;§eClick to view!

locate: '$tools'
stack: STONE_PICKAXE;1;§aTools;§eClick to view!

locate: '$bows'
stack: BOW;1;§aRanged;§eClick to view!

locate: '$potions'
stack: BREWING_STAND;1;§aPotions;§eClick to view!

locate: '$utility'
stack: TNT;1;§aUtility;§eClick to view!

stack: WOOL;16
properties: applycolorbyteam
price: 4 of iron
row: 3
column: 1

stack: STONE_SWORD;1
price: 10 of iron
row: 3
column: 2

stack: CHAINMAIL_BOOTS;1
price: 40 of iron
row: 3
column: 3

stack: RED_STAINED_GLASS_PANE;1
price: 4 of iron
row: 3
column: 4

stack: BOW;1
price: 12 of gold
row: 3
column: 5

row: 3
column: 6
price: 1 of emerald
stack:
type: POTION
display-name: "§rPotion of Healing I"
meta:
==: ItemMeta
meta-type: POTION
potion-type: healing

stack: TNT;1
price: 4 of gold
properties: "autoigniteabletnt"
row: 3
column: 7

stack: OAK_PLANKS;16
price: 4 of gold
row: 4
column: 1

stack: IRON_SWORD;1
price: 7 of gold
row: 4
column: 2

stack: IRON_BOOTS;1
price: 12 of gold
row: 4
column: 3

stack: SHEARS;1
price: 20 of iron
row: 4
column: 4

stack: ARROW;8
price: 2 of gold
row: 4
column: 5

row: 4
column: 6
price: 2 of emerald
stack:
type: POTION
display-name: "§rPotion of Invisibility"
effects:
- effect: invisibility
duration: 600
amplifier: 1

stack: WATER_BUCKET;1
row: 4
column: 7
price: 3 of emerald

stack: "RED_STAINED_GLASS_PANE;1"
row: 5
column: 1

stack: "RED_STAINED_GLASS_PANE;1"
row: 5
column: 2

stack: "RED_STAINED_GLASS_PANE;1"
row: 5
column: 3

stack: "RED_STAINED_GLASS_PANE;1"
row: 5
column: 4

stack: RED_STAINED_GLASS_PANE;1
row: 5
column: 5

stack: RED_STAINED_GLASS_PANE;1
row: 5
column: 6

stack: RED_STAINED_GLASS_PANE;1
row: 5
column: 7

stack: GREEN_STAINED_GLASS_PANE;1
row: 2
column: 0
#### If there are problem with only one game, paste here config of this game
problem with only some players specially non-ops
it seems like they are out of world border

**Comment by MyBedwars** [comment]
sorry for pating yml here instead of pasting it in pastebin

**Comment by bijuu123** [comment]
first set /worldborder center ~~ [at center of map]
then do /worldborder set 200 
then reset the pos1 and pos2

**Comment by MyBedwars** [comment]
first i set the worldborder centre ~ ~ [at the centre of map]
then i did /worldborder set 1000
then even tried to set pos1 and pos2 but did not work :(

**Comment by MyBedwars** [comment]
Some players see red at side of screen and not able to place,break block and just able to pvp in duos map (Airshow,Rooftop) #360 comment on this one
