### ISSUE TITLE
Bug but its not. 

### ISSUE THREAD

**Issue by Aadi-mone** [ScreamingSandals/BedWars#356]
just not a bug but its a bug

I am trying to make some sounds to silence here:

sounds:
  on_trap_triggered: ENTITY_ENDERMAN_TELEPORT
  bed_destroyed:
    sound: ENTITY_WITHER_DEATH
    volume: 1
    pitch: 1
  countdown:
    sound: NONE

I tried `[],  '', [SPACE]` and more symbols but it didn't work, please help me.
whenever I do other things it rolls back to default changes.
I want complete silence in some places like BedDestructions. 
if anyone helps, thanks in advance.

**Comment by Aadi-mone** [comment]
@zlataovce  :)

**Comment by zlataovce** [comment]
have you tried setting volume to 0?

**Comment by Aadi-mone** [comment]
yes
and one more doubt I have SBA installed after this I got the trap trigger sounds so will SBA do anything? 
and thanks for the help.

**Comment by bijuu123** [comment]
ok
