### ISSUE TITLE
Some players see red at side of screen and not able to place,break block and just able to pvp in duos map (Airshow,Rooftop)

### ISSUE THREAD

**Issue by MyBedwars** [ScreamingSandals/BedWars#360]
#### Describe the bug
Some players see red at side of screen and not able to place,break block and just able to pvp in duos map (Airshow,Rooftop)

#### Server and plugin version
Spigot version: 1.16.5
BedWars version: 0.2.18 (To use SBA)

#### Installed plugins on server (can be obtained by `/pl`)
BedWars-0.2.18-14.jar
DeluxeHub-3.3.10.jar
IridiumSkyblock-3.0.6.jar
Multiverse-Core-4.3.0.jar
Multiverse-Inventories-4.2.2.jar
oneblock.jar
OpenLogin.jar
PlaceholderAPI-2.10.9.jar
SBA-1.5.5.jar
Vault.jar
ViaRewind-2.0.1.jar
ViaBackwards-4.0.1.jar
ViaVersion-4.0.1.jar
worldedit-bukkit-7.2.6.jar
worldguard-bukkit-7.0.5-dist.jar
znpc-servers.jar
#### Console log
says nothing
#### Configuration (of config.yml and shop.yml)
https://pastebin.pl/view/1f6f6aa9
https://pastebin.pl/view/cfbc6420
#### If there are problem with only one game, paste here config of this game
with all games and specially for non ops

**Comment by zlataovce** [comment]
some plugin is overriding world borders or your positions are misconfigured

**Comment by MyBedwars** [comment]
can u plz give me the co-ordinates where i can set pos1 and pos2 in roofto and airshow map

**Comment by MyBedwars** [comment]
plz help bro

**Comment by MyBedwars** [comment]
and the list of plugins is there in front of u and i have disabled the plugins like deluxehub,irridium skyblock etc from access these worlds

**Comment by KnowItAllNetYT** [comment]
> and the list of plugins is there in front of u and i have disabled the plugins like deluxehub,irridium skyblock etc from accessing these worlds
> or to block any player to do anyhting in this worlds

you just will have to back away from the map a little bit and then set pos1, then set pos2, its not necessary to stay closer to the map while setting positions

**Comment by MyBedwars** [comment]
the problem is not solved y did u close the bug

**Comment by zlataovce** [comment]
can't reproduce.
