### ISSUE TITLE
Spectator not workin. 

### ISSUE THREAD

**Issue by Aadi-mone** [ScreamingSandals/BedWars#361]
after team elimination the dead players are not in the spectator, thus the left players can see them
no need for more information they can see that's all

version bedwars 0.2.18

**Comment by JustAHuman-xD** [comment]
Go to the discord server and open a support ticket, that message is hard to understand

**Comment by Aadi-mone** [comment]
well, for some legal reason in my country I can't use discord.
@zlataovce :)

**Comment by zlataovce** [comment]
follow the issue template.
