### ISSUE TITLE
Shop Proble.

### ISSUE THREAD

**Issue by NiceBg** [ScreamingSandals/BedWars#364]
Hi, i am facing just one problem in your plugin and problem is i cant add shops. All the commands works well but when i was almost going to finish my game after adding shops in map then i type the command to add shop and it says "SHOP HAVE BEEN PLACED" but i cant see it and if i right/left click on that place then also nothing happens. Plz help bro:(((

**Comment by zlataovce** [comment]
you can't see shops in the editing phase, only in the game
