### ISSUE TITLE
Iron and gold wont work

### ISSUE THREAD

**Issue by MoosePodcasts** [ScreamingSandals/BedWars#365]
#### Describe the bug 

everything works accept when i go in the shop and try to buy anything for iron and gold. i still cant buy it no matter what i try, emerald, diamond, and everything else work accept for that.

#### Server and plugin version
Spigot version: 1.17.1
BedWars version: SBA 1.5.0

**Comment by JustAHuman-xD** [comment]
Sba doesn’t support 1.17.1 it’s not a bug, for issues like this go to the discord server. Also make sure you are using bedwars 0.2.18 not 0.2.19. If that’s all please close this

**Comment by zlataovce** [comment]
not following the issue template, sba doesn't support 1.17.1
