### ISSUE TITLE
SBA cannot be activated

### ISSUE THREAD

**Issue by Codecrafter14** [ScreamingSandals/BedWars#368]
#### Describe the bug
SBA Hypixelfy Addon plugin error while startung the server.

#### Server and plugin version
Java version: 16
Spigot version: 1.17.1
BedWars version: 0.2.19-23
SBA Hypixelfy Addon version: 1.5.5

#### Installed plugins on server (can be obtained by `/pl`)
Bedwars, SBA

#### Console log

[17:15:41] [Server thread/ERROR]: ======PLUGIN ERROR===========
--
348 | [17:15:41] [Server thread/ERROR]: Plugin: SBA is being disabled for the following error:
349 | [17:15:41] [Server thread/ERROR]: You need ScreamingBedWars v0.2.18 to run SBA v1.5.0
350 | [17:15:41] [Server thread/ERROR]: Get the latest version from here: https://www.spigotmc.org/resources/screaming-bedwars-1-9-1-16.63714/
351 | [17:15:41] [Server thread/ERROR]: =============================
352 | [17:15:41] [Server thread/INFO]: [SBA] Disabling SBA v1.5.5
353 | [17:15:41] [Server thread/ERROR]: Failed to initialize the command manager
354 | [17:15:41] [Server thread/INFO]: [SBA] Disabling SBA v1.5.5
355 | [17:15:41] [Server thread/ERROR]: Error occurred while enabling SBA v1.5.5 (Is it up to date?)
356 | org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register io.github.pronze.sba.service.HealthIndicatorService@798b7d0 while not enabled
357 | at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:612) ~[minecraft_server.jar:3246-Spigot-6c1c1b2-dc764e7]
358 | at io.github.pronze.sba.SBA.registerListener(SBA.java:187) ~[?:?]
359 | at io.github.pronze.sba.service.HealthIndicatorService.postEnabled(HealthIndicatorService.java:52) ~[?:?]
360 | at io.github.pronze.sba.SBA_BukkitImpl$5.run(SBA_BukkitImpl.java:141) ~[?:?]
361 | at io.github.pronze.lib.screaminglib.utils.ControllableImpl.postEnable(ControllableImpl.java:57) ~[?:?]
362 | at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
363 | at io.github.pronze.lib.screaminglib.utils.ControllableImpl.postEnable(ControllableImpl.java:55) ~[?:?]
364 | at io.github.pronze.sba.SBA_BukkitImpl.onEnable(SBA_BukkitImpl.java:431) ~[?:?]
365 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[minecraft_server.jar:3246-Spigot-6c1c1b2-dc764e7]
366 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[minecraft_server.jar:3246-Spigot-6c1c1b2-dc764e7]
367 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[minecraft_server.jar:3246-Spigot-6c1c1b2-dc764e7]
368 | at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:514) ~[minecraft_server.jar:3246-Spigot-6c1c1b2-dc764e7]
369 | at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:428) ~[minecraft_server.jar:3246-Spigot-6c1c1b2-dc764e7]
370 | at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:619) ~[minecraft_server.jar:3246-Spigot-6c1c1b2-dc764e7]
371 | at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[minecraft_server.jar:3246-Spigot-6c1c1b2-dc764e7]
372 | at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) ~[minecraft_server.jar:3246-Spigot-6c1c1b2-dc764e7]
373 | at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[minecraft_server.jar:3246-Spigot-6c1c1b2-dc764e7]
374 | at java.lang.Thread.run(Thread.java:831) [?:?]

#### Configuration (of config.yml and shop.yml)
see attached files
[config.yml of Bedwars.txt](https://github.com/ScreamingSandals/BedWars/files/7271721/config.yml.of.Bedwars.txt)
[sbaconfig.yml.txt](https://github.com/ScreamingSandals/BedWars/files/7271722/sbaconfig.yml.txt)
[shop.yml of Bedwars.txt](https://github.com/ScreamingSandals/BedWars/files/7271723/shop.yml.of.Bedwars.txt)
[shop.yml of SBA.txt](https://github.com/ScreamingSandals/BedWars/files/7271724/shop.yml.of.SBA.txt)

**Comment by zlataovce** [comment]
sba does not support 1.17.1 at all and this is not SBA's repository, report further issues on https://github.com/pronze/SBA
