### ISSUE TITLE
Issue with Prefixes 

### ISSUE THREAD

**Issue by DragonCraftMC** [ScreamingSandals/BedWars#370]
#### Describe the bug
Okay so I am running into this problem where BedWars will override my permission plugins prefixes. From my understanding of looking at the config.yml. In the chat section on the config it has "override" which I assume means to override all prefixed which I have turned off. Then its says "separate-chat" from the "lobby" and the "game". And I am assuming that "Lobby" means the waiting lobby for the game and not the "mainlobby". All of these have been turned to false and the prefixes wont go away. Also no where in the config do I see something for changing the prefix in the "mainlobby". 

#### Server and plugin version
Spigot version: 1.15.2
BedWars version: 2.20-36

#### Installed plugins on server (can be obtained by `/pl`)
BCommons*, BedWars, Citizens, CombatPlus, DeluxeMenus, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), GadgetsMenu, HolographicDisplays, HolographicExtension, HPWP, LuckPerms, Multiverse-Core, NESS, PlaceholderAPI, ProtocolLib, SBAHypixelify, ServerListPlus*, Sudo*, TimedRewards*, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGenerator, WorldEdit, WorldGuard

#### Console log
There is no console errors

#### Configuration (of config.yml and shop.yml)
This is my config.yml https://pastebin.com/uvAKEL4V
This is my shop.yml https://pastebin.com/ktXk3P8j

**Comment by DragonCraftMC** [comment]
I also forgot to say this is the prefix the it is giving me in the lobby:
[0✫] {name}:

**Comment by JustAHuman-xD** [comment]
Go to the discord server please
it makes it much easier to provide support.

Go there and open a ticket: https://discord.gg/72zm768N

**Comment by zlataovce** [comment]
sba overrides chat, try without sba
