### ISSUE TITLE
TnT and fireball explosions not destroying blocks on some arenas

### ISSUE THREAD

**Issue by Invictable** [ScreamingSandals/BedWars#371]
Using Bedwars v0.2.18 and SBA v1.5.5 on 1.16.5

On some arenas, tnt and fireballs destroy blocks as expected, but on others they do not.
I tried removing every plugin except multiverse and the bedwars plugins, it did not fix. Outside of the games pos1 and pos2, the fireballs destroy blocks as they should. 

I thought it might be a world issue, so i changed the map on one of the arenas that didnt work to one where it did and despite being the same world, the issue persisted for the changed arena. 

Here's a video of that if it helps: 
https://youtu.be/sKUPVLkaJ8Y

Here's an Arena file that works, the test one that doesnt, and the actual map one that doesnt. converted to .txt because i cant upload .ymls.
[Oasis102-300c-4f2f-a7b9-4d7bff95e2de.txt](https://github.com/ScreamingSandals/BedWars/files/7342117/Oasis102-300c-4f2f-a7b9-4d7bff95e2de.txt)
.
[test1102-300c-4f2f-a7b9-4d7bff95e2de.txt](https://github.com/ScreamingSandals/BedWars/files/7342118/test1102-300c-4f2f-a7b9-4d7bff95e2de.txt)
[monaster-2afb-4d62-9c36-57c2dcb45904.txt](https://github.com/ScreamingSandals/BedWars/files/7342119/monaster-2afb-4d62-9c36-57c2dcb45904.txt)

**Comment by zlataovce** [comment]
could you please reproduce the issue without SBA?

**Comment by Misat11** [comment]
Users are now warned that the creation of overlapping arenas is not supported when they create such arenas using pos1/pos2 commands. I think this issue can be closed now.
