### ISSUE TITLE
Error when load map

### ISSUE THREAD

**Issue by CJYKK** [ScreamingSandals/BedWars#374]
#### Describe the bug
Can't load bedwars config on start up.

#### Server and plugin version
Spigot version: git-Paper-1618 (MC: 1.12.2)
BedWars version: 0.2.18 FREE

#### Installed plugins on server (can be obtained by `/pl`)
AntiCheatReloaded, AuthMe, AuthMeLoginSign, BedWars, Citizens, CleanMOTD, EasyWhitelist, Maintenance, OldCombatMechanics, PlaceholderAPI, ProtocolLib, SBA, SkinsRestorer, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, WorldEdit

#### Console log
[13:00:02 WARN]: [BedWars] Something went wrong while loading arena file 228bc7ea-7354-44ca-acba-4fcdc0d2e387.yml. Please report this to our Discord or GitHub!
[13:00:02 WARN]: java.lang.NumberFormatException: multiple points
[13:00:02 WARN]:        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1914)
[13:00:02 WARN]:        at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
[13:00:02 WARN]:        at java.base/java.lang.Float.parseFloat(Float.java:468)
[13:00:02 WARN]:        at org.screamingsandals.bedwars.utils.MiscUtils.readLocationFromString(MiscUtils.java:185)
[13:00:02 WARN]:        at org.screamingsandals.bedwars.game.Game.loadGame(Game.java:949)
[13:00:02 WARN]:        at org.screamingsandals.bedwars.game.Game.loadGame(Game.java:859)
[13:00:02 WARN]:        at org.screamingsandals.bedwars.Main.onEnable(Main.java:520)
[13:00:02 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:00:02 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[13:00:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:00:02 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[13:00:02 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[13:00:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[13:00:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[13:00:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[13:00:02 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[13:00:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)

#### Configuration (of config.yml and shop.yml)
config.yml:

locale: zh-CN
debug: false
allow-crafting: false
keep-inventory-on-death: false
in-lobby-colored-leather-by-team: true
jointeam-entity-show-name: true
friendlyfire: false
player-drops: false
join-randomly-after-lobby-timeout: true
prevent-killing-villagers: true
compass-enabled: true
join-randomly-on-lobby-join: false
add-wool-to-inventory-on-join: true
prevent-spawning-mobs: true
spawner-holograms: false
spawner-disable-merge: true
prevent-lobby-spawn-mobs-in-radius: 16
spawner-holo-height: 0.25
spawner-holograms-countdown: true
damage-when-player-is-not-in-arena: true
remove-unused-target-blocks: true
allow-block-falling: true
game-start-items: true
player-respawn-items: false
gived-game-start-items:
- wooden_sword
- leather_helmet
- leather_boots
- leather_leggings
- leather_chestplate
disable-hunger: true
automatic-coloring-in-shop: true
sell-max-64-per-click-in-shop: true
destroy-placed-blocks-by-explosion-except:
- ''
destroy-placed-blocks-by-explosion: true
holo-above-bed: true
allow-spectator-join: false
disable-server-message:
  player-join: false
  player-leave: false
respawn-cooldown:
  enabled: true
  time: 5
stop-team-spawners-on-die: false
allowed-commands: []
change-allowed-commands-to-blacklist: false
bungee:
  enabled: false
  serverRestart: true
  serverStop: false
  server: hub
  auto-game-connect: false
  kick-when-proxy-too-slow: true
  motd:
    enabled: false
    waiting: '%name%: Waiting for players [%current%/%max%]'
    waiting_full: '%name%: Game is full [%current%/%max%]'
    running: '%name%: Game is running [%current%/%max%]'
    rebuilding: '%name%: Rebuilding...'
    disabled: '%name%: Game is disabled'
farmBlocks:
  enable: false
  blocks: []
scoreboard:
  enable: false
  title: §a%game%§r - %time%
  bedLost: §c✘
  bedExists: §a✔
  teamTitle: '%bed%%color%%team%'
  anchorEmpty: §e✘
title:
  enabled: false
  fadeIn: 0
  stay: 0
  fadeOut: 0
items:
  jointeam: COMPASS
  leavegame: BED
  startgame: DIAMOND
  shopback: BARRIER
  shopcosmetic: STAINED_GLASS_PANE
  pageback: ARROW
  pageforward: ARROW
  team-select: WHITE_WOOL
vault:
  enable: false
  reward:
    kill: 5
    win: 20
    final-kill: 5
    bed-destroy: 0
resources:
  emerald:
    material: EMERALD
    color: GREEN
    name: 绿宝石
    interval: 60
    translate: resource_emerald
    spread: 0.1
  diamond:
    material: DIAMOND
    color: BLUE
    name: 钻石
    interval: 30
    translate: resource_diamond
    spread: 0.1
  iron:
    material: IRON_INGOT
    color: WHITE
    name: 铁锭
    interval: 2.5
    translate: resource_iron
    spread: 1.0
  gold:
    material: GOLD_INGOT
    color: GOLD
    name: 金锭
    interval: 8
    translate: resource_gold
    spread: 1.0
respawn:
  protection-enabled: true
  protection-time: 5
specials:
  action-bar-messages: true
  rescue-platform:
    is-breakable: false
    delay: 0
    break-time: 10
    distance: 1
    material: GLASS
  protection-wall:
    is-breakable: false
    delay: 20
    break-time: 0
    width: 5
    height: 3
    distance: 2
    material: CUT_SANDSTONE
  tnt-sheep:
    speed: 2.0
    follow-range: 10.0
    max-target-distance: 32
    explosion-time: 8
  arrow-blocker:
    protection-time: 10
    delay: 5
  warp-powder:
    teleport-time: 6
    delay: 0
  magnet-shoes:
    probability: 75
  golem:
    speed: 0.25
    follow-range: 10
    health: 20
    name-format: '%teamcolor%%team% Golem'
    show-name: true
    delay: 0
    collidable: false
  teamchest:
    turn-all-enderchests-to-teamchests: true
  throwable-fireball:
    explosion: 3.0
    damage: 2.0
  auto-igniteable-tnt:
    explosion-time: 3
    damage-placer: true
tnt: {}
sounds:
  on_trap_triggered: ENTITY_ENDERMAN_TELEPORT
  bed_destroyed:
    sound: ENTITY_ENDER_DRAGON_GROWL
    volume: 1
    pitch: 1
  my_bed_destroyed:
    sound: ENTITY_ENDER_DRAGON_GROWL
    volume: 1
    pitch: 1
  countdown:
    sound: UI_BUTTON_CLICK
    volume: 1
    pitch: 1
  game_start:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1
  team_kill:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1
  player_kill:
    sound: ENTITY_PLAYER_BIG_FALL
    volume: 1
    pitch: 1
  item_buy:
    sound: ENTITY_ITEM_PICKUP
    volume: 1
    pitch: 1
  upgrade_buy:
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 1
    pitch: 1
  respawn_cooldown_wait:
    sound: UI_BUTTON_CLICK
    volume: 1
    pitch: 1
  respawn_cooldown_done:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1
game-effects:
  end:
    effects:
    - ==: Firework
      flicker: false
      trail: false
      colors:
      - &id001
        ==: Color
        RED: 255
        BLUE: 255
        GREEN: 255
      fade-colors:
      - *id001
      type: BALL
    power: 1
    type: Firework
  start: {}
  kill: {}
  teamkill: {}
  lobbyjoin: {}
  lobbyleave: {}
  respawn: {}
  beddestroy: {}
  warppowdertick: {}
lobby-scoreboard:
  enabled: false
  title: §eBEDWARS
  content:
  - ' '
  - '§f地图：§2%arena%'
  - '§f玩家数：§2%players%§f/§2%maxplayers%'
  - ' '
  - §f等待中……
  - ' '
statistics:
  enabled: true
  type: yaml
  show-on-game-end: false
  bed-destroyed-kills: false
  scores:
    kill: 10
    die: 0
    win: 50
    bed-destroy: 25
    lose: 0
    record: 100
    final-kill: 0
database:
  host: localhost
  port: 3306
  db: databse
  user: root
  password: secret
  table-prefix: bw_
  useSSL: false
bossbar:
  use-xp-bar: false
  lobby:
    enable: true
    color: YELLOW
    style: SEGMENTED_20
  game:
    enable: true
    color: GREEN
    style: SEGMENTED_20
holograms:
  enabled: true
  headline: 你的§e起床战争§f统计数据
  leaderboard:
    headline: '&6起床战争排行榜'
    format: '&l%order%. &7%name% - &a%score%'
    size: 10
chat:
  override: true
  format: '<%teamcolor%%name%§r> '
  separate-chat:
    lobby: false
    game: false
  send-death-messages-just-in-game: true
  send-custom-death-messages: true
  default-team-chat-while-running: true
  all-chat-prefix: '@a'
  team-chat-prefix: '@t'
  all-chat: '[全部] '
  team-chat: '[团队] '
  death-chat: '[死亡] '
  disable-all-chat-for-spectators: false
rewards:
  enabled: false
  player-win:
  - /example {player} 200
  player-end-game:
  - /example {player} {score}
  player-destroy-bed:
  - /example {player} {score}
  player-kill:
  - /example {player} 10
  player-final-kill:
  - /example {player} 10
lore:
  generate-automatically: true
  text:
  - '§7费用：§f%price% %resource%'
  - ''
sign:
  lines:
  - §c§l[起床战争]
  - '%arena%'
  - '%status%'
  - '%players%'
  block-behind:
    enabled: false
    waiting: ORANGE_STAINED_GLASS
    rebuilding: BROWN_STAINED_GLASS
    in-game: GREEN_STAINED_GLASS
    game-disabled: RED_STAINED_GLASS
hotbar:
  selector: 0
  color: 1
  start: 2
  leave: 8
breakable:
  enabled: false
  asblacklist: false
  blocks: []
leaveshortcuts:
  enabled: false
  list:
  - leave
mainlobby:
  enabled: false
  location: 5008.480952200986;122.0;5032.798965675137;-180.29222;10.652989
  world: Lobby
version: 2
turnOnExperimentalGroovyShop: false
preventSpectatorFlyingAway: false
removePurchaseMessages: false
disableCakeEating: true
disableDragonEggTeleport: true
disable-flight: true
shop:
  rows: 4
  render-actual-rows: 6
  render-offset: 9
  render-header-start: 0
  render-footer-start: 45
  items-on-row: 9
  show-page-numbers: true
  inventory-type: CHEST
  citizens-enabled: true
gived-player-respawn-items: []
allow-fake-death: false
preventArenaFromGriefing: false
update-checker:
  zero:
    console: true
    admins: true
  one:
    console: true
    admins: true
target-block:
  allow-destroying-with-explosions: false
  respawn-anchor:
    fill-on-start: true
    enable-decrease: true
    sound:
      charge: BLOCK_RESPAWN_ANCHOR_CHARGE
      used: BLOCK_GLASS_BREAK
      deplete: BLOCK_RESPAWN_ANCHOR_DEPLETE
  cake:
    destroy-by-eating: true
event-hacks:
  damage: false
  destroy: false
  place: false
tab:
  enable: false
  header:
    enabled: true
    contents:
    - '&a起床战争'
    - '&b地图：%map%'
    - '&c玩家数：%respawnable%/%max%'
  footer:
    enabled: true
    contents:
    - §a%spectators%人正在旁观这场比赛
  hide-spectators: true
  hide-foreign-players: false
default-permissions:
  join: true
  leave: true
  stats: true
  list: true
  rejoin: true
  autojoin: true
  leaderboard: true

shop.yml

data:
#-   stack:
#      type: GOLDEN_APPLE
#      amount: 1
#      meta:
#        ==: ItemMeta
#        meta-type: UNSPECIFIC
#        display-name: "Example category"
#        lore:
#        - "This is my category!"
#        - "Please buy things inside!"
#    items:
#    - price: 50
#      price-type: "bronze"
#      stack:
#        type: DIAMOND_SWORD
#        amount: 1
#        meta:
#          ==: ItemMeta
#          meta-type: UNSPECIFIC
#          enchants:
#            DAMAGE_ALL: 2
#          repair-cost: 1
#          Damage: 99
# Value 'applycolorbyteam' is used for automatic-coloring-in-shop.
# See WarpPowder for more info.

- stack: "DIAMOND_CHESTPLATE;1;Armor;Protect yourself with armor! Click here."
  items:
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_HELMET
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_LEGGINGS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_BOOTS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 3 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 2
   - price: 7 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 3
   - price: 10 of gold
     stack:
      type: IRON_HELMET
      display-name: Helm
      enchants:
       PROTECTION_ENVIRONMENTAL: 2
       
- stack: "DIAMOND_SWORD;1;Swords;Click here to get sword for attacking your enemies"
  column: center
  items:
   - price: 8 of bronze
     stack:
      type: STICK
      enchants:
       KNOCKBACK: 1
   - price: 1 of iron
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 1
   - price: 3 of iron
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 2
   - price: 7 of iron
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 3
   - price: 3 of gold
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 2
       KNOCKBACK: 1
   - price: 15 of gold
     stack:
      type: GOLDEN_AXE
      display-name: "Axe of Infinity"
      enchants:
       DAMAGE_ALL: 1
       DURABILITY: 1
       KNOCKBACK: 1
       
- stack: "BOW;1;Bows;Prove yourself as a marksman with these wonderful bows"
  column: right
  items:
   - price: 3 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
   - price: 7 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_DAMAGE: 1
   - price: 13 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_DAMAGE: 2
   - price: 14 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_FIRE: 1
   - price: 15 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_FIRE: 1
       ARROW_KNOCKBACK: 1
   - ARROW for 1 of gold

- stack: "COOKED_PORKCHOP;1;Eat;Are you hungry? Get something to eat."
  row: 3
  column: 2
  items:
   - COOKED_PORKCHOP;2 for 4 of bronze
   - GOLDEN_APPLE for 2 of iron
   - BREAD;10 for 5 of gold

- stack:
   type: POTION
   meta:
    ==: ItemMeta
    meta-type: POTION
    display-name: "Drinks"
    lore:
     - "Not enough? Use these potions and you'll feel better!"
    potion-type: strength
  row: 3
  column: 6
  items:
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: healing
     price: 3 of iron
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strong_healing
     price: 5 of iron
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: swiftness
     price: 7 of iron
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strength
     price: 1 of gold
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: regeneration
     price: 3 of gold

- stack: "SANDSTONE;1;Blocks;Get to the others! Possible with blocks."
  linebreak: before
  items:
   - CUT_SANDSTONE;2 for 1 of bronze
   - END_STONE;3 for 7 of bronze
   - IRON_BLOCK for 3 of iron
   - GLOWSTONE;4 for 15 of bronze
   - price: 4 of bronze
     properties: "applycolorbyteam"
     stack: GLASS

- stack: "TNT;1;Useful Stuff;Looking for useful stuff? Here are some!"
  column: center
  items:
   - CHEST for 1 of iron
   - ENDER_CHEST for 1 of gold
   - price: 3 of iron
     stack: "TNT;1;Autoigniteable TNT"
     properties:
      - name: "AutoIgniteableTnt"
        explosion-time: 5
        damage-placer: false
   - price: 7 of iron
     properties:
      - name: "WarpPowder"
        delay: 6
     stack:
      type: GUNPOWDER
      display-name: "Warp Powder"
      lore:
       - "When using this powder you'll get"
       - "teleported to you spawn point within 6 seconds"
       - "Warning: Any movement will stop the process"
   - price: 3 of iron
     properties:
      - name: "Trap"
        data:
         - sound: ENTITY_SHEEP_AMBIENT
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 15
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 18
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 2
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
     stack:
      type: STRING
      display-name: "Trap"
      lore:
       - "Get informed if an enemy steps on your trap"
       - "and your enemy won't be able to move properly."
   - price: 6 of iron
     properties:
      - name: "MagnetShoes"
        probability: 75
     stack:
      type: IRON_BOOTS
      display-name: "Magnet-Shoes"
      lore:
       - "Wear those shoes and have a 75%"
       - "chance of getting no knockback!"
   - price: 5 of iron
     properties: "Tracker"
     stack:
      type: COMPASS
      display-name: "Tracker"
      lore:
       - "Wanna know where your closest target is?"
       - "Let's try this out!"
   - price: 15 of iron
     properties:
      - name: "rescueplatform"
        delay: 5
     stack:
      type: BLAZE_ROD
      display-name: "Rescue Platform"
      lore:
       - "Protect yourself from falling into"
       - "void with a Rescue Platform."
       - "This is your last hope!"
   - price: 5 of gold
     properties:
      - name: "arrowblocker"
        delay: 5
     stack:
      type: ENDER_EYE
      display-name: "Arrow Blocker"
      lore:
       - "Block arrows that are coming"
       - "for you with black magic."
       - "I mean, with this item."
   - price: 64 of bronze
     properties:
      - name: "protectionwall"
     stack:
      type: BRICKS
      display-name: "Protection Wall"
      lore:
       - "Instantly builds a wall that"
       - "can save your life!"
   - price: 24 of iron
     properties:
      - name: "Golem"
        speed: 0.25
        follow: 16.0
     stack:
      type: GHAST_SPAWN_EGG
      display-name: "Golem"
      lore:
       - "An iron golem that will protect"
       - "your team from the enemies."
   - price: 10 of gold
     properties: "TNTSheep"
     stack:
      type: SHEEP_SPAWN_EGG
      display-name: "TNT Sheep"
      lore:
       - "Use the TNT-Sheep! It will"
       - "walk towards your closest enemy"
       - "and explode within 8 seconds!"
   - price: 40 of iron
     properties: "ThrowableFireball"
     stack:
       type: FIRE_CHARGE
       display-name: "Fireball"
       lore:
         - "Is it a bird? Is it a plane?"
         - "By the time you know"
         - "you are dead!"

- stack: "DIAMOND_PICKAXE;1;Pickaxes;Destroy others blocks? Use these pickaxes."
  column: right
  items:
   - price: 4 of bronze
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 1
   - price: 2 of iron
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 2
   - price: 1 of gold
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 3

#### If there are problem with only one game, paste here config of this game
name: bw
pauseCountdown: 60
gameTime: 3600
world: BedWars
pos1: -99.5;100.0;100.5;180.0;0.0
pos2: 100.5;0.0;-99.5;-180.0;0.0
specSpawn: 0.5;100.0;0.5;180.0;90.0
lobbySpawn: 0.0;118.0;0.0;-180.0.1995904
lobbySpawnWorld: BedWars
minPlayers: 2
postGameWaiting: 3
teams:
  起床红:
    isNewColor: false
    color: RED
    maxPlayers: 16
    bed: 0.0;67.0;67.0;0.0;0.0
    spawn: 0.5;66.0;78.5;-180.0;0.0
  起床黄:
    isNewColor: false
    color: YELLOW
    maxPlayers: 16
    bed: -67.0;67.0;0.0;0.0;0.0
    spawn: -77.5;66.0;0.5;-90.0;0.0
  起床蓝:
    isNewColor: false
    color: LIGHT_BLUE
    maxPlayers: 16
    bed: 0.0;67.0;-67.0;0.0;0.0
    spawn: 0.5;66.0;-77.5;0.0;0.0
  起床绿:
    isNewColor: false
    color: LIME
    maxPlayers: 16
    bed: 67.0;67.0;0.0;0.0;0.0
    spawn: 78.5;66.0;0.5;-270.0;0.0
spawners:
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 0.5;65.5;82.5;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 0.5;65.5;82.5;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: iron
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -81.5;65.5;0.5;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -81.5;65.5;0.5;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: iron
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 0.5;65.5;-81.5;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 0.5;65.5;-81.5;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: iron
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 82.5;65.5;0.5;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 82.5;65.5;0.5;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: iron
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -28.5;67.0;31.5;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: diamond
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -30.5;67.0;-28.5;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: diamond
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 29.5;67.0;-30.5;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: diamond
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 31.5;67.0;29.5;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: diamond
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -6.5;71.0;-10.5;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: emerald
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 8.5;71.0;12.5;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: emerald
stores:
- isBaby: 'false'
  loc: 6.5;66.0;-78.5;90.0;0.0
  parent: 'false'
  shop: shop.yml
  name: Store
  skin: null
  type: VILLAGER
- isBaby: 'false'
  loc: -78.5;66.0;-5.5;360.0;0.0
  parent: 'false'
  shop: shop.yml
  name: Store
  skin: null
  type: VILLAGER
- isBaby: 'false'
  loc: -5.5;66.0;-78.5;270.0;0.0
  parent: 'false'
  shop: upgradeShop.yml
  name: TeamUpgrades
  skin: null
  type: VILLAGER
- isBaby: 'false'
  loc: 79.5;66.0;6.5;180.0;0.0
  parent: 'false'
  shop: shop.yml
  name: Store
  skin: null
  type: VILLAGER
- isBaby: 'false'
  loc: 6.5;66.0;79.5;-270.0;0.0
  parent: 'false'
  shop: upgradeShop.yml
  name: TeamUpgrades
  skin: null
  type: VILLAGER
- isBaby: 'false'
  loc: -5.5;66.0;79.5;270.0;0.0
  parent: 'false'
  shop: shop.yml
  name: Store
  skin: null
  type: VILLAGER
- isBaby: 'false'
  loc: -78.5;66.0;6.5;180.0;0.0
  parent: 'false'
  shop: upgradeShop.yml
  name: TeamUpgrades
  skin: null
  type: VILLAGER
- isBaby: 'false'
  loc: 79.5;66.0;-5.5;0.0;0.0
  parent: 'false'
  shop: upgradeShop.yml
  name: TeamUpgrades
  skin: null
  type: VILLAGER
constant:
  compass-enabled: inherit
  add-wool-to-inventory-on-join: inherit
  in-lobby-colored-leather-by-team: inherit
  allow-crafting: inherit
  join-randomly-after-lobby-timeout: inherit
  join-randomly-on-lobby-join: inherit
  keep-inventory-on-death: inherit
  prevent-killing-villagers: inherit
  player-drops: inherit
  friendlyfire: inherit
  lobbybossbar: inherit
  bossbar: inherit
  lobbyscoreboard: inherit
  scoreboard: inherit
  prevent-spawning-mobs: inherit
  spawner-holograms: inherit
  spawner-disable-merge: inherit
  game-start-items: inherit
  player-respawn-items: inherit
  spawner-holograms-countdown: inherit
  damage-when-player-is-not-in-arena: inherit
  remove-unused-target-blocks: inherit
  allow-block-falling: inherit
  holo-above-bed: inherit
  allow-spectator-join: inherit
  anchor-auto-fill: inherit
  anchor-decreasing: inherit
  cake-target-block-eating: inherit
  target-block-explosions: inherit
arenaTime: WORLD
arenaWeather: default
lobbyBossBarColor: default
gameBossBarColor: default

**Comment by zlataovce** [comment]
did you edit one of these values manually?

**Comment by CJYKK** [comment]
> did you edit one of these values manually? and use a pastebin next time please

Sorry...
Yes, I edited the coordinates

**Comment by zlataovce** [comment]
you have double decimal points in the lobbySpawn coordinate, recheck it

**Comment by CJYKK** [comment]
> you have double decimal points in the lobbySpawn coordinate, recheck it

Oh, I didn't see it! Thank you very much!

**Comment by CJYKK** [comment]
Now it works!
