### ISSUE TITLE
Sign problem [Screaming Bedwars]

### ISSUE THREAD

**Issue by DyrNo** [ScreamingSandals/BedWars#383]
I have created two bedwars games SOLO and DUO, but for some reason i cant make the join sign for DUO.
It have worked be, even tried to remake the arena. When i click the sign it says player left the game.
![sign](https://user-images.githubusercontent.com/92925346/139709573-b22e24b6-45bb-4b83-be6d-dcf07260373f.png)

**Comment by zlataovce** [comment]
insufficient information, follow the issue template
