### ISSUE TITLE
Can’t join bedwars game.

### ISSUE THREAD

**Issue by Superior126** [ScreamingSandals/BedWars#385]
#### Describe the bug
When you use the command to join a game one of two things happen. Either the command does nothing or it kicks you from the server.

#### Server and plugin version
Spigot version: 1.17.1
BedWars version: 3.0 

#### Console log
Nothing unusual 
#### Configuration (of config.yml and shop.yml)
Default config
#### If there are problem with only one game, paste here config of this game
Problem is with all games

**Comment by Misat11** [comment]
I recommend you to not use snapshots of Bedwars 0.3.0 now, they are not stable enough.

**Comment by zlataovce** [comment]
fill out the issue template properly.
