### ISSUE TITLE
Question about API

### ISSUE THREAD

**Issue by PikaMug** [ScreamingSandals/BedWars#387]
Which event should be used to detect when a player purchases something from a shop? I tried [BedwarsUpgradeBoughtEvent](https://jd.screamingsandals.org/sbw-0-2-x/BedWars-API/org/screamingsandals/bedwars/api/events/BedwarsUpgradeBoughtEvent.html) but that didn't trigger on Screaming BedWars 0.2.20.

**Comment by Misat11** [comment]
BedQarsUpgradeBoughtEvent is fired only when an upgrade is purchased. I have just noticed that there is no item bought event.

**Comment by zlataovce** [comment]
implemented in [0.2.21 snapshots](https://repo.screamingsandals.org/repository/maven-snapshots/org/screamingsandals/bedwars/BedWars/0.2.21-SNAPSHOT/BedWars-0.2.21-20211130.143132-21.jar)
