### ISSUE TITLE
tps drop during the round

### ISSUE THREAD

**Issue by Moinsn** [ScreamingSandals/BedWars#396]
During a Bedwars round, the server's tps drops below 15, regardless of how many players are in the round.

#### Server and plugin version
Spigot version: Spigot 1.16.4
BedWars version: Screaming BedWars 0.2.22

**Comment by zlataovce** [comment]
provide Timings or a spark profiler report

**Comment by Moinsn** [comment]
- Do you mean this?
![2022-01-01_20 35 07](https://user-images.githubusercontent.com/96842454/147858763-6515f559-25cb-4429-b081-7efbcbcef4da.png)

**Comment by zlataovce** [comment]
do `/spark profiler --timeout 60` when it's lagging, wait until it finishes and send us the link

**Comment by Moinsn** [comment]
https://spark.lucko.me/31O5DTQGDf

**Comment by pronze** [comment]
Doesn't seem like a BedWars issue to me, chunk and entity tick logic is taking a huge toll on the server as per reports. 

Either optimize or upgrade your server.

**Comment by Moinsn** [comment]
But the tps only drops in BedWars and not in other minigam

**Comment by zlataovce** [comment]
from the profiler output, BedWars is only taking 0.7% of the tick, which is pretty low, are you sure you don't have an excessive amount of entities on the map or anything that could seriously lag the server?

**Comment by Moinsn** [comment]
That could be. I leave a big world permanently loaded. But then why is the CPU load so low?

**Comment by zlataovce** [comment]
having a lot of entities loaded doesn't stress the CPU much, your problem seems to be that your system's RAM is exhausted, the OS is probably gasping for free RAM

**Comment by Moinsn** [comment]
Okay thank you for your help. I checked this and saw that when the server is on, there is not much ram available to the system.

**Comment by zlataovce** [comment]
also regarding your server command line flags, you should use aikar's flags that are optimized for >10GB of ram (check https://mcflags.emc.gs [be patient, his blog is slow af]) and Xmx and Xms should match

**Comment by Moinsn** [comment]
But why doesn't the Minecraft server take the RAM it needs? If the problem is RAM, why doesn't the server take all that is available? 
![2022-01-03_17 18 10](https://user-images.githubusercontent.com/96842454/147955222-ae98440c-cd54-4c1f-8422-518aabfba0d8.png)
