### ISSUE TITLE
Can not enable the plugin while Vault is present

### ISSUE THREAD

**Issue by adamek0202** [ScreamingSandals/BedWars#398]
#### Describe the bug
When i try to start a server vith this plugin in combination vith Vault, it fails to enable and gives error "java.lang.NullPointerException: Vault economy could not be loaded!" and disbles with another error.
When Vault is not present, it loads normaly without any errors.

#### Server and plugin version
Spigot version: git-Paper-408
BedWars version: 0 3.0-SNAPSHOT

#### Installed plugins on server (can be obtained by `/pl`)
BedWars
Citizens
HolographicDisplays
InvSeePlusPlus
LuckPerms
Multiverse-Core
MyWarp
OldCombatMechanics
PlaceholderAPI
ProtocolLib, SkinsRestorer
TAB
TrollBoss
Vault
WorldEdit
WorldGuard

#### Console log
https://pastebin.pl/view/fded287f

#### Configuration (of config.yml and shop.yml)
https://pastebin.pl/view/d7e98b39

**Comment by zlataovce** [comment]
0.3.0 is not ready for usage at all
