### ISSUE TITLE
[Ceph] Bugfixes needed

### ISSUE THREAD

**Issue by iamceph** [ScreamingSandals/BedWars#40]
- [x] Fireworks that are fired after won match, can kill the player.
- [x] TNT aren't breaking any blocks (they need to break player-placed blocks - configurable)
- [x] Change permissions for start item to 'bw.vip.startitem'
- [x] Allow to completly disable start item - by removing bw.vip.startitem permissions
- [x] Players can't place blocks on bed
- [x] Allow Traps to be destroyed, give players effects tho

Bugs tba

**Comment by Bbro122** [comment]
The start item is on the to-do list, and you cant place blocks on beds even in hypixel, you have to build around it then build up and over, tnt does need to be updated most

**Comment by Misat11** [comment]
@Bbro122 all things from this are already completed (exclude Players can't place blocks on bed)

**Comment by iamceph** [comment]
This is my personal list of things that I want to create/fix. :)
