### ISSUE TITLE
Abnormal throwing object

### ISSUE THREAD

**Issue by AdminHcat** [ScreamingSandals/BedWars#406]
#### Describe the bug
When I load  BedWars players can't throw objects normally

There are problems with any missile, such as Potion, end pearls, fishing rods
After unload  BedWars  it will be normal

#### Server and plugin version
Spigot version:  purpur 1.18.1 1555
BedWars version: BedWars-0.3.0-SNAPSHOT-910

#### Installed plugins on server (can be obtained by `/pl`)

Plugins (75): ArtMap, AuthMe, BanItem, BentoBox, BetterRTP, Boom, CatchBall, ChatManager, ChestsPlusPlus, ChickenShedder, Chunky, ClientDetector, CMILib, CoreProtect, CraftBook5, CraftEnhance, CRUtils, CustomBansPlus, DecentHolograms, deenchantment, DeluxeMenus, DiceFurniture, Duels, EliteMobs, Essentials, EssentialsSpawn, ExcellentEnchants, FarmControl, FartherViewDistance, FastAsyncWorldEdit (WorldEdit), FastClearLag, FurnitureLib, Geyser-Spigot, GSit, ILoreEdit, ImageOnMap, InventoryRollbackPlus, ItemEdit, ItemJoin, LargeRaids, LiteItemShow, LiteSignIn, LuckPerms, Maintenance, MarriageMaster, mcMMO, MiaoChat, Minepacks, MiniMOTD, Multiverse-Core, Multiverse-Inventories, MyCommand, NexEngine, NoCheatPlus, OpenInv, PlaceholderAPI, PlayerTitle, ProtectionLib, ProtocolLib, QuickShop, Residence, ServerBackup, SimpleClans, SkinsRestorer, Skulls, sleep-most, StackMob, ThrowableFireballs, TradeSystem, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, ViaVersionStatus, WorldBorderAPI

#### Configuration (of config.yml and shop.yml)
default

**Comment by Misat11** [comment]
Snapshots of 0.3.0 are very experimental so we recommend you to stay with 0.2.22 for now.

**Comment by Misat11** [comment]
should be fixed in latest snapshot
