### ISSUE TITLE
Kicks me every time I join a BedWars game.

### ISSUE THREAD

**Issue by TheOverlordBunny** [ScreamingSandals/BedWars#407]
Every time I try to join a BedWars game, it works fine for a bit, but then when I go to my bed, back near the shops, I get disconnected and all it says is "Disconnected" and it's very annoying because it means I can't play 1v1 Bedwars with my friends.
Oh yeah, when I get disconnected, this shows up in the console.
**xyantoaster lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.IntList.size()" because "list" is null**
There is also a LOT of this is my console.
<html>
<body>

[18:45:56] [Netty Epoll Server IO #2/ERROR]: Packet encoding of packet ID 58 threw (skippable? false)
--
600 | java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.IntList.size()" because "list" is null
601 | at net.minecraft.network.FriendlyByteBuf.writeIntIdList(FriendlyByteBuf.java:166) ~[app:?]
602 | at net.minecraft.network.protocol.game.ClientboundRemoveEntitiesPacket.write(ClientboundRemoveEntitiesPacket.java:26) ~[app:?]
603 | at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:44) ~[patched_1.17.1.jar:git-Paper-408]
604 | at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:15) ~[patched_1.17.1.jar:git-Paper-408]
605 | at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source) ~[?:?]
606 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
607 | at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
608 | at com.viaversion.viaversion.util.PipelineUtil.callEncode(PipelineUtil.java:93) ~[ViaVersion-4.1.1.jar:?]
609 | at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:71) ~[ViaVersion-4.1.1.jar:?]
610 | at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source) ~[?:?]
611 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
612 | at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
613 | at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528) ~[ProtocolLib.jar:?]
614 | at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70) ~[ProtocolLib.jar:?]
615 | at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268) ~[ProtocolLib.jar:?]
616 | at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[patched_1.17.1.jar:git-Paper-408]
617 | at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274) ~[ProtocolLib.jar:?]
618 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Paper-408]
619 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.17.1.jar:git-Paper-408]
620 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.17.1.jar:git-Paper-408]
621 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.17.1.jar:git-Paper-408]
622 | at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[patched_1.17.1.jar:git-Paper-408]
623 | at io.github.pronze.lib.screaminglib.bukkit.utils.nms.network.PacketOutboundListener$1.write(PacketOutboundListener.java:30) ~[SBA-1.5.5.jar:?]
624 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Paper-408]
625 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.17.1.jar:git-Paper-408]
626 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.17.1.jar:git-Paper-408]
627 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.17.1.jar:git-Paper-408]
628 | at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[patched_1.17.1.jar:git-Paper-408]
629 | at kernitus.plugin.OldCombatMechanics.utilities.packet.mitm.PacketInjector.write(PacketInjector.java:184) ~[OldCombatMechanics.jar:?]
630 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Paper-408]
631 | at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[patched_1.17.1.jar:git-Paper-408]
632 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[patched_1.17.1.jar:git-Paper-408]
633 | at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[patched_1.17.1.jar:git-Paper-408]
634 | at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[patched_1.17.1.jar:git-Paper-408]
635 | at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[patched_1.17.1.jar:git-Paper-408]
636 | at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[patched_1.17.1.jar:git-Paper-408]
637 | at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) ~[ProtocolLib.jar:?]
638 | at net.minecraft.network.Connection.doSendPacket(Connection.java:450) ~[app:?]
639 | at net.minecraft.network.Connection.lambda$writePacket$8(Connection.java:424) ~[app:?]
640 | at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351) ~[ProtocolLib.jar:?]
641 | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[patched_1.17.1.jar:git-Paper-408]
642 | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[patched_1.17.1.jar:git-Paper-408]
643 | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[patched_1.17.1.jar:git-Paper-408]
644 | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Paper-408]
645 | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Paper-408]
646 | at java.lang.Thread.run(Thread.java:831) ~[?:?]

</body>
</html>
Any help would be very appreciated.

**Comment by boiscljo** [comment]
1st that error is SBA and not bedwars, 2nd you have an outdated SBA that cause the error cause it does not have 1.17.1 support, only 1.17

**Comment by zlataovce** [comment]
not a BedWars issue
