### ISSUE TITLE
Stats Holograms don't show unless plugin is reloaded

### ISSUE THREAD

**Issue by kencinder** [ScreamingSandals/BedWars#408]
#### Describe the bug
Stats holograms don't show for players connecting to the server unless the plugin is reloaded. They show fine when created for anyone connected, but new players joining or leaving the server and coming back on they don't show.

Tested and reproduced on clean test server to be sure.

Join server, `/bw addholo stats` and hologram appears, leave server and rejoin and hologram is gone. Do `/bw reload` and the hologram reappears.

#### Server and plugin version
Spigot version: Paper 1.18.1-216
BedWars version: 0.2.22

#### Installed plugins on server (can be obtained by `/pl`)
Plugins (2): BedWars, LuckPerms

#### Console log
No errors, not relevant.

#### Configuration (of config.yml and shop.yml)
Default, unchanged

**Comment by ajh123** [comment]
Effects me on 0.2.23  paper 1.18.2-242

**Comment by iamceph** [comment]
@kencinder You are using outdated version, use 0.2.23.

**Comment by kencinder** [comment]
That version was not even reeleased when I posted the issue...

**Comment by iamceph** [comment]
Now it is :D

**Comment by kencinder** [comment]
And the issue still isn't fixed...

**Comment by zlataovce** [comment]
fixed, sorry for the massive delay, snapshot build [here](https://repo.screamingsandals.org/snapshots/org/screamingsandals/bedwars/BedWars/0.2.24-SNAPSHOT/BedWars-0.2.24-20220422.174306-3.jar)
