### ISSUE TITLE
[Feature]: Adding support Vault Placeholder Api

### ISSUE THREAD

**Issue by nareshalka** [ScreamingSandals/BedWars#411]
#### Describe the solution you'd like
I would like to be able to display the prefixes and suffixes of the players during the game (both in the chat and in the tab).
It turns out that the player, having bought a donation, in fact does not visually see who he is ([Admin] or [VIP]). In addition, the absence of %vault_*% spoils the overall picture of the server.

**Comment by zlataovce** [comment]
you can use %prefix% and %suffix% in bedwars message formats, that gets taken from Vault

**Comment by pixkk** [comment]
Tell me, if I use these prefixes, the team name or nick will not be repainted in the color of the prefix?

**Comment by zlataovce** [comment]
> Tell me, if I use these prefixes, the team name or nick will not be repainted in the color of the prefix?

the placeholders are directly replaced with the string that Vault provides, any colors from the prefix/suffix will be applied as well

**Comment by pixkk** [comment]
Will the chat work fine too?  in the previous update it broke when using prefixes and suffixes.

**Comment by zlataovce** [comment]
> Will the chat work fine too? in the previous update it broke when using prefixes and suffixes.

as long as you don't break the other placeholders in the chat-format in the config, it should work just fine

**Comment by pixkk** [comment]
OK, thanks for answer.  I'll test it tomorrow and report the result.  If successful, I'll close the thread.
