### ISSUE TITLE
Players get kicked on death

### ISSUE THREAD

**Issue by DJAMIRSAM** [ScreamingSandals/BedWars#424]
![image](https://user-images.githubusercontent.com/78499690/180273445-28082240-f4a0-4697-96fe-6f5860fd873d.png)

When a player dies they get kicked from the game

here is a list of plugins
![image](https://user-images.githubusercontent.com/78499690/180273582-fccb513c-1fbe-453e-8eaf-2d12d6ac575f.png)

**Comment by Misat11** [comment]
What version of Minecraft, do you use? In early spigot 1.19 builds there was a bug that caused this (make sure to NOT download the server software from getbukkit.org, this site always serves outdated builds)

**Comment by DJAMIRSAM** [comment]
> What version of Minecraft, do you use? In early spigot 1.19 builds there was a bug that caused this (make sure to NOT download the server software from getbukkit.org, this site always serves outdated builds)

i am using 1.17.1 and connecting 1.19 clients with via version

**Comment by DJAMIRSAM** [comment]
ok upon further discovery this only happens in 1.19
probably and issue with Viaversion

**Comment by zlataovce** [comment]
for 1.19, you need the dev builds of ViaVersion if I recall correctly
