### ISSUE TITLE
Compass teleport

### ISSUE THREAD

**Issue by sansta** [ScreamingSandals/BedWars#433]
When I'm selecting a team with the compass the plugin teleports me around in the world

**Comment by JustAHuman-xD** [comment]
This is not caused by sbw
Check World Edit

**Comment by JustAHuman-xD** [comment]
https://docs.screamingsandals.org/BedWars/0.2.26/troubleshooting/#compass-teleports-the-player

**Comment by JohnHeikens** [comment]
this issue should be closed @sansta
