### ISSUE TITLE
Stores not working in 1.19.2

### ISSUE THREAD

**Issue by Nachtmaken** [ScreamingSandals/BedWars#440]
#### Describe the bug
When I've placed down the various shops and saved the arena. As soon as I go to start the game the NPC villager stores aren't showing up.

#### Server and plugin version
Spigot version: 1.19.2
BedWars version: 0.2.26

#### Installed plugins on server (can be obtained by `/pl`)
BedWars, BungeeGuard, BungeeTabListPlus, CommandPanels, dDiscordBot, Denizen, Depenizen, DiscordSRV, Essentials, FastAsyncWorldEdit (WorldEdit), HuskHomes, HuskHomesGUI, LiteBans, LuckPerms, Multiverse-Core, MysqlEcoBridge*, NoChatReports, PlaceholderAPI, ProtocolLib, SyncCommands, TAB-Bridge, TNTRun_reloaded, Vault, VentureChat, WarpShortCut, WorldGuard

#### Console log
[latest_1.log](https://github.com/ScreamingSandals/BedWars/files/9693170/latest_1.log)

#### Configuration (of config.yml and shop.yml)
https://paste.gg/p/anonymous/d89a4539a2d147eda525c5fcb6e6e955

**Comment by Misat11** [comment]
Is animal (npc) spawning enabled in that world or is any of your plugins preventing that?

**Comment by Nachtmaken** [comment]
Yep that fixed it cheers!
