### ISSUE TITLE
Admin Join Game in progress.

### ISSUE THREAD

**Issue by myxxmikeyxx** [ScreamingSandals/BedWars#441]
#### Describe the solution you'd like
Having a command to join a game in progress for an admin, or having a command to destroy all beds to make the game go faster.

#### Is your feature request related to a problem? Please describe
No problem to report, just work at a school and the students want some fun games to play but sometimes they take too long and we need to speed up the game. We would like the ability to do 
/bw admin <arena> destroy bed <team/all>
/bw admin <arena> joingame <team/random>

Also we would like that admins can join a team as an extra player even if the team is already full, allow admins to override the Max number.

**Comment by Lort533** [comment]
You can't join a team, I assume that would be a game breaking change - not sure if you can spectate, but I don't think so (at least not as a game spectator, but only watching what players do on the map). With destroying beds, I think you can do that using BedWars API (I think the same for joining running games).

**Comment by myxxmikeyxx** [comment]
Gotcha, would you like me to close this or leave this open as a future feature request?

**Comment by Lort533** [comment]
Just leave this open I think, there was no reply from the author yet.

**Comment by Lort533** [comment]
Actually nevermind, it seems like you can join a full game as I didn't read the code properly, you can use `bw.vip.forcejoin` permission to do that. Even then I don't think you can join a running game.

**Comment by Misat11** [comment]
Ok, I think this can be implemented easily. However I think that these two commands belong to the `/bw cheat` category, because it kinda "breaks" the game. (`/bw admin` subcommand is used for arena editing anyways)

**Comment by myxxmikeyxx** [comment]
I will have to look into the cheats. I saw that option but didn't find the docs on it easily and was in the middle of trying to run the game for the kids.

**Comment by Misat11** [comment]
A new snapshot version of SBW 0.2.27 is available here: https://repo.screamingsandals.org/snapshots/org/screamingsandals/bedwars/BedWars/0.2.27-SNAPSHOT/BedWars-0.2.27-20221009.160855-3.jar

I have added three new commands:
* /bw cheat destroybed <team>
* /bw cheat destroyallbeds
* /bw cheat jointeam [team] - If you want to join random team, just omit the team. Despite this command can join you to the full team, the normal command won't allow other player to join if you have used this command to join. So be the last who joins the team. You can also use this command while the game is running (it is not perfect, but it somehow works).

All these commands require the admin to be in the bedwars game (being spectator is enough).

*In case you are using snapshots of SBW 0.3.0 (which is not recommended at the moment), I'm gonna port it soon*

**Comment by myxxmikeyxx** [comment]
Awesome! Thank you so much. I will have to try it out.
