### ISSUE TITLE
Is it possible to change to message when a player joins an arena?

### ISSUE THREAD

**Issue by Codecrafter14** [ScreamingSandals/BedWars#442]
I'm using a nick plugin and I want to change to join message. The nick plugin provides a placeholder with the nicked name, and if the player is not nicked, the original player name. I didn't found anything in the config...

**Comment by Misat11** [comment]
This plugin (like most of the plugins) uses display names instead of player name, because these names are changeable by plugins. Your nick plugin should be able to change display names. And if not, consider using a different plugin.
