### ISSUE TITLE
SBA Compatibility

### ISSUE THREAD

**Issue by NopeProsOnly** [ScreamingSandals/BedWars#449]
I know that SBA is outdated, and discontinued. But in the last Bedwars update, a few things stop working. Like the Upgrade Shop from SBA...

I am using Paper:
`This server is running Paper version git-Paper-304 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 96fdafd)`
Bedwars Version: `BedWars version 0.2.27.1`
SBA Version: `SBA version 1.5.7.2-h1` <-- Latest... Sad it was discontinued...
I will provide more information when requested.

**Comment by Misat11** [comment]
SBA is not discontinued, there's just a different developer working on it. And 1.5.7.2-h1 is actually just 3 days old. https://www.spigotmc.org/resources/sba-screaming-bedwars-addon-1-9-4-1-19-3.99149/

**Comment by NopeProsOnly** [comment]
Ah thanks. That's great that it isn't discontinued. And even better that there is another dev actually working on it.

So I guess this is a problem for them. Not Bedwars?

**Comment by Misat11** [comment]
There was no big change since latest BedWars release, so I don't think this bug is related to BedWars.

**Comment by NopeProsOnly** [comment]
Ok thank you.
