### ISSUE TITLE
Items stay in players inventory after they leave.

### ISSUE THREAD

**Issue by NopeProsOnly** [ScreamingSandals/BedWars#450]
This has to do with Multiverse plugin and Bedwars plugin.
If a player leaves while in a game, they will keep the items for when they rejoin and go back into the world that the bedwars game was in.
`This server is running Paper version git-Paper-304 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 96fdafd)`
`BedWars version 0.2.27.1`

**Comment by Misat11** [comment]
Multiverse-Inventories plugin is not really supported by BedWars because of how the mv plugin handles inventory switching. I recommend you to create a mainlobby world which would share the inventory with the bedwars worlds. Then you should not allow players to use /bw join or use some other plugin to disable /bw join command in the worlds other than mainlobby.

**Comment by NopeProsOnly** [comment]
Ah. That's unfortunate. The way I have my server set up, I can't do that without breaking a few things. My bedwars lobby is in the same world as the bedwars game. Infact, I have multiple bedwars games in the same world. I used permissions to deny everything anything related in the lobby... I use skript for that stuff.

**Comment by Misat11** [comment]
You can have multiple arenas and mainlobbx in the same world, why not, my point was that the player should first be teleported to the lobby and from here join the bw game, not from random world on your server.

**Comment by NopeProsOnly** [comment]
Oh ofc. I already have that. They have to be in the bedwars lobby first to even have access to the bw commands.

**Comment by NopeProsOnly** [comment]
I'm slowly migrating to bungee though. So this won't be much of an issue for me. Might for some other people.

**Comment by Misat11** [comment]
I'm gonna close this issue as we have multiple issues tracking these inventory clearing bugs. Any conversation regarding this topic should continue in #460
