### ISSUE TITLE
Cant buy

### ISSUE THREAD

**Issue by pajkopajko** [ScreamingSandals/BedWars#453]
#### Describe the bug
Cant buy any items after installing plugins. Not sure which is doing this conflict.

#### Server and plugin version
Spigot version: 1.19.2
BedWars version: 0.2.27.1

#### Installed plugins on server (can be obtained by `/pl`)

Plugins (10): BedWars, LifeSteal-Smp-Plugin, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, ntdLuckyBlock, Oneblock, PerWorldPlugins, SkinsRestorer, WorldEdit

#### Console log
none

#### Configuration (of config.yml and shop.yml)
oryginal

**Comment by boiscljo** [comment]
There is an incompatibility with PerWorldPlugins, it break bedwars in a way the shop doesn't work. Remove that plugin and it will work. It's NOT fixable by bedwars, only by PerWorldPlugins teams which won't do anything except telling you to remove it.

**Comment by pajkopajko** [comment]
Ok. thank You :)
