### ISSUE TITLE
import quickbuy from hypixel

### ISSUE THREAD

**Issue by ARDragssss** [ScreamingSandals/BedWars#454]
#### Describe the solution you'd like
its something really simple yet really effective. You can just click on a certain item and your quickbuy from hypixel gets imported.

Another great thing would be to fix the Price: 1 of iron in red glass quickbuy item and make the whole page customizable, just like the hypixel shop.

#### Is your feature request related to a problem? Please describe
no

**Comment by Misat11** [comment]
This sounds like something that should be reported in SBA repo (talking about the red glass quick buy item) as SBW itself does not have quickbuy.

And I have checked hypixel's API and I didn't find a way to obtain the information about the quickbuy of a certain player.

**Comment by ARDragssss** [comment]
oh ok tysm

**Comment by Clemintina** [comment]
> This sounds like something that should be reported in SBA repo (talking about the red glass quick buy item) as SBW itself does not have quickbuy.
> 
> And I have checked hypixel's API and I didn't find a way to obtain the information about the quickbuy of a certain player.

it's available under `favourites_2` and `favourites_1` I believe.
