### ISSUE TITLE
shops not showing up in the arena

### ISSUE THREAD

**Issue by joergsesterhenn** [ScreamingSandals/BedWars#459]
#### Describe the bug
I followed the instructions to setup an arena. I added shops to all teams spawn areas, but when I start the game there is no shop.
I went back into edit mode and went to the same place where I added the shop the first time and tried to add it again (thought I might have missed the step). Then I got a message "Store already exists." I can even list the shops with the command. But I can not see the shop in the arena.

#### Server and plugin version
Spigot version: papermc 1.19.3-R01Snapshot (5aee09d) 
BedWars version: 0.2.27.1

#### Installed plugins on server (can be obtained by `/pl`)
GeyserMC, Floodgate, Luckperms, Multiverse(Core,Portal, SignsP, NetherP, Inventories), Wordedit, Voidgen, Worldguard

#### Console log
[latest.log](https://github.com/ScreamingSandals/BedWars/files/10690590/latest.log)

#### Configuration (of config.yml and shop.yml)
[config.yml.txt](https://github.com/ScreamingSandals/BedWars/files/10690597/config.yml.txt)

[shop.yml.txt](https://github.com/ScreamingSandals/BedWars/files/10690598/shop.yml.txt)

#### If there are problem with only one game, paste here config of this game

[35f2db42-e735-45e1-b412-b9feb8be7ea9.yml.txt](https://github.com/ScreamingSandals/BedWars/files/10690601/35f2db42-e735-45e1-b412-b9feb8be7ea9.yml.txt)

**Comment by Misat11** [comment]
Do you have allowed mob/npc spawning? (server.properties, multiverse config)
BedWars protects the arena from mob spawning itself, so there's no need to protect the arena using a different way.

**Comment by joergsesterhenn** [comment]
You are correct. I stupidly had a worldguard flag to disable spawning in this world, that I forgot about. Everything's working fine now. Thanks!
