### ISSUE TITLE
Launch game

### ISSUE THREAD

**Issue by FewerElk** [ScreamingSandals/BedWars#463]
Simples player (who are not op) can't launch game.

**Comment by Misat11** [comment]
The diamond item is not the correct way to start the game. Players have to choose their teams. When at least two players have chosen different teams, the countdown starts and after ~ 60 secs (this is configurable per arena using command), the game starts. If you want to assign teams automatically (and therefore start the countdown automatically), open config.yml and set `join-randomly-on-lobby-join` or `join-randomly-after-lobby-timeout` (one of these, not both) to true.
