### ISSUE TITLE
Forbid cheat

### ISSUE THREAD

**Issue by FewerElk** [ScreamingSandals/BedWars#464]
Add a feature for admin can choose what command forbid in config.yml

**Comment by Misat11** [comment]
Can you give us some details and specify what commands do you want to "forbid"? From the title and description I'm not sure what is this feature request about.

**Comment by FewerElk** [comment]
/gm
/give
/fly
...
Like that modo can't cheat (with bedrock)

**Comment by zlataovce** [comment]
you can already deny commands via the `allowed-commands` configuration property (and modify its behavior with the following `change-allowed-commands-to-blacklist` property) for all people without the `bw.admin` permission

**Comment by FewerElk** [comment]
And for people with permission ? (op for example)

**Comment by pronze** [comment]
DeOP them.
