### ISSUE TITLE
Record

### ISSUE THREAD

**Issue by FewerElk** [ScreamingSandals/BedWars#469]
Hi, 
I see there is a file record.yml, but there is not command for record...
May you explain me this please ?

**Comment by Misat11** [comment]
Record file is used to store the best time in which a team has won. Each player from a team which breaks the record gets additional score according to your configuration. SBW 0.2.x use it only for this purpose, snapshots of SBW 0.3.x shows it when the game starts.

GitHub issues are meant for reporting bugs or requesting new features. For general questions and support use GitHub Discussions or our Discord server.
