### ISSUE TITLE
Persistent lobby inventory

### ISSUE THREAD

**Issue by FewerElk** [ScreamingSandals/BedWars#470]
#### Describe the bug
When waiting in a lobby, if I click on a bedwars sign I leave the lobby (normal) but my scoreboard and my lobby's inventory is persistent (with wool, compass...)
#### Server and plugin version
Spigot version: paper 1.19.3
BedWars version: 0.2.27.1

#### Installed plugins on server (can be obtained by `/pl`)
![image](https://user-images.githubusercontent.com/120582916/226669464-3f6877dd-4143-4e46-8daa-1a7030e72c12.jpeg)
#### Console log
None
#### Configuration (of config.yml and shop.yml)
https://paste.ogg/fe42ac0092c6445986cff34995f162f0

**Comment by Misat11** [comment]
I'm gonna close this issue as we have multiple issues tracking these inventory clearing bugs. Any conversation regarding this topic should continue in #460
