### ISSUE TITLE
Plugin Placeholders?

### ISSUE THREAD

**Issue by RangeBanenge** [ScreamingSandals/BedWars#472]
Plugin Placeholders?

**Comment by Misat11** [comment]
If you want to know placeholders for PAPI, please check this page: https://docs.screamingsandals.org/BedWars/0.2.26/placeholderapi/

Also note that Github Issues are used for reporting bugs or requesting new features, but for general question and support Github Discussions or our Discord server should be used.

**Comment by FewerElk** [comment]
What are placeholder ?
I'm sorry for this question here, but don't know a lot of think in this domain...

**Comment by Misat11** [comment]
> What are placeholder ? I'm sorry for this question here, but don't know a lot of think in this domain...

Placeholders are basically strings which are gonna be reppaced with a value. For example, imagine a placeholder %players%, this placeholder is gonna be replaced with the number of online players, for example 10. Each message may or may not support placeholders. PlaceholderAPI is a plugin which serves as a global library of placeholders which can be used in certain plugins. These plugins are usually connected with some visuals, like scoreboard, tab or holograms. (whether the plugin supports PAPI should be mentioned on their plugin page) BedWars registers new placeholders which can be used in these plugins.
