### ISSUE TITLE
Plugin disabled on launching

### ISSUE THREAD

**Issue by FewerElk** [ScreamingSandals/BedWars#476]
#### Describe the bug
The plugin is disabled when launching the server
#### Server and plugin version
Spigot version: 1.19.3
BedWars version: 0.2.27.1

#### Installed plugins on server (can be obtained by `/pl`)
see log, I can't launch the server for the moment, I'm sorry... :-(  And I've ViaVersion
#### Console log
Here logs file and errors
https://github.com/FewerElk/issues-support/tree/main/BedWars_SreamingSandals
#### Configuration (of config.yml and shop.yml)
Same as https://github.com/ScreamingSandals/BedWars/issues/470
#### If there are problem with only one game, paste here config of this game
No

**Comment by Misat11** [comment]
The problem is that it failed loading bedwars statistics from the file, it is probably malformed/broken.

**Comment by FewerElk** [comment]
Probably, I modified it today
--> I will check it tomorrow, I will recap
