### ISSUE TITLE
All holograms are duplicated

### ISSUE THREAD

**Issue by FoviOX** [ScreamingSandals/BedWars#48]
**Server and plugin version**
Spigot version: 1.12.2
BedWars version: 0.1.6

**Screenshot**
![2019-08-04_20 06 27](https://user-images.githubusercontent.com/33469628/62426945-3f319400-b6f4-11e9-8929-aa20fad492ff.png)

**Configuration**
[config.zip](https://github.com/Misat11/BedWars/files/3465116/config.zip)

**Comment by Blueyescat** [comment]
The hologram is not duplicated, there are 2+ holograms that shows stats of different players. Actually Holographic Displays needs ProtocolLib for player-specific holograms. Looks like it does that if ProtocolLib is not available.

**Comment by FoviOX** [comment]
> The hologram is not duplicated, there are 2+ holograms that shows stats of different players. Actually Holographic Displays needs ProtocolLib for player-specific holograms. Looks like it does that if ProtocolLib is not available.

I have ProtocolLib on my server. And the hologram is duplicated, because when I added this hologram it was one. Over time, 2 was duplicated, and then more and more, and at the end of the day there were so many holograms that I had to remove it due to lags.

**Comment by FoviOX** [comment]
On the arena holograms too dublicate. Errors don't found.
**Arena file:**
[Beach.zip](https://github.com/Misat11/BedWars/files/3467608/Beach.zip)
**In orange team:**
![2019-08-05_15 44 26](https://user-images.githubusercontent.com/33469628/62465727-45794c00-b798-11e9-92f4-a84d70d9daa5.png)
![2019-08-05_15 44 29](https://user-images.githubusercontent.com/33469628/62465732-46aa7900-b798-11e9-9350-e8d0925f9b1e.png)
**In green team:**
![2019-08-05_15 44 36](https://user-images.githubusercontent.com/33469628/62465752-55912b80-b798-11e9-8b6a-3191b5e04a66.png)
![2019-08-05_15 44 38](https://user-images.githubusercontent.com/33469628/62465756-575aef00-b798-11e9-814e-4d8409c361e8.png)

**Comment by Misat11** [comment]
@FoviOX Look into issue template and send me remaining informations (for example plugin list)

**Comment by FoviOX** [comment]
> @FoviOX Look into issue template and send me remaining informations (for example plugin list)

**All bedwars configuration (BedWars folder)**
[BedWars.zip](https://github.com/Misat11/BedWars/files/3467622/BedWars.zip)

**Plugin list:**
![Screenshot_20](https://user-images.githubusercontent.com/33469628/62466065-13b4b500-b799-11e9-9751-38064589990b.jpg)

**Comment by Misat11** [comment]
and are in game holograms duplicated while game running or when you start next game?

**Comment by FoviOX** [comment]
> and are in game holograms duplicated while game running or when you start next game?

I found this when players playing in arena.

**Comment by Bbro122** [comment]
Yo Thanks for posting this issue I simply downloaded protocol lib and everything was fixed

**Comment by AfkF24** [comment]
Having the same issue with holograms duplicating + not even getting removed on arena rollback. [ProtocolLib is indeed present.](http://ci.dmulloy2.net/job/ProtocolLib/425/)

**Comment by Bbro122** [comment]
Holos of stats arent part of the arena and I recommend making sure you get the newest version of protocol lib. the one that got mine working was:https://www.spigotmc.org/resources/protocollib.1997/

**Comment by Misat11** [comment]
All problems with status holograms should be fixed with commit bfac225d8b0ba3b49768148181e817d59880bda2
