### ISSUE TITLE
breakable

### ISSUE THREAD

**Issue by RangeBanenge** [ScreamingSandals/BedWars#481]
In short, if I write it in such cases, then the blocks either do not break at all, or they all break. 
  breakable:
  enabled: true
  asblacklist: false
  blocks: grass_block
  or
   blocks:
              - grass

**Comment by RangeBanenge** [comment]
paper 1.12.2

**Comment by Misat11** [comment]
By grass do you mean the tall grass or the grass block? if the tall grass, then try using `LONG_GRASS` on versions <= 1.12.2, grass is for newer versions

**Comment by RangeBanenge** [comment]
This function allows you to break the block that is on the top block?


чт, 27 апр. 2023 г. в 19:28, Misat11 ***@***.***>:

**Comment by RangeBanenge** [comment]
I understand that you inject a block there and it becomes destructible no?



чт, 27 апр. 2023 г. в 19:33, Максим Онищенко ***@***.***>:

**Comment by Misat11** [comment]
Yeah, you put there a type of block (or multiple types) and then this block can be broken.

**Comment by RangeBanenge** [comment]
I would like to know how to place the block there correctly, otherwise
I have already tried any blocks, even a stone, but it still does not
work.


чт, 27 апр. 2023 г. в 19:36, Misat11 ***@***.***>:
