### ISSUE TITLE
japanese

### ISSUE THREAD

**Issue by bunbun1217** [ScreamingSandals/BedWars#483]
I like this plugin!
However, I would like this plugin to support Japanese.
If possible, would it be possible to support Japanese? Please.

**Comment by Misat11** [comment]
There is a partial support for Japanese if you set `locale` to `ja` in config.yml. If you want to finish the translation or know someone who is capable of doing that, you can visit our weblate and contribute the translations: https://weblate.screamingsandals.org/projects/bedwars/0-2-x/

**Comment by bunbun1217** [comment]
Thank Misat11!

**Comment by kinoko2k** [comment]
All Japanese translation files for 0.3.x are already translated. 
Once the developer updates it, the Japanese translation should be available. Or rather, it was updated.
https://www.spigotmc.org/resources/screaming-bedwars-1-8-8-1-19-4.63714/update?update=493428
