### ISSUE TITLE
Store

### ISSUE THREAD

**Issue by RangeBanenge** [ScreamingSandals/BedWars#488]
How to make a command execute when clicking on an item in the store?
And how to make a store within a store?
I mean that when you click on an item in an open store, 2 stores open only already in the menu.

**Comment by LiveInGround** [comment]
For run command use an event plugin and about the store it is the case.

**Comment by RangeBanenge** [comment]
LiveInGround, Can you tell me what plugin?

**Comment by LiveInGround** [comment]
I haven't got any example but I asked for this plugin to FewerElk : https://github.com/FewerElk/FewerElktest/discussions/1.

**Comment by LiveInGround** [comment]
I haven't got any example but I asked for this plugin to FewerElk : https://github.com/FewerElk/FewerElktest/discussions/1.

**Comment by FewerElk** [comment]
Or else, you can create a fork and modify the plugin for your self-usage.

**Comment by RangeBanenge** [comment]
I meant that I need to buy a team, I want to create custom items in the store like rescue platforms and fireballs

**Comment by RangeBanenge** [comment]
But to be honest, I don’t understand how to write it correctly in the configuration under the subject ...
