### ISSUE TITLE
Can I make such a store?

### ISSUE THREAD

**Issue by RangeBanenge** [ScreamingSandals/BedWars#491]
![image](https://github.com/ScreamingSandals/BedWars/assets/123173065/8f5394b9-cc3d-491a-84dc-749614e4a385)
Can I make such a store?
Explanation: in the top bar are the menus and at the bottom are items for purchase.

**Comment by pronze** [comment]
Yes, It's possible. Refer the following file: https://github.com/pronze/SBA/blob/v1/plugin/src/main/resources/shops/shop.yml

You'll have to redefine the "top bar" items in every category to achieve this

**Comment by RangeBanenge** [comment]
Thank you!
