### ISSUE TITLE
[Feature]: %countdown% placeholder in lobby scoreboard

### ISSUE THREAD

**Issue by Leahcimkrob** [ScreamingSandals/BedWars#500]
Please add a countdown to the lobby-scoreboard?

Time to start:  x sec.

**Comment by Misat11** [comment]
Can you try the latest snapshot? I have added a new placeholder to lobby scoreboard called `%countdown%`

https://github.com/ScreamingSandals/BedWars/actions/workflows/build-0-2-x.yml

**Comment by Leahcimkrob** [comment]
Thank you, that works great.
But is it also possible that you get displayed waiting or something similar as long as players are missing and only when enough players are joined, the countdown is displayed?

**Comment by Misat11** [comment]
I've added a placeholder `%countdownwaiting%`, which shows a message defined in the language file under the key `waiting_placeholder_lobby_scoreboard` in case the countdown is not running due to waiting for more players. This issue can now be closed.
