### ISSUE TITLE
Spawner holograms disappears after death

### ISSUE THREAD

**Issue by SirvydasS** [ScreamingSandals/BedWars#503]
#### Describe the bug
Some spawner ()maybe who are far away from spawn point holograms disappears when you die.
At first join everything being good.
#### Server and plugin version
Spigot version: Current: git-Purpur-2023 (MC: 1.20.1)*
Previous: git-Purpur-2018 (MC: 1.20.1)
* You are running the latest version
BedWars version: BedWars-0.2.30-SNAPSHOT-142

**Comment by Misat11** [comment]
Can you try the latest snapshot? https://github.com/ScreamingSandals/BedWars/actions/workflows/build-0-2-x.yml

**Comment by SirvydasS** [comment]
With BedWars-0.2.30-SNAPSHOT-143 same issue

**Comment by SirvydasS** [comment]
When you die and start spectating holograms showing agian

**Comment by Misat11** [comment]
Sorry for such delay, if you are still experiencing this bug and still use our plugin, can you please try latest snapshot of 0.2.x?

**Comment by Misat11** [comment]
I'm closing this issue as it is inactive now. If anyone still has this issue even after mentioned fixes, please open a new issue with all necessarry information.
