### ISSUE TITLE
the -mainlobby command does not work-

### ISSUE THREAD

**Issue by nasmeshnick** [ScreamingSandals/BedWars#504]
hi, I can't install the command- mainlobby -version java 11|

I do everything as the author of the plugin intended, in the end nothing happens, please help

**Comment by Misat11** [comment]
Can you be more specific at what exactly you did and what exactly is not happening?

**Comment by nasmeshnick** [comment]
> Не могли бы вы уточнить, что именно вы сделали и чего именно не происходит?

what is not clear ? I write the mainloby command, I log on to the server and the point is not saved secondly, why is there no quick death in the lobby when I fall from the world ?

**Comment by Misat11** [comment]
So your point is that there's no quick death when falling off. Main lobby in SBW is a point where to teleport all players when the bedwars game ends. Nothing more. Addons like SBA may add more features to main lobby, but that's not related to this plugin.
