### ISSUE TITLE
[Bug]: choice team menu in lobby

### ISSUE THREAD

**Issue by KuroiNekOo** [ScreamingSandals/BedWars#509]
### Bug description

There's a very annoying bug, so I'll try to explain the problem as best I can and then give you a story to help you understand. 

When a player clicks on the item to choose a team in the lobby and other people are in the menu at the same time, they won't be able to choose a team.

In fact, only the first person to choose a team will have a team, but the others will have to leave the menu and reopen it, and this will continue until everyone has a team.

This is very annoying, as it means that each player will have to leave and re-open the menu every time someone chooses a team before him/her.

You have to watch the video to understand :
 - https://streamable.com/oxby15

### BedWars dump (can be obtained via `/bw dump`)

https://paste.gg/565a89d7058242eaa27f45d5c5948ed5

### Console log

[latest.log](https://github.com/ScreamingSandals/BedWars/files/12653936/latest.log)

### Additional information

Version server: 1.20.1 (PaperSpigot) (Build 97)
Version plugin: 0.2.29
Version addon SBA: 1.5.11

![plugins](https://github.com/ScreamingSandals/BedWars/assets/65861828/bca1ccd8-8702-4761-99f2-16fd37108fd1)

**Comment by KuroiNekOo** [comment]
Correctif is good : https://repo.screamingsandals.org/snapshots/org/screamingsandals/bedwars/BedWars/0.2.30-SNAPSHOT/BedWars-0.2.30-20230921.200918-16.jar

**Comment by Misat11** [comment]
I'm closing this issue since it is inactive and since creation it was already fixed. If you still have the issue on latest SBW version, please reopen the issue.
