### ISSUE TITLE
Resource drop limit

### ISSUE THREAD

**Issue by TATyKeFei** [ScreamingSandals/BedWars#515]
### Feature description

When there are too many resource generation drops and no one picks them up, it will cause the server to get stuck and the TPS will be reduced, so I want a resource generation limit feature!!

### Is your feature request related to a problem?

Resource drop limit

**Comment by Misat11** [comment]
`/bw admin <arena> spawner add <bronze|gold|iron> [hologram] [first level] [name] [team] [max spawned resources]` (The team parameter can be omitted)

or edit the arena file, the property is called maxSpawnedResoueces
