### ISSUE TITLE
Modify ressource don’t change the translation 

### ISSUE THREAD

**Issue by FewerElk** [ScreamingSandals/BedWars#517]
### Bug description

When I change the ressource (ex: bronze —> iron, iron —> diamond, gold —> emerald), the translation isn’t changed (here French translation):
![image](https://github.com/ScreamingSandals/BedWars/assets/120582916/4c4f0e14-0925-4ddc-a1f4-2bd8cbb6ffb0)
(Sorry I haven’t better screen)
<img width="414" alt="image" src="https://github.com/ScreamingSandals/BedWars/assets/120582916/ea5909e3-2f38-49d7-aedc-2585d8f561ae">

**Comment by zlataovce** [comment]
you need to change the translation key as well - the `translate` property, see [the documentation](https://docs.screamingsandals.org/BedWars/latest/config/#custom-resources)
