### ISSUE TITLE
[Bug]: Need OP to join game

### ISSUE THREAD

**Issue by lmaoNebula** [ScreamingSandals/BedWars#519]
### Bug description

Um i have a problem but idk if its SBA or this only plugin but im just gonna put it here.
to join the game ( sign that says: [bedwars] arenaname) the player has to be opped
is there a way to make everybody a player by default or a way to make the sign available to non-ops?

**Comment by Misat11** [comment]
https://docs.screamingsandals.org/BedWars/latest/troubleshooting/#non-op-players-cannot-use-signs

**Comment by lmaoNebula** [comment]
thank you
