### ISSUE TITLE
[Bug]: When the game "Bed Wars" starts on my Aternos server, crashes from the server

### ISSUE THREAD

**Issue by 1501milan** [ScreamingSandals/BedWars#522]
### Bug description

When the game "Bad Wars" starts on my Aternos server (version 1.20.1), it crashes from the server with the error **"Internal Exception: io.netty.handler.codec.decoderException: java.io.IOException: Packet 0/88 (ус) was larger then i expected, found 1 bytes extra whilst reading packet 88"** I don’t know what to do, I’m using TLanucher, dns reset the cache, reinstalled the version, nothing helps, in the console and in the log it doesn’t write anything, I logged in via a Dynamic IP address, it doesn’t help, and I immediately say that I’m from Ukraine, so the language is Ukrainian, so as not to confuse you
![Снимок экрана (217)](https://github.com/ScreamingSandals/BedWars/assets/159242946/32753678-26cf-46c1-8b31-79dfd437de7c)
![Снимок экрана (218)](https://github.com/ScreamingSandals/BedWars/assets/159242946/0d1189e8-1b7f-4e8e-85a0-2792b0742769)

### BedWars dump (can be obtained via `/bw dump`)

https://paste.gg/2579784b0b5d41e3911c8fa44af0edf8

### Additional information

**Minecraft version 1.20.1 plugin (Screaming Bedwars) version 0.2.31**
All plugins of server: ScreamingBedWars, SBA: Screaming Bedwars Addon, Chatty, DeluxeHub, Essentials, GSit, HubThat, Multiverse-Core, LuckPerms, MyCommand, NametagEdit, PlaceholderAPI, ServerNPC, Shopkeepers, Silkspawners, SkinRestorer, SystemSpawns, Vault (vault due to the fact that it is not updated from version 1 16, I installed it, maybe it needs to be removed since it is an incompatible version), ViaVersion, WanderingTrades, WorldEdit, WorldGuard.

**Comment by fruhansen** [comment]
got this one too please anyone help!

**Comment by Misat11** [comment]
For now, please disable these two options (set them to false) in sbaconfig.yml:
```yaml
show-health-in-tablist: false
show-health-under-player-name: false
```

**Comment by Misat11** [comment]
A new version of SBA (1.5.12.4) has been released containing the fix for this bug. Thank you for reporting.
