### ISSUE TITLE
[Bug]: Stats disappear after rejoin

### ISSUE THREAD

**Issue by SirvydasS** [ScreamingSandals/BedWars#526]
### Bug description

Stats disappear after the game is played and when rejoining server.
1. Check stats /bw stats.
2. Play game
3. Relog to server
4. Check stats /bw stats (is gone)

### BedWars dump (can be obtained via `/bw dump`)

https://paste.gg/6e952f74c79548cf90db2ec1ee9f4072

### Additional information

In file bw_stats_players stats remaining. And after server restart stats will be back.
https://streamable.com/ljplxe

**Comment by Misat11** [comment]
Can you try latest snapshot from https://github.com/ScreamingSandals/BedWars/actions/workflows/build-0-2-x.yml ?
