### ISSUE TITLE
[Bug]: Respawn at Mainlobby (/bw mainlobby)

### ISSUE THREAD

**Issue by Razorxd1993** [ScreamingSandals/BedWars#527]
### Bug description

Unfortunately there is the problem that if you fall down or die, you are sent to the Bedwars main lobby spawn point and the game ends.
Allow-Fake-Deaths is active, but unfortunately it doesn't help.
It can't be due to another spawnpoint plugin, ViaVersion or CMI, as you are teleported to the exact point of the specified BW main lobby point.

How can this be fixed?
Kind regards

Pupur 1.20.1

### BedWars dump (can be obtained via `/bw dump`)

https://paste.gg/p/anonymous/49557ff427804cdd8bdca5abf1729250

### Console log

No errors in the log or console

**Comment by Razorxd1993** [comment]
my fail found the issue ^^

**Comment by Flick0s** [comment]
I have this problem too but i dont know how to solve it can u help me please?

**Comment by Flick0s** [comment]
> my fail found the issue ^^

What is the issue PLEASE
