### ISSUE TITLE
[Bug]: The scoreboards and leaderboards keep resetting

### ISSUE THREAD

**Issue by Agron12MC** [ScreamingSandals/BedWars#530]
### Bug description

My scoreboards stats and leaderboards keep resetting. Please do suggest a way to save all the data of the stats and leaderboards

**Comment by Misat11** [comment]
The fix is currently available in the snapshot versions of BedWars 0.2.32 https://github.com/ScreamingSandals/BedWars/actions/workflows/build-0-2-x.yml

**Comment by Agron12MC** [comment]
how do i install the snapshot into my server. im using aternos as a server hosting service.
