### ISSUE TITLE
How to install New snapshots of Screaming Bedwars Into an ATenros Server.

### ISSUE THREAD

**Issue by Agron12MC** [ScreamingSandals/BedWars#531]
### Bug description

idk how p[las help through a step by step guide

**Comment by Misat11** [comment]
Whether or not and how can you install custom JARs depends on the hosting and selected plan. This is completely unrelated to us.

We are going to release a new version of BedWars next week, which will contain the fix for #530, that release will be available on SpigotMC and therefore Aternos.
