### ISSUE TITLE
[Bug]: block placing on bed

### ISSUE THREAD

**Issue by animy13** [ScreamingSandals/BedWars#532]
### Bug description

when you place a block on a bed without shift and it is only one block, the block doesn't disappear
SBW
Minecraft version 1.8

https://github.com/ScreamingSandals/BedWars/assets/168905229/61f9e625-91fe-4fd7-a4ab-4f33ab32df66

### BedWars dump (can be obtained via `/bw dump`)

https://paste.gg/413402e53c7347098bd538be8d77233e

**Comment by Misat11** [comment]
Should be fixed in latest build:
https://github.com/ScreamingSandals/BedWars/actions/workflows/build-0-2-x.yml
