### ISSUE TITLE
[Bug]: Respawn at mainlobby

### ISSUE THREAD

**Issue by Flick0s** [ScreamingSandals/BedWars#536]
### Bug description

Unfortunately there is the problem that if you fall down or die, you are sent to the Bedwars main lobby spawn point and the game ends.
And i dont know what to do

**Comment by Misat11** [comment]
Some plugin probably overrides the respawn, I'd check the configuration of every plugin which has something to do with respawning, like a world management plugin or plugins such as EssentialsSpawn. You have not provided any information, so I cannot help you more.
