### ISSUE TITLE
[Feature]: Support for Custom Items & Blocks (Items with NBT Tags)

### ISSUE THREAD

**Issue by pmgalileo** [ScreamingSandals/BedWars#541]
### Feature description

I want to use a custom block as a target block, and it works during the first game until the custom blocks are destroyed. After that, they do not regenerate. Only string (miencraft:string) used as a base for the custom item regenerates.

### Is your feature request related to a problem?

The issue is that I can't regenerate custom target blocks. I'm not sure if this problem is related to the BedWars plugin or the SlimeWorldManager.

**Comment by Misat11** [comment]
Duplicate of #419 and #510.

SBW does not support block entities as target block nor as breakable block besides standard containers like chest.
