### ISSUE TITLE
[Bug]: The shop.yml does Not Work.

### ISSUE THREAD

**Issue by yucdRPG** [ScreamingSandals/BedWars#544]
### Bug description

Use BedWars-0.2.33.1.jar.
I changed the prices of many items in shop.yml and added many new items.
But when I enter the game, shop.yml does not take effect.
I have deleted all leather armor, but I still see leather armor when I start the game.
turnOnExperimentalGroovyShop: false
Is it possible to roll back to an older version to avoid this problem?
If so, do I need to re-set it?

**Comment by Misat11** [comment]
You can completely reset the shop by removing the file and reloading bedwars/restarting server. I'd tell you what's wrong with your shop.yml if you have followed the issue template and sent the dump as requested.

**Comment by TEAMOBAYBY** [comment]
ERROR DESCRIPTION:
I can't open the villagers, I can't access the shop even though the villagers are placed, I can't open them, please help me.

DESCRIPCIÓNDEL ERROR:
No puedo abrir los aldeanos, no puedo acceder a la tienda a pesar de que los aldeanos se encuentren colocados, no puedo abrirlos, ayúdeme por favor.
