### ISSUE TITLE
[Feature]: Multiple prices on one item in a shop

### ISSUE THREAD

**Issue by hiyokochicken** [ScreamingSandals/BedWars#545]
### Feature description

I would like to see a feature added that allows you to purchase items with multiple types of ore at the shop.
If it already exists, I would like to know how to do it.
For example, I would like to sell a diamond sword for 4 emeralds and 4 diamonds.
I'm Japanese and I'm not good at English, so I used Google Translate.
I'm sorry if the text is difficult to understand.
Thank you for reading.

**Comment by Misat11** [comment]
Closing as a duplicate of #480
