### ISSUE TITLE
Warnings being spammed during a game

### ISSUE THREAD

**Issue by BlueNightFury46** [ScreamingSandals/BedWars#549]
### Bug description

During a bedwars game these logs get sent, players are also unable to break beds.
![Screenshot_20240907_174245_Ecosia](https://github.com/user-attachments/assets/3e5caa64-d12d-4b5d-a209-40f87417d569)

![Screenshot_20240907_173221_Ecosia](https://github.com/user-attachments/assets/b8baa26d-a0e4-452f-a991-5d7db299933d)

### BedWars dump (can be obtained via `/bw dump`)

https://paste.gg/p/anonymous/2de2acd8d1de4170a1035d37d581ebfb

### Console log

Shown in the images above

### Additional information

It's running version 2.34 and I'm using PerWorldPlugins to disable everything else to avoid conflicts

**Comment by Misat11** [comment]
Based on the logs and provided /bw dump, you are not running 0.2.34, but 0.2.31, which did not support 1.21.

**Comment by BlueNightFury46** [comment]
That's peculiar, I went off of the version listed after running /bw reload
