### ISSUE TITLE
[Bug]: Could not find game

### ISSUE THREAD

**Issue by mohammadbs1** [ScreamingSandals/BedWars#553]
### Bug description

i created and saved 1 area but when i click on a npc and click to play "could not find game" send for me in chat 
paper 1.8.8

**Comment by yeying-xingchen** [comment]
You are use SBA.Please run "/sba gamesinv"

**Comment by Misat11** [comment]
You have not provided all necessarry information you were asked for, and as such we are not able to help you. Please follow the issue template.
