### ISSUE TITLE
[Bug]: When I put Viaversion, ViaBackwards, and ViaRewind on a 1.21.3 PaperMC server, versions 1.19.2 and lower give an error and disconnect at start.

### ISSUE THREAD

**Issue by YOMA8338** [ScreamingSandals/BedWars#555]
### Bug description

When starting Bedwars on a PaperMC 1.21.3 server with ViaVersion, ViaBackwards, and ViaRewind, versions lower than 1.19.3 are forced to disconnect with an error.

### Additional information

https://github.com/ViaVersion/ViaBackwards/issues/929#issuecomment-2555998333
I reported it here and was told that the problem seems to be on the ScreamingBedWars side.

**Comment by Misat11** [comment]
I believe that this is a regression in recent ViaBackwards versions since SBW 0.2.x does not even directly send packets besides creating display entity holograms (which didn't exist in 1.19.2 btw, but ViaBackwards used to convert them just fine). It may also be a problem with SBA. I'll test it and check the origin of that issue.

**Comment by Misat11** [comment]
I have tried creating a 1.21.3 Paper server with latest snapshot versions of ViaVersion (5.2.1-SNAPSHOT) and ViaBackwards (5.2.1-SNAPSHOT), SBW 0.2.36 and SBA 1.5.13.6 (you have 1.5.13.5). I connected using two 1.19.2 clients and I was not able to reproduce your issue. I have also tried downgrading Via* plugins to 5.2.0 and SBA to 1.5.13.5, so I have the exact same versions as you, and I didn't have any crash.

I looks like an incompatibility with other plugin you have installed and you have a lot of plugins. Try running your server without any plugins but Via*, SBW and SBA (and possibly connect using vanilla client), and try adding plugins one by one until the issue returns. If the issue still persists using only Via* and BedWars, please provide more specific steps to reproduce the issue, /bw dump, and console logs. 

You have an outdated ProtocolLib btw, for 1.21.3 you have to use 5.4.0, not 5.3.0.

The client logs show that the client has received an unknown packet with ID 120. This ID is unused by 1.19.2, but is present in modern versions as 'Set Ticking State' (related to the /tick command), tho I don't know why would any plugin send that packet. In 1.21.1 it was 'Update Tags', which honestly makes more sense.

**Comment by YOMA8338** [comment]
When I tried, the error occurred even with only Viaversion, ViaBackwards, ViaRewind, Bedwars, and SBA, but when I disabled SBA, the error stopped occurring.
I will report the problem with SBA.
