### ISSUE TITLE
Scoreboard flickers

### ISSUE THREAD

**Issue by DevYorma** [ScreamingSandals/BedWars#59]
**Describe the bug**
Scoreboard in Lobby is flickering.

**Server and plugin version**
Spigot version: git-Paper-209 (MC: 1.14.4)
BedWars version: 0.2.2-SNAPSHOT-344

**Installed plugins on server (can be obtained by `/pl`):**
BedWars, HolographicDisplays, LuckPerms, Matrix, Multiverse-Core, PlaceholderAPI, PlugMan, PremiumVanish, ProtocolLib, Skellett, Skript, skript-mirror, Skungee, skUtilities, TAB, Tablisknu, TuSKe, WorldEdit, WorldGuard

**Console log:**
-

**Configuration (of config.yml and shop.yml):**
Config.yml: https://hastebin.com/nayiwurini.cs
Shop.yml: https://hastebin.com/uvitepewew.bash

**If there are problem with only one game, paste here config of this game:**
-

**Comment by DevYorma** [comment]
Video:
https://youtu.be/saCGY_gTxsk

**Comment by Misat11** [comment]
Is this bug still present or can I close it?

**Comment by DevYorma** [comment]
Yes, it's still there.

**Comment by iamceph** [comment]
Already fixed in 1.x.x. versions, 0.x.x will not get the new version

**Comment by DevYorma** [comment]
Do you recommend to use 1.x.x builds on production server?

**Comment by iamceph** [comment]
It's not ready yet
