### ISSUE TITLE
Custom Tablist

### ISSUE THREAD

**Issue by DevYorma** [ScreamingSandals/BedWars#60]
**Describe the solution you'd like**
Possibility to configure a custom tab (ingame and lobby) with placeholders like %teamcolor%, %remainingtime% or %map%

**Is your feature request related to a problem? Please describe.**
/

**Comment by SoCuul** [comment]
In recent versions of the plugin, PAPI placeholders have been introduced.

**Comment by iamceph** [comment]
He means per-player tablist, that will be in 1.x.x

**Comment by SoCuul** [comment]
If you use a custom tab list plugin, you can accomplish this task using the included placeholders or modifying them yourself.

**Comment by pronze** [comment]
Added in snapshot versions of 0.3.0
