### ISSUE TITLE
Join message is duplicate

### ISSUE THREAD

**Issue by DevYorma** [ScreamingSandals/BedWars#63]
**Describe the bug**
Join message is duplicate. (Spigot message doesn't get overwritten)
![grafik](https://user-images.githubusercontent.com/41928283/67144716-2c9e1400-f27a-11e9-95d0-840e7c724b7c.png)
Please remove the plugin's prefix in the join and leave messages.

**Server and plugin version**
Spigot version: git-Paper-209 (MC: 1.14.4)
BedWars version: 0.2.2-SNAPSHOT-344

**Installed plugins on server (can be obtained by `/pl`):**
BedWars, HolographicDisplays, LuckPerms, Matrix, Multiverse-Core, PlaceholderAPI, PlugMan, PremiumVanish, ProtocolLib, Skellett, Skript, skript-mirror, Skungee, skUtilities, TAB, Tablisknu, TuSKe, WorldEdit, WorldGuard

**Console log:**
/

**Configuration (of config.yml and shop.yml):**
Config.yml: https://hastebin.com/nayiwurini.cs
Shop.yml: https://hastebin.com/uvitepewew.bash

**If there are problem with only one game, paste here config of this game:**
/

**Comment by Misat11** [comment]
Why spigot message should be overwritten by this plugin?
