### ISSUE TITLE
Possibility to customize team selector gui

### ISSUE THREAD

**Issue by DevYorma** [ScreamingSandals/BedWars#65]
**Describe the solution you'd like**
Possibility to customize team selector gui e.g. to be able to translate the sentence below or change the design.
![grafik](https://user-images.githubusercontent.com/41928283/67144878-450f2e00-f27c-11e9-85b9-dab877760090.png)

**Is your feature request related to a problem? Please describe.**
/

**Comment by iamceph** [comment]
You can, messages_en or so. Different design is not possible.

**Comment by iamceph** [comment]
Probably TODO: make wools changeable
