### ISSUE TITLE
Maps do not reset and villagers are normal farmers/shop doesn't work

### ISSUE THREAD

**Issue by Sora2419** [ScreamingSandals/BedWars#68]
**Describe the bug**
About two weeks ago, the maps stopped working. Simply put, the maps would not reset for some odd reason. Furthermore, the shop would not show when clicking on the villagers, but regular trades.

**Server and plugin version**
Paper version: 1.14.4
BedWars version:0.2.1

**Installed plugins on server (can be obtained by `/pl`):**

BattleArena | Directory |   | 2019-09-13 01:16 |  
-- | -- | -- | -- | --
  |   | BattleTracker | Directory |   | 2019-09-24 21:09 |  
  |   | BedWars | Directory |   | 2019-10-19 03:11 |  
  |   | CMI | Directory |   | 2019-10-19 15:54 |  
  |   | ChatControl | Directory |   | 2019-10-18 23:51 |  
  |   | HideAndSeek | Directory |   | 2019-09-20 15:42 |  
  |   | IPWhitelist | Directory |   | 2019-04-05 00:16 |  
  |   | LibsDisguises | Directory |   | 2019-09-20 01:42 |  
  |   | LuckPerms | Directory |   | 2019-09-11 00:06 |  
  |   | Multiverse-Core | Directory |   | 2019-10-19 00:05 |  
  |   | Nicky | Directory |   | 2019-09-11 00:02 |  
  |   | PlaceholderAPI | Directory |   | 2019-09-10 23:58 |  
  |   | PluginMetrics | Directory |   | 2019-09-10 23:58 |  
  |   | ProtocolLib | Directory |   | 2019-10-19 12:00 |  
  |   | RedProtect | Directory |   | 2019-10-19 03:49 |  
  |   | Skywars | Directory |   | 2019-09-16 00:56 |  
  |   | Spleef | Directory |   | 2019-09-24 21:40 |  
  |   | TNTRun_reloaded | Directory |   | 2019-09-26 23:53 |  
  |   | TitleManager | Directory |   | 2019-09-20 03:51 |  
  |   | Vault | Directory |   | 2019-09-10 23:58 |  
  |   | ViaRewind | Directory |   | 2019-09-10 23:58 |  
  |   | ViaVersion | Directory |   | 2019-09-10 23:57 |  
  |   | VoidGenerator | Directory |   | 2019-10-18 23:41 |  
  |   | WorldEdit | Directory |   | 2019-09-13 17:32 |  
  |   | iDisguise | Directory |   | 2019-09-19 02:31 |  
**Console log:**
No errors show up in the console
**Configuration (of config.yml and shop.yml):**
[https://pastebin.com/7cdhk1g1](url) {config.yml}
[https://pastebin.com/mH5UyUZr](url) {shop.yml}

**Comment by tjd2** [comment]
Try updating PaperSpigot.
It solved my problem (villager shop wasn't opening)

**Comment by Sora2419** [comment]
I did that and it fixed my issue.
