### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Nety01** [ScreamingSandals/BedWars#83]
#### Describe the bug
I got this console error when player joined: https://hastebin.com/agowoselam.cs
I don't know why, because I don't use this plugin yet, only have it in plugins folder.

#### Server and plugin version
Spigot version: Paper 1.13.2
BedWars version: 0.2.2

#### Installed plugins on server (can be obtained by `/pl`)
AuthMe, BanManager*, BedWars, BetterChairs*, BKCommonLib, BuildersUtilities, ChatManager, ChestShop, Citizens, CitizensCMD, ClearLag, ColoredAnvils*, CustomHeads*, DeathMessagesPrime, DeluxeMenus, DiscordSRV, EditableSign, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FakaHedaMinequery*, FastAsyncWorldEdit, goBrush, goPaint, HolographicDisplays, Horizon, ImageOnMap, ItemMagnet*, Jobs, LightCleaner, LogBlock, LuckPerms, LWC, Minepacks, Multiverse-Core, MyCommand, PixelVip*, PlaceholderAPI, ProtocolLib*, RandomTP, Residence, SkinsRestorer, SuperbVote, SuperVanish, TabList, uKitPvP*, UltimateHomes*, Vault, Votifier, WorldBorder, WorldEdit

#### Configuration (of config.yml and shop.yml)
Default config

**Comment by Misat11** [comment]
this error is very unusual, have you latest build of your Paper (there is newer build of 1.13.2 Paper)

**Comment by Nety01** [comment]
Well, I have the one before newest. Build 651. I will update it as soon as possible to Build 652.
