### ISSUE TITLE
KD is not rounded

### ISSUE THREAD

**Issue by DevYorma** [ScreamingSandals/BedWars#87]
#### Describe the bug
The KD is not rounded in statistics.
![unknown](https://user-images.githubusercontent.com/41928283/68427589-b6227100-01aa-11ea-88cb-c3647212bd07.png)

#### Server and plugin version
Spigot version: Paper-223 (1.14.4)
BedWars version: 0.2.3-SNAPSHOT-403

#### Installed plugins on server (can be obtained by `/pl`)
Plugins (26): BedWars, LuckPerms, Matrix, Multiverse-Core, PlaceholderAPI, PlugMan, PremiumVanish, ProtocolLib, ReplaySystem, Skellett, Skore, Skript, skript-db, skript-mirror, Skungee, skUtilities, TAB, Tablisknu, TitleManager, TuSKe, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion*, WorldEdit, WorldGuard

#### Console log
/

#### Configuration (of config.yml and shop.yml)
config.yml: https://hastebin.com/ecaqawahus.cs
shop.yml: https://hastebin.com/zodawupohu.bash

#### If there are problem with only one game, paste here config of this game
/

**Comment by Misat11** [comment]
try latest jenkins build and tell us if bug still persists
