### ISSUE TITLE
Party System

### ISSUE THREAD

**Issue by IsXGeo** [ScreamingSandals/BedWars#93]
I would like a way for players to join games together with parties or groups to be on the same team.

**Comment by Bbro122** [comment]
I believe this would be possible using some logic and a plugin such as skript

**Comment by AfkF24** [comment]
Not everyone uses Skript. This should be a nice touch to the plugin, nonetheless.

**Comment by Bbro122** [comment]
Also due to data I wasn't able to say it at first.
It would be best to leave the party system to a actual party plugin and only ask for a hook system so that minigames that have could all be available for this

**Comment by iamceph** [comment]
If you know any party system that hooks  into minigames, send it out and we can look into it. :)

**Comment by Bbro122** [comment]
I'll look around when I get the chance

**Comment by DevYorma** [comment]
I think the most common one is PAF:
Bungee version: https://www.spigotmc.org/resources/party-and-friends-for-bungeecord.9531/
Spigot version: https://www.spigotmc.org/resources/party-and-friends-extended-for-spigot-supports-1-7-1-15-2.11633/

**Comment by pronze** [comment]
Added, use Parties from AlessioDP with the latest snapshot of BedWars to use this feature.
