### ISSUE TITLE
1.15 update

### ISSUE THREAD

**Issue by stuee147** [ScreamingSandals/BedWars#95]
hi i have tested your plugin on 1.15 and it mostly works as good as in 1.14.4 but for a couple of small things, 
firstly armor stands show floating above beds and spawners. and secondly mobs spawn in the arenas at night causeing problems i hope these are easy fixes as the plugin is awsome and i would love to use it on my 1.15 sever
thanks 
stuee

**Comment by Misat11** [comment]
ok, so the thing with armor stand was fixed and now fix is available in dev builds.

**Comment by Misat11** [comment]
and about second thing I'll need more informations such as errors in console, other plugins etc. because I can't reproduce your bug. Did you update all your plugins when you test new version?

**Comment by stuee147** [comment]
i didnt get any error codes in the console for the mobs spawning it was on my test server where i have the arena about 30 or so blocks above the join sign and i had been in the area for a while and seen mobs spawning on the arena platforms when i joined the game the mobs were spawning bellow the lobby and i could see them spawn in the night from the lobby when the game started the mobs stayed and attacked my two players its not a real issue for me to be honest as i can put a WG region around the arena on my main server and prevent mob spawning.
i have just run it again on my test server and there is no console warnings at all or any errors but mobs are spawning on the platforms
where can i find the dev build so i can test it ?

**Comment by stuee147** [comment]
ok im being daft i have the dev build and its working great apart from the hostile mobs spawning on the arena platforms at night and attacking the players there is no info or errors coming up on the console i have copied the console during the time i was testing the game maybe im missing something hope this helps let me know if i can help with anything 
stuee
[running bedwars.txt](https://github.com/ScreamingSandals/BedWars/files/3957573/running.bedwars.txt)

**Comment by Misat11** [comment]
ok try latest dev build, before trying it you should remove all mobs, that shouldn't be here. Note that plugin protects only area marked with pos1 and pos2, so there shouldn't be way how hostile mobs can go here. The error that you sent me in text file is not linked with BedWars.

**Comment by stuee147** [comment]
i didnt think any of the console was referring to bedwars i know what the two errors are that show on the console and they have been sorted on my main server i have tested the dev build on my test server and while i was in game at night i still had a few mobs spawn on the centre island before a player got to it i will set up a arena on my main server and see if that works any better i will let you know how it goes i have set the pos1 and pos2 area so all islands are withing the area and have several blocks space in all directions past the arena zone

**Comment by stuee147** [comment]
ive been testing it on my main server now and iv had no problems with mobs spawning at all thanks for your help keep up the great work
